#!/usr/bin/env python3
"""Run ActPlane RQ2 syscall microbenchmarks.

The runner builds the C benchmark, generates no-hit policies for AP rule-count
configurations, runs repeated trials, and writes raw/aggregate records suitable
for paper tables and artifact review.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import platform
import statistics
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
PERF_DIR = Path(__file__).resolve().parent
DEFAULT_ACTPLANE = ROOT / "target" / "release" / "actplane"
DEFAULT_BENCH = PERF_DIR / "build" / "syscall_microbench"

OPS = ["open", "write", "connect", "fork", "exec"]
DEFAULT_ITERS = {
    "open": 100_000,
    "write": 100_000,
    "connect": 100_000,
    "fork": 20_000,
    "exec": 10_000,
}
SMOKE_ITERS = {op: 50 for op in OPS}


@dataclass(frozen=True)
class PerfConfig:
    name: str
    rules: int
    sources: int
    transforms: int


CONFIGS = {
    "ap-1": PerfConfig("ap-1", rules=1, sources=2, transforms=0),
    "ap-10": PerfConfig("ap-10", rules=10, sources=5, transforms=0),
    "ap-32": PerfConfig("ap-32", rules=32, sources=16, transforms=8),
    "ap-100": PerfConfig("ap-100", rules=100, sources=32, transforms=16),
}


def utc_stamp() -> str:
    return (
        datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
        .replace(":", "")
    )


def run(
    cmd: list[str],
    cwd: Path = ROOT,
    timeout: int = 600,
    env: dict[str, str] | None = None,
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=cwd,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=timeout,
    )


def run_checked(cmd: list[str], cwd: Path = ROOT, timeout: int = 600) -> str:
    proc = run(cmd, cwd=cwd, timeout=timeout)
    if proc.returncode != 0:
        raise RuntimeError(
            f"command failed ({proc.returncode}): {' '.join(cmd)}\n"
            f"stdout:\n{proc.stdout}\nstderr:\n{proc.stderr}"
        )
    return proc.stdout.strip()


def parse_csv_arg(value: str) -> list[str]:
    return [x.strip() for x in value.split(",") if x.strip()]


def parse_iterations(value: str | None, smoke: bool) -> dict[str, int]:
    if smoke:
        return dict(SMOKE_ITERS)
    iters = dict(DEFAULT_ITERS)
    if not value:
        return iters
    if "=" not in value:
        n = int(value)
        return {op: n for op in OPS}
    for item in parse_csv_arg(value):
        op, raw = item.split("=", 1)
        op = op.strip()
        if op not in OPS:
            raise ValueError(f"unknown op in --iterations: {op}")
        iters[op] = int(raw)
    return iters


def build_benchmark(bench_bin: Path) -> None:
    bench_bin.parent.mkdir(parents=True, exist_ok=True)
    src = PERF_DIR / "syscall_microbench.c"
    cmd = [
        "cc",
        "-O2",
        "-Wall",
        "-Wextra",
        "-std=c11",
        str(src),
        "-o",
        str(bench_bin),
    ]
    run_checked(cmd, cwd=ROOT)


def build_actplane() -> None:
    run_checked(
        ["cargo", "build", "--release", "-p", "actplane"],
        cwd=ROOT,
        timeout=1200,
    )


def generate_policy(cfg: PerfConfig) -> str:
    lines = [
        "version: 1",
        "policy: |",
        "  # Generated by docs/rq2-performance/run_perf.py.",
        "  # No-hit policy: the benchmark subtree is labeled, but rule targets",
        "  # are deliberately unreachable so no violation/reporting cost is included.",
        '  source COMMAND = exec "**"',
    ]
    for i in range(1, cfg.sources):
        lines.append(f'  source L{i} = file "/tmp/actplane-perf/source-{i}"')
    for i in range(cfg.transforms):
        label = f"L{1 + (i % max(1, cfg.sources - 1))}"
        lines.append(f'  declassify {label} by exec "__actplane_clear_{i}"')

    op_cycle = ["open", "write", "connect", "exec"]
    for i in range(cfg.rules):
        op = op_cycle[i % len(op_cycle)]
        expr = "COMMAND"
        if cfg.sources > 1:
            expr = f"COMMAND and not L{1 + (i % (cfg.sources - 1))}"
        lines.append(f"")
        lines.append(f"  rule perf-nohit-{i}:")
        if op == "open":
            lines.append(
                f'    notify open file "/tmp/actplane-perf/nohit/open-{i}" if {expr}'
            )
        elif op == "write":
            lines.append(
                f'    notify write file "/tmp/actplane-perf/nohit/write-{i}" if {expr}'
            )
        elif op == "connect":
            octet = 1 + (i % 250)
            lines.append(f'    notify connect endpoint "203.0.113.{octet}" if {expr}')
        else:
            lines.append(f'    notify exec "__actplane_nohit_{i}" if {expr}')
        lines.append('    because "performance no-hit rule"')
    return "\n".join(lines) + "\n"


def write_policies(config_names: list[str], policy_dir: Path) -> dict[str, Path]:
    policy_dir.mkdir(parents=True, exist_ok=True)
    out: dict[str, Path] = {}
    for name in config_names:
        if name == "baseline":
            continue
        cfg = CONFIGS[name]
        path = policy_dir / f"{name}.yaml"
        path.write_text(generate_policy(cfg), encoding="utf-8")
        out[name] = path
    return out


def read_first_line(path: Path) -> str:
    try:
        with path.open(encoding="utf-8", errors="replace") as f:
            return f.readline().strip()
    except OSError:
        return ""


def metadata(args: argparse.Namespace, out_dir: Path) -> dict[str, Any]:
    cpu_model = ""
    try:
        for line in Path("/proc/cpuinfo").read_text(errors="replace").splitlines():
            if line.startswith("model name"):
                cpu_model = line.split(":", 1)[1].strip()
                break
    except OSError:
        pass

    governor = ""
    if args.cpu is not None:
        governor = read_first_line(
            Path(f"/sys/devices/system/cpu/cpu{args.cpu}/cpufreq/scaling_governor")
        )

    def maybe_cmd(cmd: list[str]) -> str:
        proc = run(cmd, cwd=ROOT, timeout=30)
        return proc.stdout.strip() if proc.returncode == 0 else ""

    git_status = maybe_cmd(["git", "status", "--porcelain"])
    return {
        "created_at": utc_stamp(),
        "root": str(ROOT),
        "output_dir": str(out_dir),
        "argv": sys.argv,
        "platform": platform.platform(),
        "uname": platform.uname()._asdict(),
        "cpu_model": cpu_model,
        "cpu_count": os.cpu_count(),
        "pinned_cpu": args.cpu,
        "cpu_governor": governor,
        "active_lsms": read_first_line(Path("/sys/kernel/security/lsm")),
        "git_rev": maybe_cmd(["git", "rev-parse", "HEAD"]),
        "git_dirty": bool(git_status),
        "git_status_porcelain": git_status,
        "actplane": str(args.actplane),
        "benchmark_binary": str(args.bench_bin),
    }


def parse_benchmark_stdout(stdout: str) -> list[dict[str, Any]]:
    records = []
    for line in stdout.splitlines():
        line = line.strip()
        if not line.startswith("{"):
            continue
        try:
            rec = json.loads(line)
        except json.JSONDecodeError:
            continue
        if rec.get("benchmark") == "syscall_microbench":
            records.append(rec)
    return records


def bench_command(
    bench_bin: Path,
    op: str,
    iterations: int,
    warmup: int,
    tmpdir: Path,
    cpu: int | None,
    raw_path: Path | None,
) -> list[str]:
    cmd = [
        str(bench_bin),
        "--json",
        "--op",
        op,
        "--iterations",
        str(iterations),
        "--warmup",
        str(warmup),
        "--tmpdir",
        str(tmpdir),
    ]
    if cpu is not None:
        cmd += ["--cpu", str(cpu)]
    if raw_path is not None:
        cmd += ["--raw", str(raw_path)]
    return cmd


def run_trial(
    args: argparse.Namespace,
    out_dir: Path,
    policies: dict[str, Path],
    config: str,
    op: str,
    repeat: int,
    iterations: int,
    warmup: int,
) -> list[dict[str, Any]]:
    tmpdir = out_dir / "tmp" / config / op / f"r{repeat}"
    tmpdir.mkdir(parents=True, exist_ok=True)
    raw_path = None
    if args.raw_samples:
        raw_path = out_dir / "raw" / f"{config}-{op}-r{repeat}.csv"
        raw_path.parent.mkdir(parents=True, exist_ok=True)
        raw_path.write_text("op,iteration,latency_ns\n", encoding="utf-8")

    target_cmd = bench_command(
        args.bench_bin, op, iterations, warmup, tmpdir, args.cpu, raw_path
    )
    if config == "baseline":
        cmd = target_cmd
        cwd = ROOT
    else:
        cmd = [
            str(args.actplane),
            "--policy",
            str(policies[config]),
            "run",
            "--",
            *target_cmd,
        ]
        cwd = ROOT

    proc = run(cmd, cwd=cwd, timeout=args.timeout_s)
    logs = out_dir / "logs"
    logs.mkdir(parents=True, exist_ok=True)
    stem = f"{config}-{op}-r{repeat}"
    (logs / f"{stem}.stdout").write_text(proc.stdout, encoding="utf-8", errors="replace")
    (logs / f"{stem}.stderr").write_text(proc.stderr, encoding="utf-8", errors="replace")

    if proc.returncode != 0:
        raise RuntimeError(
            f"trial failed: config={config} op={op} repeat={repeat} rc={proc.returncode}\n"
            f"command: {' '.join(cmd)}\n"
            f"stdout log: {logs / (stem + '.stdout')}\n"
            f"stderr log: {logs / (stem + '.stderr')}"
        )

    records = parse_benchmark_stdout(proc.stdout)
    if not records:
        raise RuntimeError(f"no benchmark JSON records parsed for {stem}")
    for rec in records:
        rec.update(
            {
                "config": config,
                "repeat": repeat,
                "policy": str(policies.get(config, "")),
                "command": cmd,
                "stdout_log": str(logs / f"{stem}.stdout"),
                "stderr_log": str(logs / f"{stem}.stderr"),
            }
        )
    return records


def write_jsonl(path: Path, records: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, sort_keys=True) + "\n")


def write_runs_csv(path: Path, records: list[dict[str, Any]]) -> None:
    fields = [
        "config",
        "op",
        "repeat",
        "iterations",
        "warmup",
        "min_ns",
        "mean_ns",
        "p50_ns",
        "p90_ns",
        "p95_ns",
        "p99_ns",
        "p999_ns",
        "max_ns",
    ]
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        for rec in records:
            writer.writerow({k: rec.get(k, "") for k in fields})


def median(values: list[float]) -> float:
    return float(statistics.median(values)) if values else 0.0


def aggregate(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    by_key: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for rec in records:
        by_key.setdefault((rec["config"], rec["op"]), []).append(rec)

    agg: list[dict[str, Any]] = []
    metrics = ["mean_ns", "p50_ns", "p90_ns", "p95_ns", "p99_ns", "p999_ns", "max_ns"]
    baseline: dict[tuple[str, str], float] = {}
    for (config, op), group in sorted(by_key.items()):
        row: dict[str, Any] = {
            "config": config,
            "op": op,
            "repeats": len(group),
            "iterations": group[0]["iterations"],
            "warmup": group[0]["warmup"],
        }
        for metric in metrics:
            row[f"median_{metric}"] = median([float(g[metric]) for g in group])
        agg.append(row)
        if config == "baseline":
            for metric in metrics:
                baseline[(op, metric)] = row[f"median_{metric}"]

    for row in agg:
        op = row["op"]
        for metric in metrics:
            base = baseline.get((op, metric), 0.0)
            value = float(row[f"median_{metric}"])
            row[f"overhead_{metric}_pct"] = ((value / base) - 1.0) * 100.0 if base else ""
    return agg


def write_aggregate_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    fields = list(rows[0].keys())
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--actplane", type=Path, default=DEFAULT_ACTPLANE)
    parser.add_argument("--bench-bin", type=Path, default=DEFAULT_BENCH)
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument(
        "--configs", default="baseline,ap-1,ap-10,ap-32,ap-100"
    )
    parser.add_argument("--baseline-only", action="store_true")
    parser.add_argument("--ops", default="open,write,connect,fork,exec")
    parser.add_argument(
        "--iterations",
        help="Global N or comma list like open=100000,exec=10000.",
    )
    parser.add_argument("--warmup", type=int, default=1000)
    parser.add_argument("--repeats", type=int, default=5)
    parser.add_argument("--cpu", type=int)
    parser.add_argument("--raw-samples", action="store_true")
    parser.add_argument("--skip-build", action="store_true")
    parser.add_argument("--build-actplane", action="store_true")
    parser.add_argument("--timeout-s", type=int, default=900)
    parser.add_argument("--smoke", action="store_true")
    args = parser.parse_args()

    if args.smoke:
        args.repeats = 1
        args.warmup = 5
    if args.baseline_only:
        config_names = ["baseline"]
    else:
        config_names = parse_csv_arg(args.configs)
    for name in config_names:
        if name != "baseline" and name not in CONFIGS:
            raise SystemExit(f"unknown config: {name}")

    ops = parse_csv_arg(args.ops)
    for op in ops:
        if op not in OPS:
            raise SystemExit(f"unknown op: {op}")
    iterations = parse_iterations(args.iterations, args.smoke)

    out_dir = args.output_dir or (PERF_DIR / "results" / utc_stamp())
    out_dir.mkdir(parents=True, exist_ok=True)

    if not args.skip_build:
        build_benchmark(args.bench_bin)
    if args.build_actplane:
        build_actplane()
    if any(name != "baseline" for name in config_names) and not args.actplane.exists():
        raise SystemExit(
            f"actplane binary not found: {args.actplane}; run with --build-actplane"
        )

    policies = write_policies(config_names, out_dir / "policies")
    (out_dir / "metadata.json").write_text(
        json.dumps(metadata(args, out_dir), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    all_records: list[dict[str, Any]] = []
    for config in config_names:
        for op in ops:
            for repeat in range(1, args.repeats + 1):
                print(
                    f"[perf] config={config} op={op} repeat={repeat}/{args.repeats}",
                    flush=True,
                )
                recs = run_trial(
                    args,
                    out_dir,
                    policies,
                    config,
                    op,
                    repeat,
                    iterations[op],
                    args.warmup,
                )
                all_records.extend(recs)
                write_jsonl(out_dir / "runs.jsonl", all_records)

    write_runs_csv(out_dir / "runs.csv", all_records)
    agg = aggregate(all_records)
    (out_dir / "aggregate.json").write_text(
        json.dumps(agg, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    write_aggregate_csv(out_dir / "aggregate.csv", agg)
    print(f"[perf] wrote {out_dir}")
    print(f"[perf] aggregate {out_dir / 'aggregate.csv'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
