#!/usr/bin/env python3
"""Run ActPlane macro/end-to-end performance workloads.

The syscall microbench isolates individual hooks. This runner measures larger
commands that resemble real agent sessions: synthetic stress-ng OS pressure and
repository build/test workloads. It writes raw command logs and aggregate CSV/JSON
records for artifact review.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
PERF_DIR = Path(__file__).resolve().parent
DEFAULT_ACTPLANE = ROOT / "target" / "release" / "actplane"


@dataclass(frozen=True)
class PerfConfig:
    name: str
    rules: int
    sources: int
    transforms: int


CONFIGS = {
    "ap-1": PerfConfig("ap-1", rules=1, sources=2, transforms=0),
    "ap-10": PerfConfig("ap-10", rules=10, sources=5, transforms=0),
    "ap-32": PerfConfig("ap-32", rules=32, sources=16, transforms=8),
    "ap-100": PerfConfig("ap-100", rules=100, sources=32, transforms=16),
}


@dataclass(frozen=True)
class Workload:
    name: str
    argv: list[str]
    cwd: Path = ROOT
    env: dict[str, str] | None = None


def utc_stamp() -> str:
    return (
        datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
        .replace(":", "")
    )


def parse_csv_arg(value: str) -> list[str]:
    return [x.strip() for x in value.split(",") if x.strip()]


def run(
    cmd: list[str],
    cwd: Path = ROOT,
    timeout: int = 600,
    env: dict[str, str] | None = None,
) -> subprocess.CompletedProcess[str]:
    merged_env = os.environ.copy()
    if env:
        merged_env.update(env)
    return subprocess.run(
        cmd,
        cwd=cwd,
        env=merged_env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=timeout,
    )


def build_actplane() -> None:
    proc = run(
        ["cargo", "build", "--release", "-p", "actplane"],
        cwd=ROOT,
        timeout=1200,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"cargo build failed:\n{proc.stdout}\n{proc.stderr}")


def generate_policy(cfg: PerfConfig) -> str:
    lines = [
        "version: 1",
        "policy: |",
        "  # Generated by docs/rq2-performance/run_macro.py.",
        "  # No-hit policy: the workload subtree is labeled, but rule targets",
        "  # are deliberately unreachable so no violation/reporting cost is included.",
        '  source COMMAND = exec "**"',
    ]
    for i in range(1, cfg.sources):
        lines.append(f'  source L{i} = file "/tmp/actplane-macro/source-{i}"')
    for i in range(cfg.transforms):
        label = f"L{1 + (i % max(1, cfg.sources - 1))}"
        lines.append(f'  declassify {label} by exec "__actplane_macro_clear_{i}"')

    op_cycle = ["open", "write", "connect", "exec"]
    for i in range(cfg.rules):
        op = op_cycle[i % len(op_cycle)]
        expr = "COMMAND"
        if cfg.sources > 1:
            expr = f"COMMAND and not L{1 + (i % (cfg.sources - 1))}"
        lines.append("")
        lines.append(f"  rule macro-nohit-{i}:")
        if op == "open":
            lines.append(f'    notify open file "/tmp/actplane-macro/nohit/open-{i}" if {expr}')
        elif op == "write":
            lines.append(f'    notify write file "/tmp/actplane-macro/nohit/write-{i}" if {expr}')
        elif op == "connect":
            octet = 1 + (i % 250)
            lines.append(f'    notify connect endpoint "203.0.113.{octet}" if {expr}')
        else:
            lines.append(f'    notify exec "__actplane_macro_nohit_{i}" if {expr}')
        lines.append('    because "macro performance no-hit rule"')
    return "\n".join(lines) + "\n"


def write_policies(configs: list[str], out_dir: Path) -> dict[str, Path]:
    policy_dir = out_dir / "policies"
    policy_dir.mkdir(parents=True, exist_ok=True)
    out: dict[str, Path] = {}
    for name in configs:
        if name == "baseline":
            continue
        path = policy_dir / f"{name}.yaml"
        path.write_text(generate_policy(CONFIGS[name]), encoding="utf-8")
        out[name] = path
    return out


def metadata(args: argparse.Namespace, out_dir: Path) -> dict[str, Any]:
    def first_line(path: Path) -> str:
        try:
            return path.read_text(encoding="utf-8", errors="replace").splitlines()[0]
        except (OSError, IndexError):
            return ""

    def maybe(cmd: list[str]) -> str:
        proc = run(cmd, timeout=30)
        return proc.stdout.strip() if proc.returncode == 0 else proc.stderr.strip()

    return {
        "created_at": utc_stamp(),
        "argv": sys.argv,
        "root": str(ROOT),
        "output_dir": str(out_dir),
        "active_lsms": first_line(Path("/sys/kernel/security/lsm")),
        "uname": maybe(["uname", "-a"]),
        "cpu": maybe(["lscpu"]),
        "git_rev": maybe(["git", "rev-parse", "HEAD"]),
        "git_status_porcelain": maybe(["git", "status", "--porcelain"]),
        "actplane": str(args.actplane),
        "stress_ng_version": maybe(["stress-ng", "--version"]),
        "perf_status": maybe(["perf", "stat", "--", "true"]),
    }


def available_workloads(out_dir: Path) -> dict[str, Workload]:
    stress_tmp = out_dir / "stress-tmp"
    return {
        "agent-trace": Workload(
            "agent-trace",
            [
                sys.executable,
                str(PERF_DIR / "agent_trace_replay.py"),
                "--trace-root",
                str(ROOT / "docs/corpus-test"),
                "--variants",
                "compliant,violation",
            ],
            cwd=ROOT,
        ),
        "linux-build": Workload(
            "linux-build",
            [
                sys.executable,
                str(PERF_DIR / "linux_build_once.py"),
            ],
            cwd=ROOT,
        ),
        "stressng-open": Workload(
            "stressng-open",
            ["stress-ng", "--open", "4", "--open-ops", "400000", "--metrics-brief", "--times"],
            cwd=stress_tmp,
        ),
        "stressng-fork": Workload(
            "stressng-fork",
            ["stress-ng", "--fork", "4", "--fork-ops", "50000", "--metrics-brief", "--times"],
            cwd=stress_tmp,
        ),
        "stressng-exec": Workload(
            "stressng-exec",
            ["stress-ng", "--exec", "4", "--exec-ops", "10000", "--metrics-brief", "--times"],
            cwd=stress_tmp,
        ),
        "stressng-hdd": Workload(
            "stressng-hdd",
            [
                "stress-ng",
                "--hdd",
                "4",
                "--hdd-ops",
                "12000",
                "--hdd-bytes",
                "128M",
                "--temp-path",
                str(stress_tmp),
                "--metrics-brief",
                "--times",
            ],
            cwd=stress_tmp,
        ),
        "stressng-mixed": Workload(
            "stressng-mixed",
            [
                "stress-ng",
                "--open",
                "2",
                "--open-ops",
                "200000",
                "--fork",
                "2",
                "--fork-ops",
                "20000",
                "--exec",
                "2",
                "--exec-ops",
                "5000",
                "--hdd",
                "2",
                "--hdd-ops",
                "6000",
                "--hdd-bytes",
                "64M",
                "--cpu",
                "4",
                "--cpu-ops",
                "100000",
                "--temp-path",
                str(stress_tmp),
                "--metrics-brief",
                "--times",
            ],
            cwd=stress_tmp,
        ),
        "actplane-cargo-test": Workload(
            "actplane-cargo-test",
            ["cargo", "test", "-p", "actplane"],
            cwd=ROOT,
        ),
        "actplane-release-build": Workload(
            "actplane-release-build",
            ["cargo", "build", "--release", "-p", "actplane"],
            cwd=ROOT,
        ),
    }


TIME_KEYS = {
    "User time (seconds)": "user_s",
    "System time (seconds)": "sys_s",
    "Percent of CPU this job got": "cpu_pct_text",
    "Elapsed (wall clock) time (h:mm:ss or m:ss)": "time_elapsed_text",
    "Maximum resident set size (kbytes)": "max_rss_kb",
    "File system inputs": "fs_inputs",
    "File system outputs": "fs_outputs",
    "Voluntary context switches": "voluntary_context_switches",
    "Involuntary context switches": "involuntary_context_switches",
}


def parse_elapsed(text: str) -> float:
    parts = text.strip().split(":")
    try:
        if len(parts) == 3:
            return int(parts[0]) * 3600 + int(parts[1]) * 60 + float(parts[2])
        if len(parts) == 2:
            return int(parts[0]) * 60 + float(parts[1])
        return float(parts[0])
    except (ValueError, IndexError):
        return 0.0


def parse_time_verbose(stderr: str) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for line in stderr.splitlines():
        stripped = line.strip()
        for prefix, key in TIME_KEYS.items():
            if stripped.startswith(prefix + ":"):
                value = stripped[len(prefix) + 1 :].strip()
                if key.endswith("_text"):
                    out[key] = value
                elif key in {"user_s", "sys_s"}:
                    out[key] = float(value)
                else:
                    try:
                        out[key] = int(value)
                    except ValueError:
                        out[key] = value
    if "time_elapsed_text" in out:
        out["elapsed_s"] = parse_elapsed(str(out["time_elapsed_text"]))
    return out


def parse_stressng(stderr: str) -> dict[str, Any]:
    total_bogo = 0
    stressors: list[dict[str, Any]] = []
    for line in stderr.splitlines():
        if "metrics:" not in line and "metrc:" not in line:
            continue
        # Example columns contain stressor, bogo ops, real time, usr, sys.
        m = re.search(r"metr(?:ic|c):\s+\[\s*\d+\]\s+(\S+)\s+(\d+)\s+", line)
        if not m:
            continue
        bogo = int(m.group(2))
        total_bogo += bogo
        stressors.append({"stressor": m.group(1), "bogo_ops": bogo, "line": line.strip()})
    return {"stressng_total_bogo_ops": total_bogo, "stressng_stressors": stressors}


def timed_command(argv: list[str]) -> list[str]:
    return ["/usr/bin/time", "-v", *argv]


def run_one(
    args: argparse.Namespace,
    workload: Workload,
    config: str,
    repeat: int,
    out_dir: Path,
    policies: dict[str, Path],
) -> dict[str, Any]:
    work_cwd = workload.cwd
    work_cwd.mkdir(parents=True, exist_ok=True)
    env = dict(workload.env or {})
    argv = list(workload.argv)
    if workload.name.startswith("stressng"):
        env.setdefault("TMPDIR", str(work_cwd))
    if workload.name.startswith("actplane-"):
        cargo_target = out_dir / "cargo-targets" / workload.name / config / f"r{repeat}"
        env["CARGO_TARGET_DIR"] = str(cargo_target)
    linux_build_dir: Path | None = None
    if workload.name == "linux-build":
        linux_build_dir = out_dir / "linux-builds" / config / f"r{repeat}"
        argv += [
            "--source",
            str(args.linux_source),
            "--build-dir",
            str(linux_build_dir),
            "--jobs",
            str(args.linux_jobs),
            "--target",
            args.linux_target,
            "--config",
            args.linux_config,
        ]
    if workload.name == "agent-trace":
        argv += [
            "--workspace",
            str(out_dir / "agent-trace-workspaces" / config / f"r{repeat}"),
        ]

    target = timed_command(argv)
    if config == "baseline":
        cmd = target
    else:
        cmd = [str(args.actplane), "--policy", str(policies[config]), "run", "--", *target]

    started = time.time()
    proc = run(cmd, cwd=work_cwd, timeout=args.timeout_s, env=env)
    ended = time.time()
    logs = out_dir / "logs"
    logs.mkdir(parents=True, exist_ok=True)
    stem = f"{workload.name}-{config}-r{repeat}"
    stdout_path = logs / f"{stem}.stdout"
    stderr_path = logs / f"{stem}.stderr"
    stdout_path.write_text(proc.stdout, encoding="utf-8", errors="replace")
    stderr_path.write_text(proc.stderr, encoding="utf-8", errors="replace")

    time_metrics = parse_time_verbose(proc.stderr)
    stress_metrics = parse_stressng(proc.stdout + "\n" + proc.stderr)
    rec: dict[str, Any] = {
        "workload": workload.name,
        "config": config,
        "repeat": repeat,
        "returncode": proc.returncode,
        "measured_elapsed_s": ended - started,
        "command": cmd,
        "cwd": str(work_cwd),
        "stdout_log": str(stdout_path),
        "stderr_log": str(stderr_path),
        **time_metrics,
        **stress_metrics,
    }
    if proc.returncode != 0:
        raise RuntimeError(
            f"workload failed: {workload.name} {config} r{repeat} rc={proc.returncode}\n"
            f"stderr: {stderr_path}"
        )
    if linux_build_dir is not None and not args.keep_build_dirs:
        shutil.rmtree(linux_build_dir, ignore_errors=True)
    return rec


def median(values: list[float]) -> float:
    values = [v for v in values if v is not None]
    return float(sorted(values)[len(values) // 2]) if values else 0.0


def aggregate(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    by_key: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for rec in records:
        by_key.setdefault((rec["workload"], rec["config"]), []).append(rec)

    rows: list[dict[str, Any]] = []
    baseline: dict[str, float] = {}
    for (workload, config), group in sorted(by_key.items()):
        elapsed = [float(g.get("elapsed_s") or g["measured_elapsed_s"]) for g in group]
        user = [float(g.get("user_s", 0.0)) for g in group]
        sys_s = [float(g.get("sys_s", 0.0)) for g in group]
        bogo = [float(g.get("stressng_total_bogo_ops", 0.0)) for g in group]
        row = {
            "workload": workload,
            "config": config,
            "repeats": len(group),
            "median_elapsed_s": median(elapsed),
            "median_user_s": median(user),
            "median_sys_s": median(sys_s),
            "median_stressng_total_bogo_ops": median(bogo),
        }
        rows.append(row)
        if config == "baseline":
            baseline[workload] = row["median_elapsed_s"]

    for row in rows:
        base = baseline.get(row["workload"], 0.0)
        value = row["median_elapsed_s"]
        row["elapsed_overhead_pct"] = ((value / base) - 1.0) * 100.0 if base else ""
    return rows


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    fields = list(rows[0].keys())
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, sort_keys=True) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--actplane", type=Path, default=DEFAULT_ACTPLANE)
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--configs", default="baseline,ap-32,ap-100")
    parser.add_argument("--workloads", default="stressng-open,stressng-fork,stressng-exec,stressng-hdd,stressng-mixed,actplane-cargo-test,actplane-release-build")
    parser.add_argument("--repeats", type=int, default=3)
    parser.add_argument("--timeout-s", type=int, default=1800)
    parser.add_argument("--build-actplane", action="store_true")
    parser.add_argument("--skip-cargo-workloads", action="store_true")
    parser.add_argument(
        "--linux-source",
        type=Path,
        default=Path(os.environ.get("ACTPLANE_LINUX_SOURCE", "/home/yunwei37/workspace/multikernel/linux")),
    )
    parser.add_argument("--linux-jobs", type=int, default=min(os.cpu_count() or 1, 24))
    parser.add_argument("--linux-target", default="vmlinux")
    parser.add_argument("--linux-config", default="defconfig")
    parser.add_argument("--keep-build-dirs", action="store_true")
    args = parser.parse_args()

    if args.build_actplane:
        build_actplane()
    configs = parse_csv_arg(args.configs)
    for cfg in configs:
        if cfg != "baseline" and cfg not in CONFIGS:
            raise SystemExit(f"unknown config: {cfg}")
    if any(cfg != "baseline" for cfg in configs) and not args.actplane.exists():
        raise SystemExit(f"actplane binary not found: {args.actplane}")

    out_dir = args.output_dir or (PERF_DIR / "results" / f"macro-{utc_stamp()}")
    out_dir.mkdir(parents=True, exist_ok=True)
    policies = write_policies(configs, out_dir)
    (out_dir / "metadata.json").write_text(
        json.dumps(metadata(args, out_dir), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    workloads = available_workloads(out_dir)
    names = parse_csv_arg(args.workloads)
    if args.skip_cargo_workloads:
        names = [n for n in names if not n.startswith("actplane-")]
    for name in names:
        if name not in workloads:
            raise SystemExit(f"unknown workload: {name}")
    if shutil.which("stress-ng") is None and any(n.startswith("stressng") for n in names):
        raise SystemExit("stress-ng is required for selected workloads")
    if "linux-build" in names and not args.linux_source.exists():
        raise SystemExit(f"linux source not found: {args.linux_source}")

    records: list[dict[str, Any]] = []
    for name in names:
        workload = workloads[name]
        for config in configs:
            for repeat in range(1, args.repeats + 1):
                print(
                    f"[macro] workload={name} config={config} repeat={repeat}/{args.repeats}",
                    flush=True,
                )
                rec = run_one(args, workload, config, repeat, out_dir, policies)
                records.append(rec)
                write_jsonl(out_dir / "runs.jsonl", records)

    write_csv(out_dir / "runs.csv", records)
    agg = aggregate(records)
    (out_dir / "aggregate.json").write_text(
        json.dumps(agg, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    write_csv(out_dir / "aggregate.csv", agg)
    print(f"[macro] wrote {out_dir}")
    print(f"[macro] aggregate {out_dir / 'aggregate.csv'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
