import React,{useEffect,useRef,useState} from 'react';
import RecordBadge from './RecordBadge.jsx';
import {agentProcessLabel} from './agentInstancePresentation.mjs';

export const scopeName=r=>({system:'系统策略',agent:'Agent 策略',session:'会话策略'})[r.scope_type]||r.scope_type;
export const typeName=t=>({per_event:'单事件',cross_event:'跨事件',semantic_only:'语义指导'})[t]||t;
export function DslCode({text,firstLine=1}){
 const tokens=line=>line.split(/(#[^\n]*|"(?:\\.|[^"\\])*"|\b(?:source|rule|block|kill|notify|if|unless|after|since|because|and|or|not|exec|file|endpoint|read|write|unlink|connect|recv|open|exits|declassify|endorse|via|lineageIncludes)\b)/g).map((part,i)=><span key={i} className={part.startsWith('#')?'dsl-comment':part.startsWith('"')?'dsl-string':/^[a-zA-Z]+$/.test(part)?'dsl-keyword':''}>{part}</span>);
 return <div className="dsl-code" tabIndex={0} aria-label="ActPlane DSL">{(text||'未记录').split('\n').map((line,i)=><div className="dsl-code-line" key={i}><span className="dsl-line-number" aria-hidden="true">{firstLine+i}</span><code>{tokens(line)||' '}</code></div>)}</div>;
}
export function PolicyRecords({records=[],onDetail,onEdit,empty='尚无已配置的 ActPlane 策略。'}){
 return <div className="table-scroll policy-records-wrap"><table className="policy-records"><thead><tr>{['策略语句','动作','事件类型','上下文需求','策略来源','状态','操作'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{records.map((r,i)=><tr key={r.id||i}>
  <td><strong>{r.statement}</strong><small>{r.statement_origin==='dsl_summary'?'DSL 摘要 · ':''}{r.rule_name||r.id}</small></td>
  <td><div className="policy-badges">{(r.effects||[r.effect]).filter(Boolean).map(e=><span key={e} className={'effect-pill effect-'+e}>{e}</span>)}</div></td>
  <td><div className="policy-badges">{(r.event_types||[r.policy_type]).filter(Boolean).map(t=><RecordBadge key={t} tone={t==='cross_event'?'purple':'info'} dot={false}>{typeName(t)}</RecordBadge>)}</div></td>
  <td><RecordBadge tone={r.context_requirement==='self_contained'?'neutral':'purple'} dot={false}>{r.context_requirement||'未记录'}</RecordBadge></td>
  <td><RecordBadge tone={r.scope_type==='system'?'purple':r.scope_type==='session'?'good':'info'} dot={false}>{scopeName(r)}</RecordBadge></td>
  <td><RecordBadge tone={r.active?'good':r.loaded?'info':'neutral'}>{r.active?'当前绑定已核验':r.application_state==='blocked'?'应用失败 · 已暂停':r.coverage?.verified_count?'当前核验 '+r.coverage.verified_count+' / '+r.coverage.total_count+' 个连接':r.loaded?'历史已加载':r.application_state==='applied'?'已确认 · 待加载':r.compile_status==='compiled'?'编译通过 · 未加载':'未取得编译映射'}</RecordBadge></td>
  <td><div className="policy-row-actions"><button className="button tiny ghost" onClick={()=>onDetail?.(r)}>详情</button>{onEdit&&r.document_id&&r.editable!==false&&<button className="button tiny ghost" onClick={()=>onEdit(r)}>编辑 DSL</button>}</div></td>
 </tr>)}{!records.length&&<tr><td colSpan={7} className="task-empty">{empty}</td></tr>}</tbody></table></div>;
}
export function PolicyDetail({record:r,onClose,onEdit}){
 const dialog=useRef(null),origin=useRef(document.activeElement),[copy,setCopy]=useState('');
 useEffect(()=>{dialog.current?.showModal();return()=>{dialog.current?.close();origin.current?.isConnected&&origin.current.focus();};},[]);
 return <dialog ref={dialog} className="record-drawer dsl-detail" aria-label="ActPlane 策略详情" onCancel={e=>{e.preventDefault();onClose();}}><div className="record-drawer-head"><h2>策略详情 · {r.rule_name||r.id}</h2><button className="button tiny ghost" onClick={onClose}>关闭</button></div><div className="record-drawer-body">
 <p className="policy-statement">{r.statement}</p><div className="policy-badges">{(r.effects||[]).map(e=><span key={e} className={'effect-pill effect-'+e}>{e}</span>)}{(r.event_types||[]).map(t=><RecordBadge key={t} tone="purple" dot={false}>{typeName(t)}</RecordBadge>)}<RecordBadge dot={false}>{r.context_requirement||'未记录'}</RecordBadge><RecordBadge tone="info" dot={false}>{scopeName(r)}</RecordBadge></div>
 <dl className="security-facts"><dt>上下文依据</dt><dd>{r.context_reason||'未提供额外上下文说明'}</dd><dt>策略来源</dt><dd>{r.source_kind==='legacy_generated'?'既有启动编译器生成':r.scope_id}</dd><dt>编译状态</dt><dd>{r.compile_status==='compiled'?'编译通过':'未取得编译映射'}</dd><dt>加载与运行</dt><dd>{r.active?'当前运行绑定已核验':r.loaded?'存在历史加载记录；当前运行未核验':'尚未加载'}</dd></dl>
 <section className="dsl-section"><div className="dsl-section-heading"><h3>原始 DSL</h3>{r.original_dsl&&<button className="button tiny ghost" onClick={async()=>{try{await navigator.clipboard.writeText(r.original_dsl);setCopy('已复制');}catch{setCopy('复制不可用，请选中文本复制');}}}>{copy||'复制'}</button>}</div>{r.original_dsl?<DslCode text={r.original_dsl} firstLine={r.source_start_line||1}/>:<p className="field-note">用户原始 DSL 未记录。以下加载材料来自既有编译回执。</p>}{r.original_document&&<details><summary>完整原始文档 · {r.document_name}</summary><DslCode text={r.original_document}/></details>}</section>
 <section className="dsl-section"><h3>实际编译 DSL</h3><DslCode text={r.effective_dsl||r.compilation?.dsl}/><dl className="security-facts"><dt>策略包 hash</dt><dd><code>{r.bundle_hash||'未记录'}</code></dd></dl><details><summary>编译子句与加载绑定</summary><pre>{JSON.stringify({compiled_refs:r.compiled_refs||[],bindings:r.bindings||[]},null,2)}</pre></details></section>
 {r.loaded_document&&<details><summary>完整加载 DSL · 包含声明与继承约束</summary><DslCode text={r.loaded_document}/></details>}
 <section className="dsl-section"><h3>真实命中记录</h3><p className="field-note">{r.hit_coverage||'仅展示已核对运行进程、策略包与编译子句的命中。'}</p>{r.hits?.length?r.hits.map(h=><article key={h.id} className="dsl-target"><b>{h.operation} · {h.effect}</b><code>{h.target}</code><small>PID {h.pid} · 域 {h.domain_id} · {h.killed?'进程已终止':h.blocked?'操作已阻止':['notify','report'].includes(h.actual_action)?'已上报':'处置未记录'}</small></article>):<p className="field-note">暂无本策略已核验的命中记录。</p>}</section>
 {onEdit&&r.document_id&&r.editable!==false&&<button className="button primary" onClick={()=>onEdit(r)}>编辑所属 DSL 文档</button>}
 </div></dialog>;
}

function DslEditor({data,record,importing,onClose,onValidate,onApply,busy}){
 const dialog=useRef(null),input=useRef(null),gutter=useRef(null),origin=useRef(document.activeElement);
 const fresh=()=>({id:crypto.randomUUID(),name:'新策略文档',original_dsl:'',metadata:{}});
 const initial=structuredClone(data.documents||[]);if(importing||!initial.length)initial.push(fresh());
 const [docs,setDocs]=useState(initial),[selected,setSelected]=useState(record?.document_id||initial.at(-1)?.id),[preview,setPreview]=useState(null),[checked,setChecked]=useState(''),[error,setError]=useState('');
 const doc=docs.find(d=>d.id===selected),known=(preview?.result?.compilations?.[0]?.documents||[]).flatMap(d=>d.rules.map(r=>({...r,document_id:d.id}))).filter(r=>r.document_id===selected);
 const rules=known.length?known:(data.records||[]).filter(r=>r.document_id===selected);
 useEffect(()=>{dialog.current?.showModal();return()=>{dialog.current?.close();origin.current?.isConnected&&origin.current.focus();};},[]);
 useEffect(()=>{if(record?.source_start_line&&input.current){const offset=(doc?.original_dsl||'').split('\n').slice(0,record.source_start_line-1).join('\n').length;input.current.focus();input.current.setSelectionRange(offset,offset);}},[]);
 function change(patch){setDocs(old=>old.map(d=>d.id===selected?{...d,...patch}:d));}
 function metadata(rule,patch){change({metadata:{...doc.metadata,[rule]:{...doc.metadata?.[rule],...patch}}});}
 const current=JSON.stringify(docs),valid=preview?.state==='pending'&&checked===current;
 return <dialog ref={dialog} className="record-drawer dsl-editor" aria-label="编辑或导入 DSL" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><div className="record-drawer-head"><h2>{importing?'导入 DSL':'编辑 DSL'} · {data.scope_id==='system'?'系统策略':'当前 Agent 策略'}</h2><button className="button tiny ghost" disabled={busy} onClick={onClose}>关闭</button></div><div className="record-drawer-body">
 <p className="field-note">保存与校验不会改变运行策略。确认应用后，受影响的执行器会停止并重新加载策略。</p>
 <div className="dsl-document-toolbar"><label>所属文档<select aria-label="选择 DSL 文档" value={selected||''} onChange={e=>setSelected(e.target.value)}>{docs.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><button className="button tiny ghost" disabled={busy} onClick={()=>{const d=fresh();setDocs([...docs,d]);setSelected(d.id);}}>新增文档</button><label className="button tiny ghost dsl-file-input">导入 .dsl<input type="file" accept=".dsl,text/plain" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>50000)throw Error('DSL 文件不能超过 50000 字节');const text=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());const d={...fresh(),name:file.name,original_dsl:text};setDocs(old=>[...old.filter(x=>x.original_dsl.trim()||x.id!==selected),d]);setSelected(d.id);setError('');}catch(e){setError(e.message);}e.target.value='';}}/></label></div>
 {doc?<><label className="dsl-name-field">文档名称<input maxLength={120} value={doc.name} disabled={busy} onChange={e=>change({name:e.target.value})}/></label><div className="dsl-edit-box"><div ref={gutter} className="dsl-editor-lines" aria-hidden="true">{doc.original_dsl.split('\n').map((_,i)=><div key={i}>{i+1}</div>)}</div><textarea ref={input} onScroll={e=>{if(gutter.current)gutter.current.scrollTop=e.target.scrollTop;}} spellCheck={false} aria-label="原始 DSL 文本" disabled={busy} value={doc.original_dsl} onChange={e=>change({original_dsl:e.target.value})} placeholder={'source AGENT = exec "**"\n\nrule policy-name:\n  notify exec "git" if AGENT\n  because "说明触发条件与原因"'}/></div>
 {rules.length>0&&<details className="dsl-metadata"><summary>策略语句与上下文 · {rules.length} 条规则</summary>{rules.map(r=><div className="dsl-rule-metadata" key={r.rule_name}><b>{r.rule_name}</b><button className="button tiny ghost" disabled={busy} onClick={()=>{const next={...doc.metadata};delete next[r.rule_name];change({metadata:next});}}>清除该规则的说明</button><label>策略原始语句<textarea value={doc.metadata?.[r.rule_name]?.statement||''} disabled={busy} onChange={e=>metadata(r.rule_name,{statement:e.target.value})} placeholder="留空时使用包含完整条件的 DSL 摘要"/></label><label>上下文需求<select value={doc.metadata?.[r.rule_name]?.context_requirement||'self_contained'} disabled={busy} onChange={e=>metadata(r.rule_name,{context_requirement:e.target.value})}><option value="self_contained">self_contained · 无外部上下文需求</option><option value="project">project · 项目上下文</option><option value="task">task · 任务上下文</option></select></label><label>上下文依据<input value={doc.metadata?.[r.rule_name]?.context_reason||''} disabled={busy} onChange={e=>metadata(r.rule_name,{context_reason:e.target.value})}/></label></div>)}</details>}
 <button className="button tiny danger" disabled={busy} onClick={()=>{setDocs(docs.filter(d=>d.id!==selected));setSelected(docs.find(d=>d.id!==selected)?.id||'');}}>从候选中移除此文档</button></>:<p className="task-empty">候选不包含任何用户 DSL。应用后将移除本层用户策略，继承约束仍然保留。</p>}
 {error&&<p role="alert" className="inline-notice warning">{error}</p>}
 <div className="dsl-save-actions"><button className="button primary" disabled={busy||docs.some(d=>!d.original_dsl.trim())} onClick={async()=>{setError('');try{const p=await onValidate(docs);setPreview(p);setChecked(current);}catch(e){setError(e.message);}}}>{busy?'正在处理…':'保存并校验'}</button><span className="field-note">{preview&&checked!==current?'内容已修改，需要重新校验':'校验后预览全部受影响连接'}</span></div>
 {preview&&<section className="dsl-preview"><h3>{preview.state==='pending'?'校验通过 · 待手动应用':'草案已保存 · 校验未通过'}</h3>{preview.result.error&&<p role="alert" className="inline-notice warning">{preview.result.error}</p>}<p>{preview.targets.length} 个受影响连接；只有变更前正在运行且已核验的连接才会重新启动。</p>{preview.targets.map(t=><div className="dsl-target" key={t.id}><strong>{agentProcessLabel(t)}</strong><small>{t.resources.join(' · ')} · {t.active?'将重新加载执行器':'保持未运行'} · PID {t.pid||'未核验'} · 所有工作区与会话</small></div>)}<details><summary>原始 DSL 变更前／候选内容</summary><div className="dsl-diff"><section><h4>变更前</h4><DslCode text={(data.documents||[]).map(d=>d.original_dsl).join('\n')||'无用户 DSL'}/></section><section><h4>候选</h4><DslCode text={preview.documents.map(d=>d.original_dsl).join('\n')||'无用户 DSL'}/></section></div></details>{preview.result.compilations.map(c=><details key={c.instance_id}><summary>实际编译 DSL · {c.instance_id}</summary><DslCode text={c.effective_dsl}/><code>{c.bundle_hash}</code></details>)}<button className="button primary" disabled={busy||!valid} onClick={async()=>{try{await onApply(preview);onClose();}catch(e){setError(e.message);}}}>{busy?'正在应用…':'确认并应用到'+(data.scope_id==='system'?'系统策略':'当前 Agent')}</button></section>}
 </div></dialog>;
}

export default function ActPlanePolicies({scopeId,api,post,onChanged}){
 const base=scopeId==='system'?'/api/security/system/dsl':'/api/agent-instances/'+encodeURIComponent(scopeId)+'/dsl';
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[detail,setDetail]=useState(null),[editor,setEditor]=useState(null),[query,setQuery]=useState('');
 const seq=useRef(0);
 function edit(options={}){setEditor({...options,base:structuredClone(data)});}
 async function refresh(){const n=++seq.current;try{const d=await api(base);if(n===seq.current){setData(d);setError('');}}catch(e){if(n===seq.current){setError(e.message);setData(null);}}}
 useEffect(()=>{refresh();const timer=setInterval(refresh,7000);return()=>{seq.current++;clearInterval(timer);};},[base,api]);
 async function run(fn){setBusy(true);try{return await fn();}finally{setBusy(false);}}
 const records=(data?.records||[]).filter(r=>(r.statement+' '+r.rule_name).toLowerCase().includes(query.toLowerCase()));
 return <section className="actplane-policies" aria-label={scopeId==='system'?'系统 ActPlane 策略':'Agent ActPlane 策略'}><div className="dsl-scope-header"><div><h3>{scopeId==='system'?'系统策略':'当前 Agent 策略'} <RecordBadge tone={scopeId==='system'?'purple':'info'} dot={false}>{scopeId==='system'?'所有受控 Agent 继承':'此 Agent 所有工作区与会话共用'}</RecordBadge></h3><p>配置真实的 ActPlane DSL；编译、加载与当前运行核验分别记录。</p></div><div className="actions"><button className="button ghost" disabled={!data||busy} onClick={()=>edit({importing:true})}>导入 DSL</button><button className="button primary" disabled={!data||busy} onClick={()=>edit()}>编辑 DSL</button></div></div>
 {error&&<p role="alert" className="inline-notice warning">{error} <button className="button tiny ghost" onClick={refresh}>重新读取</button></p>}
 {data?.phase!=='ready'&&data&&<p role="alert" className="inline-notice warning">上次 DSL 应用未完成，执行保持暂停。请打开编辑器，重新校验并确认恢复。</p>}
 <div className="dsl-list-toolbar"><input type="search" aria-label="搜索策略语句" placeholder="搜索策略语句或规则名" value={query} onChange={e=>setQuery(e.target.value)}/><span>{data?records.length+' 条策略 · v'+data.revision:'正在读取策略…'}</span></div>
 <PolicyRecords records={records} onDetail={setDetail} onEdit={r=>edit({record:r})} empty={data?'尚无用户配置的 ActPlane DSL。通过编辑或导入添加策略。':'正在读取策略记录…'}/>
 {data?.proposals?.filter(p=>p.state!=='applied').length>0&&<details className="dsl-drafts"><summary>已保存的草案与应用记录</summary>{data.proposals.filter(p=>p.state!=='applied').map(p=><div className="dsl-draft-row" key={p.id}><code>{p.id.slice(0,12)}</code><span>{({pending:'校验通过 · 待应用',invalid:'校验未通过',failed:'应用失败',applying:'应用中'})[p.state]||p.state}</span><button className="button tiny ghost" onClick={()=>edit({draft:p})}>继续编辑</button></div>)}</details>}
 {detail&&<PolicyDetail record={detail} onClose={()=>setDetail(null)} onEdit={r=>{setDetail(null);edit({record:r});}}/>}
 {editor&&editor.base&&<DslEditor data={editor.draft?{...editor.base,documents:editor.draft.documents}:editor.base} record={editor.record} importing={editor.importing} busy={busy} onClose={()=>setEditor(null)} onValidate={docs=>run(()=>post(base+'/proposals',{documents:docs,base_hash:editor.base.document_hash,base_revision:editor.base.revision,request_key:crypto.randomUUID()}))} onApply={p=>run(async()=>{const result=await post(base+'/proposals/'+p.id+'/confirm',{proposal_hash:p.proposal_hash});await refresh();onChanged?.(result);return result;})}/>}
 </section>;
}
