import {auditOperation} from './consoleState.mjs';
const kindNames={workspace_scene_read:'确认工作区任务草稿',scene_read_queued:'排队读取场景',scene_read_finished:'完成场景读取',list_scene_sources:'列出场景文件',read_scene_source:'只读读取场景文件',submit_scene_draft:'提交任务识别结果',task_created:'创建任务',created:'登记受管任务',task_context:'保存任务上下文',file_snapshot:'保存文件快照',evidence:'登记文件证据',startup_job:'生成启动策略',startup_started:'开始生成启动策略',startup_finished:'完成启动策略生成',startup_candidate:'提交启动策略候选',startup_result:'启动策略生成结果',startup_generation:'生成启动策略',startup_clarification:'补充启动信息',startup_review_required:'启动策略待人工审核',startup_confirmed:'人工批准启动策略',startup_rejected:'人工拒绝启动策略',policy_version:'保存策略版本',policy_review:'策略版本审核',compilation:'编译策略',deployment:'保存策略加载回执',policy_active:'策略加载回执',runtime_job:'运行时上下文评估',runtime_observation:'记录上下文变化',scope_request:'权限变化请求',scope_review:'权限变化审核',request:'收到任务请求',request_resolved:'完成请求处理',candidate:'提交权限变更候选',change_review:'人工审核权限变化',change_review_required:'权限变化待人工审核',control_pause:'控制面暂停工具执行',failure:'记录执行故障',feedback_delivery:'送达执行反馈',recovering:'开始恢复任务',recovered:'完成任务恢复',recovery:'任务恢复',closure_requested:'请求结束与撤权',cleanup_result:'清理与撤权结果',close_failed:'结束清理失败',closed:'保存结束撤权回执',task_ended:'任务结束',deployment_ended:'历史加载结束',task_stopped:'停止任务执行',task_execution_finished:'执行结束',revocation:'撤销执行权限',tool_start:'工具开始',tool_result:'工具结果',kernel:'内核操作记录',operation_verified:'操作效果核验',policy_approved:'批准策略',policy_rejected:'拒绝策略',policy_generated:'策略生成完成',task_prepared:'任务准备完成'};
const stateNames={correct_block:'核验拦截',correct_allow:'核验允许',false_block:'误拦截',missed_block:'漏拦截',operation_failed:'操作失败',unverified_denial:'拒绝未核验',recorded:'已记录',not_recorded:'未记录',queued:'排队中',running:'处理中',completed:'已完成',failed:'失败',interrupted:'已中断',validated:'已校验',needs_clarification:'待澄清',pending_review:'待审核',pending_confirmation:'待确认',approved:'已批准',rejected:'已拒绝',loaded:'历史已加载',active:'历史已加载',partially_loaded:'部分条款历史已加载',partially_active:'部分条款历史已加载',ended:'已结束',closed:'已撤权',stopped:'已停止',success:'成功',failure:'失败',denied:'拒绝记录',started:'已开始',prepared:'已准备',applied:'已应用',superseded:'已被替代',expired:'已过期',revoked:'已撤销',policy_review:'待策略审核',waiting_confirmation:'待人工确认',control_pause:'工具执行暂停'};
const decisions={no_change:'无需调整权限',guidance_only:'仅更新任务指导',guidance:'更新任务指导',restrict:'收紧权限',expand:'扩展权限',approve:'人工批准',reject:'人工拒绝',clarify:'要求澄清'};
export function eventDecision(event){return event.detail?.decision||event.detail?.proposal?.decision||event.detail?.change?.decision||event.detail?.change?.effect;}
export function eventSummary(event){const assessment=eventDecision(event);if(['no_change','guidance_only'].includes(assessment))return '策略评估：'+decisions[assessment];if(event.kind==='operation_verified'){const d=event.detail||{},target=d.target||d.probe?.target||'',name=target.split(/[\\/]/).filter(Boolean).at(-1)||'对象未记录',result=d.classification||d.result;return `操作效果核验：${auditOperation({operation:d.operation||d.probe?.operation})} ${name} · ${result?eventStatus(result):d.effect_verified===true?'效果已核验':'结果未记录'}`;}const title=kindNames[event.kind]||(/[^\x00-\x7F]/.test(event.summary||'')?event.summary:'任务事件');const decision=eventDecision(event);return decisions[decision]?`${title}：${decisions[decision]}`:title;}
export function eventStatus(value){return stateNames[typeof value==='string'?value:'']||'已记录';}
export function mergeArchiveEvents(...groups){const map=new Map();for(const event of groups.flat())if(event?.id)map.set(event.id,event);return [...map.values()];}
export function archiveValue(value){if(value===undefined||value===null||value==='')return '未记录';if(Array.isArray(value))return value.map(archiveValue).join('；')||'无';return typeof value==='object'?JSON.stringify(value):String(value);}
export function archiveListWorkspace(row){return row.source_name||(typeof row.workspace==='object'?row.workspace?.path||'':row.workspace||'').split('/').filter(Boolean).at(-1)||'未记录';}
export function archiveListMatch(row,query='',filter='history'){const text=`${row.name||''} ${row.id||''} ${row.agent||''} ${row.source_name||''} ${row.workspace||''}`.toLowerCase();if(query&&!text.includes(query.toLowerCase()))return false;const ended=['ended','completed','stopped'].includes(row.phase||row.status);return !filter||filter==='all'?true:filter==='history'?ended:!ended;}
const policyKinds=new Set(['startup_job','startup_started','startup_finished','startup_candidate','startup_result','startup_generation','startup_review_required','startup_confirmed','startup_rejected','policy_version','policy_review','compilation','deployment','policy_active','runtime_job','candidate','change_review','change_review_required','request_resolved','policy_approved','policy_rejected','policy_generated']);
export function archiveSeedEvents(data){const previews=Object.values(data.stage_previews||{});return mergeArchiveEvents(data.events||[],...previews.map(p=>Array.isArray(p)?p:p.events||[]),...previews.map(p=>Array.isArray(p)?[]:p.highlights||[]));}
export function archiveHighlightIds(data){return Object.values(data.stage_previews||{}).flatMap(p=>Array.isArray(p)?[]:(p.highlights||[]).map(e=>e.id));}
export function groupArchiveEvents(events,highlights=[]){
 const sorted=mergeArchiveEvents(events).sort((a,b)=>new Date(a.time||0)-new Date(b.time||0)||a.id.localeCompare(b.id)),highlightIds=new Set(highlights),versionJobs=new Map();
 const assessment=e=>['no_change','guidance_only'].includes(eventDecision(e));
 const policy=e=>policyKinds.has(e.kind)&&!assessment(e);
 const jobKey=e=>(e.task_id||'')+':job:'+e.job_id,versionKey=e=>(e.task_id||'')+':version:'+e.version;
 for(const e of sorted)if(policy(e)&&e.job_id&&Number.isInteger(e.version)&&e.version>0){const key=versionKey(e);if(!versionJobs.has(key))versionJobs.set(key,new Set());versionJobs.get(key).add(jobKey(e));}
 const map=new Map();for(const e of sorted){const file=['file_snapshot','evidence'].includes(e.kind),hasVersion=Number.isInteger(e.version)&&e.version>0;let key='event:'+e.id,type='event';
  if(file){key='files:'+e.stage;type='files';}
  else if(assessment(e)&&e.job_id){key='assessment:'+jobKey(e);type='assessment';}
  else if(policy(e)&&(e.job_id||hasVersion)){type='policy';const jobs=hasVersion?versionJobs.get(versionKey(e)):null;key='policy:'+(e.job_id?jobKey(e):jobs?.size===1?[...jobs][0]:versionKey(e));}
  let group=map.get(key);if(!group){group={id:key,type,stage:e.stage,events:[],time:e.time,highlighted:false};map.set(key,group);}group.events.push(e);group.time=e.time;group.highlighted ||= highlightIds.has(e.id);
 }
 for(const group of map.values())if(group.type==='policy'){const execution=group.events.some(e=>e.stage==='execution'&&['policy_active','deployment','runtime_job','candidate','change_review','request_resolved'].includes(e.kind));group.stage=execution?'execution':group.events.some(e=>e.stage==='preparation')?'preparation':group.stage;}
 return [...map.values()].sort((a,b)=>new Date(a.time||0)-new Date(b.time||0));
}

const criticalKinds=new Set(['startup_confirmed','startup_rejected','policy_review','change_review','policy_active','deployment','policy_approved','policy_rejected','control_pause','failure','recovering','recovered','recovery','recovery_started','recovery_completed','session_resumed','session_recovered','close_failed','closed','closure_requested','cleanup_result','task_ended','task_stopped','task_execution_finished','revocation']);
export function previewArchiveGroups(groups,limit=5){if(groups.length<=limit)return {visible:groups,hidden:[]};const priority=g=>g.highlighted?(g.type==='policy'?130:120):g.type==='assessment'?10:g.type==='policy'?100:g.events.some(e=>criticalKinds.has(e.kind))?90:g.type==='files'?70:g.events.every(e=>e.kind==='operation_verified')?0:20;const ranked=groups.map((group,index)=>({group,index,score:priority(group)})).sort((a,b)=>b.score-a.score||b.index-a.index),selected=new Set(ranked.slice(0,limit).map(r=>r.group));return {visible:groups.filter(g=>selected.has(g)),hidden:groups.filter(g=>!selected.has(g))};}

const constraintLabels={declared_constraints:'声明约束',execution_constraints:'执行约束',platform_constraints:'平台约束',id:'条目编号',intent:'约束意图',authority_role:'来源角色',source_quote:'来源原文',targets:'作用对象',constraints:'任务约束',goal:'任务目标',protected_paths:'保护范围',protected_files:'保护文件',protected:'保护范围',write_scope:'写入范围',allowed_write_paths:'允许写入',allowed_paths:'允许路径',denied_paths:'禁止路径',output_dir:'输出目录',output:'输出',baseline:'启动底线',baseline_rules:'底线规则',rules:'规则',guidance:'任务指导',user_constraints:'用户约束',statement:'要求',text:'内容',reason:'依据',paths:'路径',operations:'操作',forbidden_operations:'禁止操作',read_only_paths:'只读路径',editable_paths:'可修改路径',type:'类型',scope:'范围',source:'来源',policy:'策略',mode:'模式',name:'名称',enabled:'启用',test_paths:'测试路径',config_paths:'配置路径'};
export function constraintEntries(value,prefix=''){if(value===undefined||value===null||value==='')return [];if(Array.isArray(value))return value.flatMap((v,i)=>constraintEntries(v,prefix?`${prefix} ${i+1}`:`约束 ${i+1}`));if(typeof value==='object')return Object.entries(value).flatMap(([k,v])=>constraintEntries(v,[prefix,constraintLabels[k]||('约束项（'+k+'）')].filter(Boolean).join(' / ')));return [[prefix||'任务约束',typeof value==='boolean'?(value?'是':'否'):String(value)]];}
