import test from 'node:test';
import assert from 'node:assert/strict';
import {eventSummary,eventStatus,mergeArchiveEvents,archiveValue,archiveListMatch,archiveListWorkspace,groupArchiveEvents,previewArchiveGroups,constraintEntries,archiveSeedEvents,archiveHighlightIds} from './archivePresentation.mjs';
test('stage previews preserve preparation and closure beside a busy execution page without duplicating events',()=>{const events=mergeArchiveEvents([{id:'run',stage:'execution'}],[{id:'prepare',stage:'preparation'}],[{id:'run',stage:'execution'},{id:'end',stage:'closure'}]);assert.deepEqual(events.map(e=>e.id),['run','prepare','end']);assert.equal(new Set(events.map(e=>e.stage)).size,3);});
test('runtime assessment displays its public no-change decision in Chinese',()=>{assert.equal(eventSummary({kind:'runtime_job',summary:'runtime_job',detail:{decision:'no_change'}}),'策略评估：无需调整权限');assert.equal(eventSummary({kind:'change_review',detail:{decision:'reject'}}),'人工审核权限变化：人工拒绝');assert.equal(eventSummary({kind:'unknown_internal_kind',summary:'unknown_internal_kind'}),'任务事件');});
test('archived loaded and legacy active status never claim current enforcement',()=>{assert.equal(eventStatus('loaded'),'历史已加载');assert.equal(eventStatus('active'),'历史已加载');assert.equal(eventStatus('partially_loaded'),'部分条款历史已加载');assert.equal(eventStatus('failed'),'失败');});
test('missing source snapshots remain explicitly unrecorded',()=>{assert.equal(archiveValue(undefined),'未记录');assert.equal(archiveValue(['保护测试','保留配置']),'保护测试；保留配置');});

test('archive list defaults to ended tasks and keeps explicit all/active filters',()=>{const ended={id:'e',status:'completed'},running={id:'r',phase:'running'};assert.equal(archiveListMatch(ended),true);assert.equal(archiveListMatch(running),false);assert.equal(archiveListMatch(running,'','all'),true);assert.equal(archiveListMatch(ended,'','active'),false);});
test('archive list exposes the recorded Agent and workspace without inventing missing identity',()=>{const row={id:'x',agent:'dsh',source_name:'支付项目',workspace:'/tmp/task-x',phase:'ended'};assert.equal(archiveListMatch(row,'支付','history'),true);assert.equal(archiveListWorkspace(row),'支付项目');assert.equal(archiveListWorkspace({}),'未记录');});

test('file snapshots form one collapsed evidence batch and stage preview never exceeds five groups',()=>{const files=Array.from({length:13},(_,i)=>({id:'f'+i,kind:'file_snapshot',stage:'preparation',time:'2026-10-07'}));const other=Array.from({length:8},(_,i)=>({id:'e'+i,kind:'request',stage:'preparation',time:'2026-10-07'}));const groups=groupArchiveEvents([...files,...other]);assert.equal(groups.filter(g=>g.type==='files').length,1);assert.equal(groups.find(g=>g.type==='files').events.length,13);const preview=previewArchiveGroups(groups);assert.equal(preview.visible.length,5);assert.equal(preview.hidden.length,4);assert.ok(preview.visible.some(g=>g.type==='files'));});
test('policy lifecycle links exact job and version across candidate review compile and load receipts',()=>{const events=[{id:'j',task_id:'t',kind:'startup_job',stage:'preparation',job_id:'job1'},{id:'c',task_id:'t',kind:'startup_candidate',stage:'preparation',job_id:'job1'},{id:'v',task_id:'t',kind:'policy_version',stage:'preparation',job_id:'job1',version:2},{id:'compile',task_id:'t',kind:'compilation',stage:'preparation',version:2},{id:'load',task_id:'t',kind:'policy_active',stage:'execution',version:2}];const groups=groupArchiveEvents(events);assert.equal(groups.length,1);assert.equal(groups[0].events.length,5);assert.equal(groups[0].stage,'execution');});
test('missing identity, unrelated jobs and different task versions are not guessed into a policy group',()=>{const events=[{id:'a',task_id:'t1',kind:'candidate',stage:'execution',job_id:'a'},{id:'b',task_id:'t1',kind:'candidate',stage:'execution',job_id:'b'},{id:'v1',task_id:'t1',kind:'policy_version',stage:'preparation',version:1},{id:'v2',task_id:'t2',kind:'policy_version',stage:'preparation',version:1},{id:'none',task_id:'t1',kind:'compilation',stage:'preparation'}];assert.equal(groupArchiveEvents(events).length,5);});
test('no-change assessments retain their own decision instead of joining a prior loaded version',()=>{const groups=groupArchiveEvents([{id:'v',kind:'policy_version',stage:'preparation',version:1},{id:'noop',kind:'runtime_job',stage:'execution',version:1,detail:{decision:'no_change'}}]);assert.equal(groups.length,2);assert.ok(['event','assessment'].includes(groups.find(g=>g.events[0].id==='noop').type));});
test('constraint disclosure presents Chinese field entries without a JSON document',()=>{assert.deepEqual(constraintEntries({protected_paths:['tests'],output_dir:'out',enabled:true}),[['保护范围 1','tests'],['输出目录','out'],['启用','是']]);});
test('default stage summary keeps an earlier policy v4 ahead of the latest five probe results without reordering history',()=>{const events=[{id:'v4',kind:'policy_version',task_id:'t',version:4,stage:'execution',time:'2026-10-07T10:00:00Z'},...Array.from({length:5},(_,i)=>({id:'probe'+i,kind:'operation_verified',stage:'execution',time:`2026-10-07T10:01:0${i}Z`}))],groups=groupArchiveEvents(events),preview=previewArchiveGroups(groups);assert.equal(preview.visible.length,5);assert.ok(preview.visible.some(g=>g.events.some(e=>e.id==='v4')));assert.equal(preview.hidden.length,1);assert.deepEqual(groups.flatMap(g=>g.events.map(e=>e.id)),['v4','probe0','probe1','probe2','probe3','probe4']);assert.equal(preview.visible[0].events[0].id,'v4');});
test('operation verification summary names the operation target and recorded classification',()=>{assert.equal(eventSummary({kind:'operation_verified',detail:{operation:'unlink',target:'/work/config.json',classification:'correct_block',effect_verified:true}}),'操作效果核验：删除 config.json · 核验拦截');});
test('global highlights seed old v3/v4 receipts beyond the latest fifty probes without changing pagination records',()=>{const recent=Array.from({length:50},(_,i)=>({id:'probe'+i,kind:'operation_verified',stage:'execution',time:`2026-10-07T11:00:${String(i).padStart(2,'0')}Z`})),v3={id:'loaded3',task_id:'t',kind:'policy_active',stage:'execution',version:3,time:'2026-10-07T10:00:00Z'},v4={id:'loaded4',task_id:'t',kind:'policy_active',stage:'execution',version:4,time:'2026-10-07T10:30:00Z'},data={events:recent,next_cursor:'older',total:310,stage_previews:{execution:{events:recent.slice(-3),highlights:[v3,v4],highlight_total:2}}};const seeds=archiveSeedEvents(data),groups=groupArchiveEvents(seeds,archiveHighlightIds(data)),preview=previewArchiveGroups(groups);assert.equal(seeds.length,52);assert.ok(preview.visible.some(g=>g.events.some(e=>e.id==='loaded3')));assert.ok(preview.visible.some(g=>g.events.some(e=>e.id==='loaded4')));assert.equal(data.events.length,50);assert.equal(data.total,310);assert.equal(data.next_cursor,'older');});
test('v4 no-change runtime candidate and resolved events remain assessments outside a true expansion job',()=>{const events=[{id:'expand',task_id:'t',kind:'runtime_job',stage:'execution',job_id:'real',version:4,detail:{decision:'expand'}},{id:'loaded',task_id:'t',kind:'policy_active',stage:'execution',job_id:'real',version:4},...['runtime_job','candidate','request_resolved'].map((kind,i)=>({id:'noop'+i,task_id:'t',kind,stage:'execution',job_id:'noop',version:4,detail:{decision:'no_change'}}))];const groups=groupArchiveEvents(events);assert.equal(groups.length,2);assert.equal(groups.find(g=>g.type==='policy').events.length,2);assert.equal(groups.find(g=>g.type==='assessment').events.length,3);assert.equal(eventSummary(events.at(-1)),'策略评估：无需调整权限');});
test('different jobs with the same version are never unioned and an ambiguous version-only receipt stays separate',()=>{const groups=groupArchiveEvents([{id:'a',task_id:'t',kind:'candidate',job_id:'a',version:4},{id:'b',task_id:'t',kind:'candidate',job_id:'b',version:4},{id:'receipt',task_id:'t',kind:'policy_active',version:4}]);assert.equal(groups.length,3);assert.ok(groups.every(g=>g.events.length===1));});
