import test from 'node:test';
import assert from 'node:assert/strict';
import {instanceState,uniqueTasks,latestRequest,pendingChangeLabel,runtimeCaption,recordPermissionLabel,isTaskEnded,selectableTasks,visibleInstances,auditOperation,auditIdentity,auditSource,pendingReviewRecord,archiveAuditMetadata,auditPageAction,mergeAuditRecords,canReadWorkspace} from './consoleState.mjs';
import {readNavigation,navigationTarget} from './navigation.mjs';
test('connection immediately loses green on failure or expired evidence despite active phase',()=>{const a={connected:true,status:'connected',expires_at:'2026-10-07T10:00:08Z',phase:'running'};assert.equal(instanceState(a,Date.parse('2026-10-07T10:00:07Z')).live,true);assert.equal(instanceState(a,Date.parse('2026-10-07T10:00:07Z'),true).live,false);assert.equal(instanceState(a,Date.parse('2026-10-07T10:00:08Z')).live,false);assert.equal(instanceState({phase:'running'}).live,false);});
test('a delayed check cannot replace the newer request',()=>{const r=latestRequest(),old=r.begin(),fresh=r.begin();assert.equal(r.current(old),false);assert.equal(r.current(fresh),true);r.invalidate();assert.equal(r.current(fresh),false);});
test('logical task produces one row even when snapshots repeat',()=>{const rows=uniqueTasks([{id:'a',name:'first',updated_at:'2026-10-06'},{task_id:'a',name:'latest',updated_at:'2026-10-07'},{id:'b'}]);assert.equal(rows.length,2);assert.equal(rows.find(r=>r.id==='a').name,'latest');});
test('archive navigation preserves workbench agent task and history filters across refresh/back',()=>{const start='http://localhost/?view=workbench&task=abc&stage=runtime&q=fix&listPage=2';const target=navigationTarget(start,{page:'history',archiveTask:'other'}),r=readNavigation('http://localhost'+target);assert.equal(r.task,'abc');assert.equal(r.archiveTask,'other');assert.equal(r.workbenchSection,'runtime');assert.equal(r.query,'fix');assert.equal(r.listPage,2);});
test('old task/runtime/agent links migrate to the three modules',()=>{assert.equal(readNavigation('http://a/?view=task').page,'workbench');assert.equal(readNavigation('http://a/?view=task').workbenchSection,'startup');assert.equal(readNavigation('http://a/?view=scope-demo').page,'workbench');assert.equal(readNavigation('http://a/?view=agent-bridge').page,'connections');});
test('instance and workspace remain selected when archive query and browser history change',()=>{const base='http://localhost/?view=workbench&agent=managed%3At1&workspace=w1&connectionAgent=native-dsh&connectionWorkspace=w2&stage=audit';const r=readNavigation('http://localhost'+navigationTarget(base,{page:'history',archiveTask:'t2',query:'receipt',listPage:4}));assert.equal(r.agent,'managed:t1');assert.equal(r.workspace,'w1');assert.equal(r.connectionAgent,'native-dsh');assert.equal(r.connectionWorkspace,'w2');assert.equal(r.workbenchSection,'audit');});
test('history opens with ended filter and all remains explicitly restorable',()=>{assert.equal(readNavigation('http://a/?view=history').filter,'history');assert.equal(readNavigation('http://a/?view=history&filter=all').filter,'all');});

test('pending change wording follows proposal decision and confirmation is distinct from Pi evaluation',()=>{assert.equal(pendingChangeLabel({proposal:{decision:'restrict',effect:'expand'}}),'收紧待审核');assert.equal(pendingChangeLabel({proposal:{decision:'expand'}}),'扩权待审核');assert.equal(runtimeCaption({gate:'waiting_confirmation'}),'等待人工审核');assert.equal(runtimeCaption({gate:'waiting_policy'}),'Pi 正在评估，执行暂停');});
test('no-change and guidance rows distinguish unchanged permission from unapplied rejected or expired candidates',()=>{assert.equal(recordPermissionLabel({effect:'no_change'}),'保持当前权限');assert.equal(recordPermissionLabel({effect:'guidance_only'}),'仅指导');assert.equal(recordPermissionLabel({status:'rejected',loading:{version:2}}),'已拒绝，未应用');assert.equal(recordPermissionLabel({status:'expired'}),'已过期，未应用');});

test('workbench selections show current tasks and keep failed history out of the dropdown',()=>{const rows=[{id:'created',managed:true,dsh_profile:'web',phase:'prepared'},{id:'paused',managed:true,dsh_profile:'web',phase:'paused'},{id:'failed',managed:true,dsh_profile:'web',phase:'failed'},{id:'ended',managed:true,dsh_profile:'web',phase:'ended'},{id:'closed',managed:true,dsh_profile:'web',phase:'closed'},{id:'receipt',managed:true,dsh_profile:'web',phase:'failed',ended_at:'2026-10-07'}];assert.deepEqual(selectableTasks(rows).map(t=>t.id),['created','paused']);assert.equal(isTaskEnded(rows.at(-1)),true);});
test('ended managed instances disappear from connection choices while current registered instances remain unknown',()=>{const agents=[{id:'managed:old',kind:'managed',status:'offline'},{id:'managed:now',kind:'managed',status:'unresponsive'},{id:'native-dsh',kind:'native',generation:'g1',status:'running_unattached'},{id:'dsh',kind:'history'}];assert.deepEqual(visibleInstances(agents,[{id:'old',phase:'ended'}]).map(a=>a.id),['managed:now','native-dsh']);});
test('audit rows preserve operation process domain and distinguish acceptance probes from DSH',()=>{assert.equal(auditOperation({operation:'unlink'}),'删除');assert.equal(auditSource({source:'independent_probe'}),'验收探针');assert.equal(auditSource({source:'native_tool'}),'DSH');assert.equal(auditIdentity({pid:21,domain_id:7,source:'native_tool'}),'PID 21 / 域 7 / DSH');assert.match(auditIdentity({}),/PID 未记录/);});
test('two live tasks plus dozens of failed histories keep the current dropdown small and explicit failed remains recoverable',()=>{const live=[{id:'task2v1',managed:true,dsh_profile:'web',phase:'running'},{id:'root-task1v3',managed:true,dsh_profile:'web',phase:'running'}],failed=Array.from({length:45},(_,i)=>({id:'failed-'+i,managed:true,dsh_profile:'web',phase:'failed'})),tasks=[...live,...failed];assert.deepEqual(selectableTasks(tasks).map(t=>t.id),['task2v1','root-task1v3']);const explicit=tasks.find(t=>t.id==='failed-12');assert.equal(isTaskEnded(explicit),false);const visible=[...selectableTasks(tasks),explicit];assert.equal(visible.length,3);assert.equal(visible.filter(t=>t.phase==='failed').length,1);});

test('current selector requires managed web evidence and leaves old headless records in history',()=>{const rows=[{id:'live-web',managed:true,dsh_profile:'web',phase:'running'},{id:'headless-running',managed:true,dsh_profile:'headless',phase:'running'},{id:'headless-prepared',managed:true,dsh_profile:'headless',phase:'prepared'},{id:'unmanaged',managed:false,dsh_profile:'web',phase:'running'},{id:'unknown',phase:'running'}];assert.deepEqual(selectableTasks(rows).map(t=>t.id),['live-web']);assert.equal(isTaskEnded(rows[1]),false);});
test('loaded restriction subtitle follows stored loading receipts without requiring a version field',()=>{assert.equal(recordPermissionLabel({effect:'restrict',status:'loaded',loading:{loaded:true}}),'历史已加载');assert.equal(recordPermissionLabel({effect:'restrict',status:'partially_loaded'}),'历史已加载');assert.equal(recordPermissionLabel({effect:'restrict',loading:{loaded:true,version:4}}),'历史已加载 v4');assert.equal(recordPermissionLabel({effect:'no_change',status:'loaded'}),'保持当前权限');assert.equal(recordPermissionLabel({effect:'guidance_only',status:'loaded'}),'仅指导');});

test('pending review ignores a one-child statement delta and reconstructs the complete job scope',()=>{const pending={job_id:'job',hash:'h',base_version:3,proposal:{decision:'expand',allow_output:true,allowed_write_dirs:['src'],protected_paths:['tests']}};const data={state:{version:3},resources:{allow_output:false,allowed_write_dirs:['src'],runtime_protected:['tests']}};const child={id:'runtime:job:statement:0',statement:'保留文件',delta:{added_protection:['x']}};const record=pendingReviewRecord(pending,data,child);assert.equal(record.id,'runtime:job');assert.equal(record.delta.output_before,false);assert.equal(record.delta.output_after,true);assert.deepEqual(record.delta.added_protection,[]);assert.deepEqual(record.delta.removed_protection,[]);assert.equal(record.review.base_version,3);assert.equal(record.statement,'权限扩展候选（完整范围）');});
test('frozen parent baseline and process generation outrank current workbench values',()=>{const pending={job_id:'job',hash:'h',base_version:9,proposal:{decision:'restrict'}};const frozen={id:'runtime:job',base_version:4,process_generation:{domain_id:7,runner_pid:25,session_id:'session-old'},delta:{output_before:false,output_after:false}};const record=pendingReviewRecord(pending,{resources:{allow_output:true}},frozen);assert.equal(record.review.base_version,4);assert.equal(record.review.process_generation.session_id,'session-old');assert.equal(record.delta.output_before,false);});
test('archive audit attributes by action_source and never interprets a storage table as DSH',()=>{const row={source:'managed_events',action_source:'independent_probe',detail:{operation:'unlink',target:'config.json',pid:42,domain_id:8,classification:'correct_block'}};assert.deepEqual(archiveAuditMetadata(row),{source:'验收探针',operation:'unlink',target:'config.json',pid:42,domain:8,result:'correct_block'});assert.equal(archiveAuditMetadata({source:'managed_events',detail:{pid:42}}).source,'来源未记录');});

test('stale pending fallback does not invent a baseline from a newer live version',()=>{const r=pendingReviewRecord({job_id:'j',base_version:2,proposal:{allow_output:true,protected_paths:[]}},{state:{version:3},resources:{allow_output:false,runtime_protected:['tests']}});assert.equal(r.delta.output_before,undefined);assert.equal(r.delta.added_protection,undefined);});

test('audit reveals every row of a 50-row batch before requesting its older cursor',()=>{let visible=12;for(const expected of [24,36,48,50]){const next=auditPageAction(50,visible,'older');assert.equal(next.type,'reveal');assert.equal(next.visible,expected);visible=next.visible;}assert.deepEqual(auditPageAction(50,visible,'older'),{type:'fetch',visible:62,cursor:'older'});const combined=mergeAuditRecords(Array.from({length:50},(_,id)=>({id})),Array.from({length:50},(_,i)=>({id:i+49})));assert.equal(combined.length,99);assert.deepEqual(combined.slice(0,62).map(r=>r.id),Array.from({length:62},(_,i)=>i));});
test('probe operation labels describe file-descriptor mappings and path mutations',()=>{for(const [operation,label] of Object.entries({replace:'替换',hardlink:'硬链接',symlink_write:'经符号链接写入',ancestor_rename:'改名父目录',mmap_new:'共享映射写入',hold:'持有文件句柄',fd_write:'通过已有句柄写入'}))assert.equal(auditOperation({operation}),label);});

test('restored workspace selection waits for an explicitly readable registration before reading files',()=>{assert.equal(canReadWorkspace([],'w1'),false);assert.equal(canReadWorkspace([{id:'w1',readable:false}],'w1'),false);assert.equal(canReadWorkspace([{id:'w1'}],'w1'),false);assert.equal(canReadWorkspace([{id:'w1',readable:true}],'w1'),true);});
