export function instanceState(agent,now=Date.now(),failed=false){
 if(failed)return {label:'状态未知',tone:'warn',live:false};
 if(!agent)return {label:'状态未知',tone:'warn',live:false};
 const expired=agent.expires_at&&new Date(agent.expires_at).getTime()<=now;
 const live=agent.connected===true&&agent.status==='connected'&&!expired;
 return {live,tone:live?'good':'warn',label:expired?'证据已过期':({connected:'已连接',running_unattached:'进程运行，未连接',offline:'离线',unresponsive:'无响应',stale:'证据已过期',unknown:'状态未知'})[agent.status]||'状态未知'};
}
export function uniqueTasks(rows){const m=new Map();for(const r of rows){const id=r.task_id||r.id;if(!id)continue;const old=m.get(id);if(!old||new Date(r.updated_at||0)>=new Date(old.updated_at||0))m.set(id,{...old,...r,id,task_id:id});}return [...m.values()];}
export function latestRequest(){let seq=0;return {begin:()=>++seq,current:n=>n===seq,invalidate:()=>++seq};}
export function tabKeys(event,values,current,select){if(!['ArrowRight','ArrowLeft','Home','End'].includes(event.key))return;event.preventDefault();const i=values.indexOf(current);select(event.key==='Home'?values[0]:event.key==='End'?values.at(-1):values[(i+(event.key==='ArrowRight'?1:-1)+values.length)%values.length]);event.currentTarget.parentElement?.querySelectorAll('[role=tab]')[event.key==='Home'?0:event.key==='End'?values.length-1:(i+(event.key==='ArrowRight'?1:-1)+values.length)%values.length]?.focus();}
export function pendingChangeLabel(pending){const decision=pending?.proposal?.decision;return decision==='restrict'?'收紧待审核':decision==='expand'?'扩权待审核':'权限变更待审核';}
export function runtimeCaption(state){if(state?.phase==='ended')return '任务已结束';if(state?.phase==='failed')return '任务已暂停';return ({open:'监控中',waiting_confirmation:'等待人工审核',waiting_clarification:'待澄清，执行暂停',waiting_policy:'Pi 正在评估，执行暂停'})[state?.gate]||'执行状态待确认';}
export function recordPermissionLabel(record){if(record.status==='rejected')return '已拒绝，未应用';if(record.status==='expired')return '已过期，未应用';if(record.effect==='no_change'||record.decision==='no_change')return '保持当前权限';if(['guidance_only','guidance'].includes(record.effect)||record.decision==='guidance_only')return '仅指导';if(record.loading?.loaded===true||['loaded','partially_loaded'].includes(record.status))return record.loading?.version?'历史已加载 v'+record.loading.version:'历史已加载';return record.loading?.version?'加载回执 v'+record.loading.version:'未加载';}
export function isTaskEnded(task){return !!task?.ended_at||task?.gate==='closed'||['ended','closed','completed','stopped','finished','cancelled','canceled'].includes(task?.phase||task?.status);}
export function selectableTasks(tasks){return tasks.filter(t=>t.managed===true&&t.dsh_profile==='web'&&!isTaskEnded(t)&&['running','recovering','generating','prepared','created','policy_review','starting','paused'].includes(t.phase||t.status));}
export function visibleInstances(agents,tasks=[]){const ended=new Set(tasks.filter(isTaskEnded).map(t=>t.id||t.task_id));return agents.filter(a=>{if(a.kind==='history')return false;if(a.kind==='managed'){const id=a.task_id||(a.id?.startsWith('managed:')?a.id.slice(8):'');return !ended.has(id)&&!isTaskEnded(a);}return a.kind==='native'&&(a.available||a.connected||a.pid||a.generation);});}
const operationNames={replace:'替换',hardlink:'硬链接',symlink_write:'经符号链接写入',ancestor_rename:'改名父目录',mmap_new:'共享映射写入',hold:'持有文件句柄',fd_write:'通过已有句柄写入',write:'写入',write_open:'打开写入',read:'读取',unlink:'删除',rename:'重命名',mkdir:'创建目录',rmdir:'删除目录',execute:'执行'};
export function auditOperation(row){return operationNames[row.operation]||row.operation||'操作未记录';}
export function auditSource(row){return ({independent_probe:'验收探针',native_tool:'DSH',kernel:'ActPlane 内核',controller:'控制面'})[row.source]||'来源未记录';}
export function auditIdentity(row){return `PID ${row.pid??'未记录'} / 域 ${row.domain_id??'未记录'} / ${auditSource(row)}`;}
export function pendingReviewRecord(pending,data,parent){const p=pending?.proposal||{},resources=data?.state?.version===pending?.base_version?data?.resources||{}:{},before=resources.runtime_protected,after=p.protected_paths;const full=parent?.id==='runtime:'+pending.job_id?parent:{};return {...full,id:'runtime:'+pending.job_id,stage:'runtime',effect:p.decision||full.effect,status:'pending_confirmation',statement:p.decision==='restrict'?'权限收紧候选（完整范围）':'权限扩展候选（完整范围）',identified_statements:full.identified_statements||p.identified_statements||[],targets:full.targets||[],delta:{write_scope_before:resources.allowed_write_dirs,write_scope_after:p.allowed_write_dirs,output_before:resources.allow_output,output_after:p.allow_output,added_protection:Array.isArray(after)&&Array.isArray(before)?after.filter(v=>!before.includes(v)):undefined,removed_protection:Array.isArray(after)&&Array.isArray(before)?before.filter(v=>!after.includes(v)):undefined,...full.delta},review:{base_version:full.base_version??pending.base_version,process_generation:full.process_generation,revision:pending.revision,base_policy_hash:full.base_policy_hash??pending.base_policy_hash,binding:pending.binding,candidate_hash:pending.hash},loading:full.loading||{loaded:false,candidate_hash:pending.hash},compilation:full.compilation||{status:'not_applicable'},created_at:full.created_at||p.created_at};}
export function archiveAuditMetadata(event){const d=event.detail||{},source=event.action_source||d.action_source;const names={independent_probe:'验收探针',native_tool:'DSH',kernel:'ActPlane 内核',controller:'控制面',user_request:'用户请求',agent_report:'Agent报告',not_recorded:'来源未记录'};return {source:names[source]||'来源未记录',operation:d.operation||d.probe?.operation||d.kernel?.operation,target:d.target||d.probe?.target||d.kernel?.target,pid:d.pid??d.probe?.pid??d.kernel?.pid,domain:d.domain_id??d.probe_binding?.domain_id,result:d.classification||d.result||event.status};}
export function auditPageAction(loaded,visible,cursor,size=12){return visible<loaded?{type:'reveal',visible:Math.min(loaded,visible+size)}:cursor?{type:'fetch',visible:loaded+size,cursor}:{type:'done',visible};}
export function mergeAuditRecords(before,after){const map=new Map(before.map(r=>[r.id,r]));for(const row of after)map.set(row.id,row);return [...map.values()];}
export function canReadWorkspace(workspaces,id){return !!id&&workspaces.some(w=>w.id===id&&w.readable===true);}
