import React,{useCallback,useEffect,useRef,useState} from 'react';
import GenerationResults,{GenerationStatus} from './GenerationResults.jsx';
import {states,phases,time,sourceName} from './generationPresentation.js';
const names={history_generation:'统一策略生成',collect:'文档采集',extract:'语句抽取',translate:'策略转 DSL',compile:'编译检查',rq1_import:'RQ1 语料准备',task_bootstrap:'Pi 启动前生成'};
const runStates=['queued','running','completed','partial','failed','cancelled','interrupted'];
const actions={history_generation_retried:'生成检查点重试',history_generation_created:'创建生成记录',history_generation_final_review:'最终候选审核',history_completeness_review:'完整性二审',history_generation_cancel_requested:'取消生成',rq1_corpus_import:'RQ1 语料导入',history_input_registered:'登记转换输入',history_extracted:'语句抽取完成',history_statement_review:'语句版本审核',history_statement_revised:'语句版本修订',history_artifact_review:'DSL 候选审核',history_artifact_duplicate_result:'重复产物复用',strategy_review:'目录策略审核',strategy_created:'创建策略',strategy_updated:'修改目录策略',strategy_archived:'归档策略',strategy_restored:'恢复策略'};

function GenerationRecord({id,api,post,busy,action,notify,onBack,onContinueReview}){
 const [run,setRun]=useState(null),[jobs,setJobs]=useState([]),[error,setError]=useState('');
 const sequence=useRef(0);
 const load=useCallback(async()=>{const n=++sequence.current;try{const [value,attempts]=await Promise.all([api('/api/history/generations/'+id),api('/api/history/activity?'+new URLSearchParams({section:'jobs',kind:'history_generation',q:id,limit:'100'}))]);if(n!==sequence.current)return;setRun(value);setJobs(attempts.items);setError('')}catch(e){if(n===sequence.current)setError(e.message)}},[api,id]);
 useEffect(()=>{load();const timer=setInterval(load,5000);return()=>{sequence.current++;clearInterval(timer)}},[load]);
 if(!run)return <section className="panel"><button className="button ghost" onClick={onBack}>返回生成记录</button><p>{error||'正在读取生成记录'}</p></section>;
 return <div className="generation-record-detail"><div className="panel-head"><div><h2>历史结果与生成过程</h2><p className="field-note">{sourceName(run)} · {time(run.created_at)}</p></div><div className="button-row"><button className="button ghost" onClick={onBack}>返回生成记录</button><button className="button primary" disabled={busy} onClick={()=>onContinueReview(id)}>继续审核</button></div></div>
  <section className="panel generation-summary"><div className="button-row"><GenerationStatus value={run.status}/><span>阶段：{phases[run.stage]||'处理记录'}</span>{['queued','running'].includes(run.status)&&<button className="button tiny ghost" disabled={busy||!!run.cancel_requested} onClick={()=>action(async()=>{await post('/api/history/generations/'+id+'/cancel');await load();notify('已请求取消，当前调用结束后生效')})}>取消生成</button>}{['failed','partial','cancelled','interrupted'].includes(run.status)&&<button className="button tiny ghost" disabled={busy} onClick={()=>action(async()=>{await post('/api/history/generations/'+id+'/retry');await load();notify('已从检查点排队重试')})}>从检查点重试</button>}</div>{run.error&&<p className="error">{run.error}</p>}{error&&<p className="error">{error}</p>}
   <details><summary>来源、输入与生成编号</summary><dl className="record-metadata"><dt>生成编号</dt><dd>{id}</dd><dt>开始 / 结束</dt><dd>{time(run.created_at)} / {time(run.finished_at)}</dd></dl><pre>{JSON.stringify({input:run.input,source:run.source},null,2)}</pre></details>
   <details><summary>处理步骤与诊断</summary>{run.steps.map(step=><details key={step.step_key}><summary>{phases[step.stage]||'处理记录'} · {states[step.status]||step.status}</summary>{step.error&&<p className="error">{step.error}</p>}<pre>{JSON.stringify(step.result,null,2)}</pre></details>)}{!run.steps.length&&<p className="field-note">尚未开始处理。</p>}</details>
   <details><summary>执行与重试记录（{jobs.length}）</summary>{jobs.map(job=><div className="generation-attempt" key={job.id}><GenerationStatus value={job.status}/><small>{time(job.created_at)} · {job.id}</small>{job.retry_of&&<small>重试来源：{job.retry_of}</small>}{job.error&&<p className="error">{job.error}</p>}</div>)}</details>
  </section>
  <GenerationResults key={id} runId={id} api={api} post={post} busy={busy} action={action} notify={notify} readOnly/>
 </div>;
}

export default function HistoryAudit({api,post,busy,action,notify,selectedRunId,onSelectRun,onContinueReview}){
 const [section,setSection]=useState('generations'),[kind,setKind]=useState(''),[status,setStatus]=useState(''),[q,setQ]=useState(''),[offset,setOffset]=useState(0);
 const [page,setPage]=useState({items:[],total:0});
 const request=useRef(0);
 const load=useCallback(async()=>{if(selectedRunId)return;const sequence=++request.current;const url=section==='generations'?'/api/history/generations/page?':'/api/history/activity?';const result=await api(url+new URLSearchParams({...(section==='generations'?{}:{section,kind}),status,q,offset:String(offset),limit:'20'}));if(sequence===request.current)setPage(result)},[api,section,kind,status,q,offset,selectedRunId]);
 useEffect(()=>{load().catch(e=>notify(e.message));const timer=setInterval(()=>load().catch(()=>{}),5000);return()=>{request.current++;clearInterval(timer)}},[load,notify]);
 const filter=(setter,value)=>{setter(value);setOffset(0)};
 const change=mode=>{setSection(mode);setKind('');setStatus('');setQ('');setOffset(0);setPage({items:[],total:0});onSelectRun('')};
 return <div className="history-audit"><div className="panel-head"><div><h2>生成记录与审计</h2><p>查看历次生成及其保存结果、处理步骤、失败诊断和审核操作；历史预览不改变当前审核对象。</p></div></div>
  <div className="segmented audit-sections" aria-label="生成记录视图">{[['generations','生成记录'],['jobs','后台作业'],['events','操作日志']].map(([value,title])=><button key={value} className={section===value?'sel':''} aria-pressed={section===value} onClick={()=>change(value)}>{title}</button>)}</div>
  {selectedRunId?<GenerationRecord key={selectedRunId} id={selectedRunId} api={api} post={post} busy={busy} action={action} notify={notify} onBack={()=>onSelectRun('')} onContinueReview={onContinueReview}/>:<>
   <div className="toolbar records-toolbar">{section!=='generations'&&<label>记录类型<select aria-label="筛选记录类型" value={kind} onChange={e=>filter(setKind,e.target.value)}><option value="">全部类型</option>{Object.entries(section==='jobs'?names:actions).map(([value,title])=><option key={value} value={value}>{title}</option>)}</select></label>}{section!=='events'&&<label>{section==='generations'?'生成状态':'作业状态'}<select aria-label={section==='generations'?'筛选生成状态':'筛选作业状态'} value={status} onChange={e=>filter(setStatus,e.target.value)}><option value="">全部状态</option>{runStates.map(value=><option key={value} value={value}>{states[value]}</option>)}</select></label>}<label className="audit-search">搜索记录<input aria-label="搜索审计记录" placeholder={section==='generations'?'仓库、commit 或生成编号':'作业 ID、仓库、版本或操作人'} value={q} onChange={e=>filter(setQ,e.target.value)}/></label></div>
   <div className="records-pagination"><span>{page.total} 条记录</span><div className="button-row"><button className="button tiny ghost" disabled={offset===0||busy} onClick={()=>setOffset(Math.max(0,offset-20))}>上一页</button><button className="button tiny ghost" disabled={offset+page.items.length>=page.total||busy} onClick={()=>setOffset(offset+20)}>下一页</button></div></div>
   {section==='generations'?<section className="panel table-panel"><div className="table-scroll"><table className="generation-records-table"><thead><tr><th>来源</th><th>生成时间</th><th>状态</th><th>产出</th><th>操作</th></tr></thead><tbody>{page.items.map(row=><tr key={row.id} data-generation-id={row.id}><td>{sourceName(row)}{row.input?.statement_version_id&&<small>单条策略二审 / 生成</small>}{row.source?.commit&&!row.source.repository?.startsWith('manual/')&&<small>commit：{row.source.commit.slice(0,12)}</small>}</td><td>{time(row.created_at)}</td><td><GenerationStatus value={row.status}/></td><td>{Object.entries(row.statistics||{}).map(([state,count])=><small key={state}>{states[state]||state} {count}</small>)}{!Object.keys(row.statistics||{}).length&&<small>尚无策略结果</small>}</td><td><button className="button tiny ghost" onClick={()=>onSelectRun(row.id)}>查看结果</button></td></tr>)}{!page.items.length&&<tr><td colSpan="5" className="empty-row">暂无符合条件的生成记录。</td></tr>}</tbody></table></div></section>:<>
    {page.items.map(row=><article className="panel audit-record" key={row.id}><div className="panel-head"><div><b>{section==='jobs'?names[row.kind]||row.kind:actions[row.action]||row.action}</b><small>{time(row.created_at)} · {row.id}</small></div>{section==='jobs'?<GenerationStatus value={row.status}/>:<span className="tag">{row.actor}</span>}</div>
     {section==='jobs'?<><dl className="record-metadata"><dt>开始 / 结束</dt><dd>{time(row.started_at)} / {time(row.finished_at)}</dd>{row.retry_of&&<><dt>重试来源</dt><dd>{row.retry_of}</dd></>}</dl>{row.error&&<p className="error">{row.error}</p>}<details><summary>输入</summary><pre>{JSON.stringify(row.input,null,2)}</pre></details><details><summary>结果与产物引用</summary><pre>{JSON.stringify(row.result,null,2)}</pre></details>{row.kind==='history_generation'?<button className="button tiny ghost" onClick={()=>{setSection('generations');onSelectRun(row.input.run_id)}}>查看生成记录</button>:['failed','interrupted'].includes(row.status)&&<button className="button tiny ghost" disabled={busy} onClick={()=>action(async()=>{await post('/api/history/jobs/'+row.id+'/retry');await load();notify('重试作业已排队')})}>重试作业</button>}</>:<details><summary>审计详情与版本引用</summary><pre>{JSON.stringify(row.details,null,2)}</pre></details>}
    </article>)}{!page.items.length&&<div className="panel empty-box">暂无符合条件的记录。</div>}
   </>}
  </>}
 </div>;
}
