import React,{useEffect,useRef,useState} from 'react';
import './managed.css';
const names={'safety-impossible-tests':'支付验证：修复代码，保护测试','safety-delete-config':'工作区清理：保留有效配置'};
const phases={prepared:'待启动',generating:'生成启动策略',running:'运行中',failed:'已暂停',recovering:'恢复中',ended:'已结束'};
const types={per_event:'单事件策略',cross_event:'跨事件策略',content:'内容策略',semantic_only:'语义指导',assessment:'上下文评估'};
const statuses={unmapped:'规则未映射',active:'正在生效',paused:'执行暂停',revoked:'已撤销',validated:'已校验',guidance:'任务指导',pending_confirmation:'待确认',needs_clarification:'待澄清',partially_active:'部分仍生效',superseded:'已被后续版本替代',expired:'候选已过期',assessed:'评估完成',invalid:'未通过校验'};
const effects={block:'禁止修改',restrict:'权限收紧',expand:'权限扩展',guidance_only:'任务指导',guidance:'任务指导',no_change:'无需变更'};
const kinds={kernel:'内核拒绝',operation_verified:'效果核验',tool_start:'工具开始',tool_result:'工具结果',control_pause:'执行暂停',failure:'执行故障',feedback_delivery:'反馈送达',policy_active:'策略加载',closed:'结束撤权'};
const results={denied:'已拒绝',correct_block:'正确拦截',correct_allow:'实际允许',false_block:'误拦截',missed_block:'漏拦截',success:'工具成功',failure:'工具失败',started:'已开始',control_pause:'暂停',feedback_delivery:'已送达',policy_active:'已加载',closed:'已撤销',operation_failed:'操作失败',unverified_denial:'拒绝未核验'};
const sources={kernel:'ActPlane 内核',native_tool:'DSH 工具',controller:'控制面',independent_probe:'独立验收探针'};
const when=value=>value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'—';
function Tag({children,good=false}){return <span className={'record-tag'+(good?' good':'')}>{children}</span>;}
function Fields({items}){return <dl className="record-fields">{items.filter(([,v])=>v!==undefined&&v!==null).map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{typeof v==='boolean'?(v?'是':'否'):Array.isArray(v)?v.join('、')||'无':v||'无'}</dd></React.Fragment>)}</dl>;}
function Drawer({detail,onClose}){
 const ref=useRef(null),[pane,setPane]=useState('statement');
 useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);
 const r=detail.record,hook=detail.hook,a=detail.audit;
 return <dialog ref={ref} className="record-drawer" onCancel={onClose} aria-label={r?'策略记录详情':a?'执行记录详情':'工作区与触发详情'}><div className="record-drawer-head"><h2>{r?'策略记录':a?kinds[a.kind]:'绑定与触发'}</h2><button className="button ghost tiny" onClick={onClose}>关闭</button></div>
 {r?<><div className="record-drawer-tabs" role="tablist" aria-label="策略记录详情">{[['statement','语句与类型'],['context','上下文'],['dsl','DSL'],['loading','加载']].map(([id,label])=><button key={id} role="tab" aria-selected={pane===id} onClick={()=>setPane(id)}>{label}</button>)}</div><div className="record-drawer-body">
 {pane==='statement'&&<><Tag>{r.stage==='startup'?'运行前':'运行时'}</Tag><p className="record-statement">{r.statement}</p><Fields items={[["策略类型",types[r.policy_type]],["处理方式",effects[r.effect]],["记录状态",statuses[r.status]||r.status],["需要上下文",r.context_required],["操作",r.operations],["对象",r.targets],["识别来源",r.origin==='parameterize'?'审核模板参数化':r.origin==='new_candidate'?'Pi 新候选':r.identified_statements?.some(s=>s.origin!=='authenticated_target_clause')?'Pi 结构化识别':r.classification_origin?.includes('historical')?'已校验增量 / 历史真实条款':r.classification_origin==='authenticated_delta_request'?'历史认证请求 / 增量关联':r.classification_origin==='authenticated_target_clause'?'历史认证目标条款':r.effect==='guidance'?'Pi 任务指导':'Pi 识别 / 控制面结构校验'],["生成时间",when(r.created_at)]]}/>{r.identified_statements?.length>0&&<><h3>识别语句</h3>{r.identified_statements.map((s,i)=><article className="record-evidence" key={i}><p>{s.statement}</p><Fields items={[["类型",types[s.policy_type]],["需要上下文",s.context_required],["依据",s.context_reason],["来源",s.origin==='authenticated_target_clause'?'真实用户目标条款':'Pi 结构化识别']]}/></article>)}</>}{r.explanation&&<details className="record-note"><summary>评估理由</summary><p>{r.explanation}</p></details>}</>}
 {pane==='context'&&<><Fields items={[["需要上下文",r.context_required],["原因",r.context_reason],["范围",({project:'项目工作区',task:'任务'})[r.context_scope]],["触发",r.trigger?.name],["关联轮次",r.trigger?.turn],["上下文版本",r.trigger?.revision]]}/><h3>证据来源</h3>{r.evidence?.map(e=><article className="record-evidence" key={e.id}><Fields items={[["来源",e.role],["路径",e.path],["已读取",e.read_verified],["内容哈希",e.content_hash],["证据 ID",e.id]]}/></article>)}{!r.evidence?.length&&<p className="muted">该指导项没有独立的逐条来源映射。</p>}{r.trigger?.observations?.length>0&&<details className="record-note"><summary>原生上下文观察</summary>{r.trigger.observations.map(o=><Fields key={o.category} items={[["类型",o.type],["事件序号",o.seq],["内容哈希",o.content_hash]]}/>)}</details>}</>}
 {pane==='dsl'&&<><p className="record-statement">{r.statement}</p><Fields items={[["编译",r.compilation.status==='compiled'?'通过':r.compilation.status==='not_applicable'?'不适用':'对应规则尚未登记'],["DSL 来源",({statement_compiler_clauses:'该语句对应的编译子句',compiler_rule_source:'该语句对应的编译规则',semantic_guidance:'语义指导，无 OS DSL',permission_update:'权限变更，无新增拒绝规则',assessment_no_rule:'上下文评估，无逐句规则',unmapped_statement:'该语句尚无可靠规则关联'})[r.compilation.origin]],["规则片段哈希",r.compilation.dsl_hash]]}/>{r.compilation.message&&<p className="muted">{r.compilation.message}</p>}{r.compilation.reused&&<p className="muted">该语句沿用已有规则，本轮没有重新加载。</p>}{r.compilation.dsl&&<pre className="record-code">{r.compilation.dsl}</pre>}</>}
 {pane==='loading'&&<><Fields items={[["记录状态",statuses[r.status]||r.status],["已加载该变更",r.loading.loaded],[r.loading.loaded?"加载版本":"评估回执版本",r.loading.version?`v${r.loading.version}`:undefined],["确认回执",r.loading.confirmation],["会话",r.loading.session_id],["策略候选哈希",r.loading.candidate_hash],["启动底线哈希",r.loading.baseline_hash],["启动底线保留",r.loading.baseline_retained]]}/>{r.delta&&<><h3>权限变化</h3><Fields items={[["新增保护",r.delta.added_protection],["解除运行时保护",r.delta.removed_protection],["写入范围：之前",r.delta.write_scope_before],["写入范围：之后",r.delta.write_scope_after],["输出可写：之前",r.delta.output_before],["输出可写：之后",r.delta.output_after]]}/></>}{r.loading.binding&&<details className="record-note"><summary>进程绑定</summary><Fields items={[["策略域",r.loading.binding.domain_id],["执行进程",r.loading.binding.runner_pid]]}/></details>}</>}
 </div></>:a?<div className="record-drawer-body"><Fields items={[["记录层",a.category==='os'?'OS 操作':a.category==='tools'?'工具调用':'控制面'],["来源",sources[a.source]],["时间",when(a.time)],["操作",a.operation],["对象",a.target],["结果",results[a.result]||a.result],["原因",a.reason],["工具调用",a.call_id],["实际 PID",a.pid],["策略域",a.domain_id],["策略版本",a.version?`v${a.version}`:undefined],["关联反馈",a.feedback_event_ids]]}/>{a.rule&&<><h3>命中规则</h3><Fields items={[["规则",typeof a.rule==='string'?a.rule:a.rule.name||a.rule.rule_id],["原因",a.rule.reason]]}/>{a.rule.source_text&&<pre className="record-code">{a.rule.source_text}</pre>}</>}<p className="muted">工具成功不等于所有 OS 操作都已放行。OS 区记录内核拒绝与独立效果核验。</p></div>:<div className="record-drawer-body"><Fields items={[["工作区",detail.binding?.workspace],["Session ID",detail.binding?.session_id],["实际进程绑定",detail.binding?.process_verified]]}/>{hook&&<><h3>{hook.name}</h3><Fields items={[["触发事件",hook.events]]}/><ol className="record-hook-flow">{hook.sequence.map(s=><li key={s}>{s}</li>)}</ol></>}</div>}
 </dialog>;
}
export default function ManagedWorkbench({api,post,notify,task,onSelectTask}){
 const [data,setData]=useState(null),[binding,setBinding]=useState(null),[resolved,setResolved]=useState(false),[matches,setMatches]=useState([]),[choosing,setChoosing]=useState(false),[creating,setCreating]=useState(false),[scene,setScene]=useState('safety-impossible-tests'),[busy,setBusy]=useState(false),[detail,setDetail]=useState(null),[stage,setStage]=useState('startup'),[category,setCategory]=useState('os'),[records,setRecords]=useState({records:[]}),[audit,setAudit]=useState({records:[]}),[runtimeFilter,setRuntimeFilter]=useState(''),[startupFilter,setStartupFilter]=useState('per_event'),[before,setBefore]=useState(null),[constraint,setConstraint]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const key=JSON.stringify([task,stage,category,before,creating]),active=useRef(key);active.current=key;
 async function load(){const current=key;try{
  const lookup=await api('/api/managed/workspace-binding'+(task?'?task_id='+task:''));if(active.current!==current)return;
  setBinding(lookup.binding);setMatches(lookup.candidates);setResolved(true);
  if(!task&&!creating&&lookup.binding){onSelectTask(lookup.binding.task_id);return;}
  if(task&&lookup.binding){const [state,list]=await Promise.all([api(`/api/managed/tasks/${task}/workbench`),api(stage==='audit'?`/api/managed/tasks/${task}/execution-audit?category=${category}${before===null?'':`&before=${before}`}`:`/api/managed/tasks/${task}/strategy-records?stage=${stage}&include_assessments=false${before===null?'':`&before=${before}`}`)]);if(active.current!==current)return;setData(state);stage==='audit'?setAudit(list):setRecords(list);}
  setError('');setLoading(false);
 }catch(e){if(active.current===current){setError(e.message);setLoading(false);}}}
 useEffect(()=>{setData(null);setResolved(false);setDetail(null);setBefore(null);setConstraint('');},[task]);
 useEffect(()=>{setLoading(true);load();const timer=setInterval(load,3000);return()=>clearInterval(timer);},[key]);
 const run=async(fn)=>{setBusy(true);try{await fn();await load();}catch(e){notify(e.message);}finally{setBusy(false);}};
 const switchStage=value=>{setRecords({records:[]});setAudit({records:[]});setLoading(true);setStage(value);setBefore(null);};
 const openRecord=r=>run(async()=>{const current=key,record=await api(`/api/managed/tasks/${task}/strategy-records/${encodeURIComponent(r.id)}`);if(active.current===current)setDetail({record});});
 const s=data?.state,pending=s?.pending_expansion,filter=stage==='startup'?startupFilter:runtimeFilter,shown=filter?records.records.filter(r=>r.policy_type===filter):records.records;
 return <div className="content managed-workbench"><div className="page-heading"><h1>任务工作台</h1><div className="actions"><button className="button ghost" onClick={()=>{setChoosing(!choosing);if(!choosing)run(async()=>{const all=await api('/api/tasks');setMatches(all.filter(t=>t.dsh_profile==='web').map(t=>({task_id:t.id,name:t.name,workspace:t.workspace,phase:t.status})));});}}>切换工作区</button><button className="button ghost" onClick={()=>{setCreating(true);onSelectTask('');}}>新建任务</button></div></div>
 {error&&<p role="alert" className="inline-notice warning">读取失败：{error}</p>}
 {choosing&&<section className="panel workspace-choice"><h2>已登记 DSH 工作区</h2>{matches.map(m=><button className="workspace-option" key={m.task_id} onClick={()=>{setCreating(false);setChoosing(false);onSelectTask(m.task_id);}}><b>{names[m.name]||m.name}</b><code>{m.workspace}</code><Tag>{phases[m.phase]||m.phase}</Tag></button>)}</section>}
 {!task&&!creating&&resolved&&!binding&&<section className="panel"><h2>{matches.length?'发现多个活动工作区':'尚无受管工作区'}</h2><p className="muted">{matches.length?'请选择对应的 DSH 工作区，系统将核对 Session 与进程绑定。':'从新建任务开始，启动前由 Pi 识别并编译策略。'}</p>{matches.map(m=><button className="workspace-option" key={m.task_id} onClick={()=>onSelectTask(m.task_id)}><b>{names[m.name]||m.name}</b><code>{m.workspace}</code></button>)}</section>}
 {creating&&!task&&<section className="panel"><h2>新建受管任务</h2><div className="bootstrap-controls"><select aria-label="工作任务" value={scene} onChange={e=>setScene(e.target.value)}>{Object.entries(names).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><button className="button primary" disabled={busy} onClick={()=>run(async()=>{const x=await post(`/api/managed/scenarios/${scene}/tasks`);setCreating(false);onSelectTask(x.id);await post(`/api/managed/tasks/${x.id}/start`);})}>启动前生成策略</button></div></section>}
 {!creating&&!resolved&&!error&&<p className="muted">正在识别 DSH 工作区…</p>}
 {task&&resolved&&!binding&&!error&&<p className="muted">当前任务没有登记受管 DSH 工作区。可切换已登记工作区或新建任务。</p>}
 {s&&binding&&<><section className="workspace-strip"><div><b>{names[binding.name]||binding.name}</b><code>{binding.workspace}</code></div><div className="actions"><Tag good={data.effective}>{phases[s.phase]||s.phase}</Tag><Tag>{s.version?`策略 v${s.version}`:'未加载'}</Tag><button className="button tiny ghost" onClick={()=>setDetail({binding})}>绑定详情</button>{s.web_url&&s.phase==='running'&&<a className="button primary" href={`/api/managed/tasks/${task}/open`} target="_blank" rel="noreferrer">打开 DSH</a>}{['prepared','failed'].includes(s.phase)&&<button className="button primary" disabled={busy} onClick={()=>run(()=>post(`/api/managed/tasks/${task}/start`))}>{s.phase==='failed'?'重新校验并恢复':'启动 Pi'}</button>}{!['prepared','ended'].includes(s.phase)&&<button className="button ghost" disabled={busy} onClick={()=>run(()=>post(`/api/managed/tasks/${task}/close`))}>结束任务</button>}</div></section>
 {s.error&&<p role="alert" className="inline-notice warning">暂停原因：{s.error}</p>}
 {s.phase==='failed'&&s.version===0&&<details className="panel" open><summary>补充启动任务信息</summary><textarea aria-label="启动任务澄清" rows="3" value={constraint} onChange={e=>setConstraint(e.target.value)}/><button className="button primary" disabled={busy||!constraint.trim()} onClick={()=>run(async()=>{await post(`/api/managed/tasks/${task}/startup/clarify`,{text:constraint});setConstraint('');})}>重新交给 Pi 校验</button></details>}
 <div className="tabs managed-main-tabs" role="tablist" aria-label="任务记录">{[['startup','运行前策略'],['runtime','运行时策略'],['audit','执行审计']].map(([id,label])=><button role="tab" aria-selected={stage===id} className={stage===id?'active':''} key={id} onClick={()=>switchStage(id)}>{label}</button>)}</div>
 {stage!=='audit'?<section className="panel policy-record-panel"><div className="record-list-head"><h2>{stage==='startup'?'运行前策略':'运行时策略'}</h2><div className="actions"><button className="button tiny ghost" onClick={()=>setDetail({binding,hook:records.hook})}>Hook 触发方式</button>{stage==='startup'?<select aria-label="策略类型筛选" value={startupFilter} onChange={e=>setStartupFilter(e.target.value)}><option value="per_event">OS 执行策略</option><option value="semantic_only">任务指导</option><option value="">全部策略</option></select>:<select aria-label="运行时策略类型" value={runtimeFilter} onChange={e=>setRuntimeFilter(e.target.value)}><option value="">全部语句</option><option value="per_event">OS 执行策略</option><option value="semantic_only">任务指导</option></select>}</div></div>
 {pending&&stage==='runtime'&&<div className="record-pending"><Tag>扩权待确认</Tag><button className="button ghost tiny" onClick={()=>openRecord({id:'runtime:'+pending.job_id})}>查看候选</button><button className="button primary tiny" disabled={busy} onClick={()=>run(()=>post(`/api/managed/tasks/${task}/expansion/confirm`,{expected_hash:pending.hash}))}>确认并加载</button></div>}
 {stage==='runtime'&&<p className="record-caption">{s.gate==='open'?'监控中':s.gate==='waiting_clarification'?'待澄清，执行暂停':'Pi 正在评估，执行暂停'}<span>{records.counts?.no_change||0} 次评估无需调整权限</span></p>}
 <div className="policy-record-list">{shown.map(r=><button className="policy-record" key={r.id} onClick={()=>openRecord(r)}><div className="record-line"><b>{r.targets?.length?r.targets.map(t=>t.replace(binding.workspace+'/','')).join('、'):effects[r.effect]||types[r.policy_type]}</b><Tag good={r.status==='active'}>{statuses[r.status]||r.status}</Tag></div><p>{r.statement}</p><div className="record-tags"><Tag>{types[r.policy_type]}</Tag><Tag>{r.context_required?'需上下文':'无需上下文'}</Tag><Tag>{r.compile_status==='compiled'?(r.effect==='no_change'||r.effect==='guidance_only'?'沿用对应规则':'编译通过'):r.compile_status==='not_applicable'?'无 OS DSL':'对应规则待映射'}</Tag><span>{r.stage==='runtime'?r.trigger.name:'启动前识别'}</span><span className="record-open">查看记录 ›</span></div></button>)}</div>{!shown.length&&<p className="record-empty">{loading?'正在读取记录…':stage==='startup'?'尚无此类策略记录。':'尚无识别出的策略语句。'}</p>}
 {before!==null&&<button className="button ghost tiny" onClick={()=>setBefore(null)}>返回最新记录</button>}{records.next_cursor&&<button className="button ghost tiny" onClick={()=>setBefore(records.next_cursor)}>更早记录</button>}
 </section>:<section className="panel policy-record-panel"><div className="record-list-head"><h2>执行审计</h2><select aria-label="审计层" value={category} onChange={e=>{setAudit({records:[]});setLoading(true);setCategory(e.target.value);setBefore(null);}}><option value="os">OS 操作</option><option value="tools">工具调用</option><option value="control">控制面</option></select></div><p className="record-caption">{category==='os'?'内核拒绝与独立文件效果核验':category==='tools'?'DSH 工具开始与返回结果；成功不等于 OS 放行证明':'暂停、反馈送达、策略加载与撤权'}</p><div className="audit-record-list">{audit.records.map(a=><button className="audit-record" key={a.id} onClick={()=>setDetail({audit:a})}><div><Tag>{kinds[a.kind]}</Tag><b>{a.target?a.target.replace(binding.workspace+'/',''):a.operation}</b></div><div><span>{sources[a.source]}</span><Tag good={['success','correct_allow','correct_block'].includes(a.result)}>{results[a.result]||a.result}</Tag><time>{when(a.time)}</time><span>详情 ›</span></div></button>)}</div>{!audit.records.length&&<p className="record-empty">{loading?'正在读取记录…':'尚无此层审计记录。'}</p>}{before!==null&&<button className="button ghost tiny" onClick={()=>setBefore(null)}>返回最新记录</button>}{audit.next_cursor&&<button className="button ghost tiny" onClick={()=>setBefore(audit.next_cursor)}>更早记录</button>}</section>}
 </>}
 {detail&&<Drawer key={detail.record?.id||detail.audit?.id||'hook'} detail={detail} onClose={()=>setDetail(null)}/>}
 </div>;
}
