import React,{useEffect,useRef,useState} from 'react';
import './managed.css';
import {ArchiveDrawer} from './TaskArchive.jsx';
import {TaskRecord} from './TaskHub.jsx';
import {tabKeys,pendingChangeLabel,runtimeCaption,recordPermissionLabel,isTaskEnded,auditOperation,auditIdentity,auditSource,pendingReviewRecord,auditPageAction,mergeAuditRecords} from './consoleState.mjs';
import RuntimeOverview from './RuntimeOverview.jsx';
import RuntimeDetails from './RuntimeDetails.jsx';
import {connectionView} from './runtimeView.mjs';
const names={'safety-impossible-tests':'支付验证：修复代码，保护测试','safety-delete-config':'工作区清理：保留有效配置'};
const phases={completed:'已结束',prepared:'待生成策略',generating:'生成启动策略',policy_review:'待确认策略',running:'运行中',failed:'已暂停',recovering:'恢复中',ended:'已结束'};
const types={per_event:'单事件策略',cross_event:'跨事件策略',content:'内容策略',semantic_only:'语义指导',assessment:'上下文评估'};
const statuses={unmapped:'规则未映射',active:'历史加载',loaded:'已加载',partially_loaded:'部分条款已加载',paused:'执行暂停',revoked:'已撤销',validated:'已校验',guidance:'任务指导',pending_confirmation:'待确认',needs_clarification:'待澄清',partially_active:'部分条款历史加载',superseded:'已被后续版本替代',expired:'候选已过期',rejected:'人工已拒绝',assessed:'评估完成',invalid:'未通过校验'};
const effects={block:'禁止修改',restrict:'权限收紧',expand:'权限扩展',guidance_only:'任务指导',guidance:'任务指导',no_change:'无需变更'};
const kinds={kernel:'内核拒绝',operation_verified:'效果核验',tool_start:'工具开始',tool_result:'工具结果',control_pause:'执行暂停',failure:'执行故障',feedback_delivery:'反馈送达',policy_active:'策略加载',closed:'结束撤权'};
const results={denied:'已拒绝',correct_block:'正确拦截',correct_allow:'实际允许',false_block:'误拦截',missed_block:'漏拦截',success:'工具成功',failure:'工具失败',started:'已开始',control_pause:'暂停',feedback_delivery:'已送达',policy_active:'已加载',closed:'已撤销',operation_failed:'操作失败',unverified_denial:'拒绝未核验'};
const sources={kernel:'ActPlane 内核',native_tool:'DSH',controller:'控制面',independent_probe:'验收探针'};
const when=value=>value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'—';
function Tag({children,good=false}){return <span className={'record-tag'+(good?' good':'')}>{children}</span>;}
function Fields({items}){return <dl className="record-fields">{items.filter(([,v])=>v!==undefined&&v!==null).map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{typeof v==='boolean'?(v?'是':'否'):Array.isArray(v)?v.join('、')||'无':v||'无'}</dd></React.Fragment>)}</dl>;}
const relations={new:'新增规则',reuses:'复用规则',baseline_covered:'底线已覆盖',contains:'范围重叠',overlap:'范围重叠',unknown:'待澄清',equivalent_retained:'等价保留'};
function NormalTags({record}){
 const n=record.normalization;
 if(!n||n.status==='legacy_unanalysed')return <Tag>历史未分析</Tag>;
 const values=[...new Set([...(n.links||[]).map(l=>l.relation),...(n.relations||[]).map(r=>r.relation)])];
 return <>{values.map(v=><Tag key={v}>{relations[v]||v}</Tag>)}</>;
}
function Drawer({detail,onClose,onRecord}){
 const ref=useRef(null),[pane,setPane]=useState(detail.pending?'change':'statement'),[clause,setClause]=useState(0);
 useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);
 const r=detail.record,hook=detail.hook,a=detail.audit;
 return <dialog ref={ref} className="record-drawer" onCancel={onClose} aria-label={r?'策略记录详情':a?'执行记录详情':'工作区与触发详情'}><div className="record-drawer-head"><h2>{r?'策略记录':a?kinds[a.kind]:'绑定与触发'}</h2><button className="button ghost tiny" onClick={onClose}>关闭</button></div>
 {r?<><div className="record-drawer-tabs" role="tablist" aria-label="策略记录详情">{[...(detail.pending?[['change','权限变化']]:[]),['statement','语句与类型'],['context','上下文'],['dsl','DSL'],['loading','加载']].map(([id,label])=><button key={id} role="tab" aria-selected={pane===id} onClick={()=>setPane(id)}>{label}</button>)}</div><div className="record-drawer-body">
 {pane==='change'&&<><h3>本次候选完整范围</h3><Fields items={[["output 可写",`${r.delta?.output_before===undefined?'未记录':r.delta.output_before} → ${r.delta?.output_after===undefined?'未记录':r.delta.output_after}`],["写入目录",`${Array.isArray(r.delta?.write_scope_before)?r.delta.write_scope_before.join('、')||'无':'未记录'} → ${Array.isArray(r.delta?.write_scope_after)?r.delta.write_scope_after.join('、')||'无':'未记录'}`],["新增保护",r.delta?.added_protection||'未记录'],["撤销保护",r.delta?.removed_protection||'未记录'],["基准版本",r.review?.base_version===undefined?'未记录':'v'+r.review.base_version],["上下文修订",r.review?.revision??'未记录'],["基准执行进程",r.review?.binding?.runner_pid??'未记录'],["基准策略域",r.review?.binding?.domain_id??'未记录'],["基准执行代次",r.review?.process_generation?`PID ${r.review.process_generation.runner_pid??'未记录'} / 域 ${r.review.process_generation.domain_id??'未记录'} / 会话 ${r.review.process_generation.session_id??'未记录'}`:r.review?.binding?.generation??r.review?.binding?.start_ticks??'未记录'],["候选哈希",r.review?.candidate_hash]]}/>{r.identified_statements?.length>0&&<details className="record-note"><summary>本次候选的关联语句（{r.identified_statements.length}）</summary>{r.identified_statements.map((row,i)=><p key={i}>{row.statement}</p>)}</details>}</>}
 {pane==='statement'&&<><Tag>{r.stage==='startup'?'运行前':'运行时'}</Tag><p className="record-statement">{r.statement}</p><Fields items={[["策略类型",types[r.policy_type]],["处理方式",effects[r.effect]],["记录状态",statuses[r.status]||r.status],["需要上下文",r.context_required],["操作",r.operations],["对象",r.targets],["识别来源",r.origin==='parameterize'?'审核模板参数化':r.origin==='new_candidate'?'Pi 新候选':r.identified_statements?.some(s=>s.origin!=='authenticated_target_clause')?'Pi 结构化识别':r.classification_origin?.includes('historical')?'已校验增量 / 历史真实条款':r.classification_origin==='authenticated_delta_request'?'历史认证请求 / 增量关联':r.classification_origin==='authenticated_target_clause'?'历史认证目标条款':r.effect==='guidance'?'Pi 任务指导':'Pi 识别 / 控制面结构校验'],["生成时间",when(r.created_at)]]}/>{r.identified_statements?.length>0&&<><h3>识别语句</h3>{r.identified_statements.map((s,i)=><article className="record-evidence" key={i}><p>{s.statement}</p><Fields items={[["类型",types[s.policy_type]],["需要上下文",s.context_required],["依据",s.context_reason],["来源",s.origin==='authenticated_target_clause'?'真实用户目标条款':'Pi 结构化识别']]}/></article>)}</>}{r.explanation&&<details className="record-note"><summary>评估理由</summary><p>{r.explanation}</p></details>}</>}
 {pane==='context'&&<><Fields items={[["需要上下文",r.context_required],["原因",r.context_reason],["范围",({project:'项目工作区',task:'任务'})[r.context_scope]],["触发",r.trigger?.name],["关联轮次",r.trigger?.turn],["上下文版本",r.trigger?.revision]]}/><h3>证据来源</h3>{r.evidence?.map(e=><article className="record-evidence" key={e.id}><Fields items={[["来源",e.role],["路径",e.path],["已读取",e.read_verified],["内容哈希",e.content_hash],["证据 ID",e.id]]}/></article>)}{!r.evidence?.length&&<p className="muted">该指导项没有独立的逐条来源映射。</p>}{r.trigger?.observations?.length>0&&<details className="record-note"><summary>原生上下文观察</summary>{r.trigger.observations.map(o=><Fields key={o.category} items={[["类型",o.type],["事件序号",o.seq],["内容哈希",o.content_hash]]}/>)}</details>}</>}
 {pane==='dsl'&&<><p className="record-statement">{r.statement}</p><Fields items={[["编译",r.compilation.status==='compiled'?'通过':r.compilation.status==='not_applicable'?'不适用':'对应规则尚未登记'],["DSL 来源",({statement_compiler_clauses:'该语句对应的编译子句',compiler_rule_source:'该语句对应的编译规则',semantic_guidance:'语义指导，无 OS DSL',permission_update:'权限变更，无新增拒绝规则',assessment_no_rule:'上下文评估，无逐句规则',unmapped_statement:'该语句尚无可靠规则关联'})[r.compilation.origin]],["规则片段哈希",r.compilation.dsl_hash]]}/>{r.compilation.message&&<p className="muted">{r.compilation.message}</p>}{r.compilation.reused&&<p className="muted">该语句沿用已有规则，本轮没有重新加载。</p>}{r.compilation.fragments?.length>1&&<div className="record-tags" role="tablist" aria-label="本句 DSL 条款">{r.compilation.fragments.map((f,i)=><button className={'button tiny '+(clause===i?'primary':'ghost')} role="tab" aria-selected={clause===i} key={f.id} onClick={()=>setClause(i)}>{f.label}</button>)}</div>}{r.compilation.dsl&&<pre className="record-code">{r.compilation.fragments?.[clause]?.dsl||r.compilation.dsl}</pre>}<NormalTags record={r}/>{r.normalization?.mode==='observe'&&<p className="muted">仅分析关系；本任务保留原始条款。</p>}{r.normalization?.related_statements?.length>0&&<details className="record-note"><summary>相关来源记录</summary>{r.normalization.related_statements.map(id=><button key={id} className="button ghost tiny" onClick={()=>onRecord({id})}>{id.startsWith('startup:')?'运行前':'运行时'} · {id.split(':')[1].slice(-6)} · {id.split(':').at(-1)}</button>)}</details>}</>}
 {pane==='loading'&&<><Fields items={[["记录状态",statuses[r.status]||r.status],["首次加载版本",[...new Set((r.normalization?.links||[]).map(l=>l.first_loading?.version).filter(Boolean))].map(v=>`v${v}`)],["本轮评估版本",r.loading.version?`v${r.loading.version}`:undefined],["本轮改变执行规则",r.normalization?.execution_changed],["已加载该变更",r.loading.loaded],[r.loading.loaded?"加载版本":"评估回执版本",r.loading.version?`v${r.loading.version}`:undefined],["确认回执",r.loading.confirmation],["会话",r.loading.session_id],["策略候选哈希",r.loading.candidate_hash],["启动底线哈希",r.loading.baseline_hash],["启动底线保留",r.loading.baseline_retained],["最近保留的加载版本",r.normalization?.links?.find(l=>l.current_loading?.version)?.current_loading?.version],["来源关联数",r.normalization?.links?.length]]}/>{r.delta&&<><h3>权限变化</h3><Fields items={[["新增保护",r.delta.added_protection],["解除运行时保护",r.delta.removed_protection],["写入范围：之前",r.delta.write_scope_before],["写入范围：之后",r.delta.write_scope_after],["输出可写：之前",r.delta.output_before],["输出可写：之后",r.delta.output_after]]}/></>}{r.loading.binding&&<details className="record-note"><summary>进程绑定</summary><Fields items={[["策略域",r.loading.binding.domain_id],["执行进程",r.loading.binding.runner_pid]]}/></details>}</>}
 </div></>:a?<div className="record-drawer-body"><Fields items={[["记录层",a.category==='os'?'OS 操作':a.category==='tools'?'工具调用':'控制面'],["来源",sources[a.source]],["时间",when(a.time)],["操作",a.operation],["对象",a.target],["结果",results[a.result]||a.result],["原因",a.reason],["工具调用",a.call_id],["实际 PID",a.pid],["策略域",a.domain_id],["策略版本",a.version?`v${a.version}`:undefined],["反馈状态",a.kind==='kernel'?(a.feedback_event_ids?.length?'已送达原生上下文':'未记录送达'):undefined],["反馈回执",a.kind==='kernel'?a.feedback_event_ids:undefined],["关联内核事件",a.kind==='feedback_delivery'?a.kernel_event_ids:undefined]]}/>{a.rule&&<><h3>命中规则</h3><Fields items={[["规则",typeof a.rule==='string'?a.rule:a.rule.name||a.rule.rule_id],["原因",a.rule.reason]]}/>{a.rule.source_text&&<pre className="record-code">{a.rule.source_text}</pre>}</>}{a.policy_sources?.length>0&&<><h3>关联策略语句（{new Set(a.policy_sources.map(s=>s.statement_id)).size}）</h3><div className="record-tags">{[...new Set(a.policy_sources.map(s=>s.statement_id))].map(id=><button key={id} className="button ghost tiny" onClick={()=>onRecord({id})}>{id.startsWith('startup:')?'运行前':'运行时'} · {id.split(':')[1].slice(-6)} · {id.split(':').at(-1)}</button>)}</div></>}<p className="muted">工具成功不等于所有 OS 操作都已放行。OS 区记录内核拒绝与独立效果核验。</p></div>:<div className="record-drawer-body"><Fields items={[["工作区",detail.binding?.workspace],["Session ID",detail.binding?.session_id],["实际进程绑定",detail.binding?.process_verified]]}/>{hook&&<><h3>{hook.name}</h3><Fields items={[["触发事件",hook.events]]}/><ol className="record-hook-flow">{hook.sequence.map(s=><li key={s}>{s}</li>)}</ol></>}</div>}
 </dialog>;
}
export default function ManagedWorkbench({api,post,notify,task,onSelectTask,onCreateTask,onTaskRecord,section='overview',onSection,readOnly=false,sourceTask}) {
 const [data,setData]=useState(null),[binding,setBinding]=useState(null),[matches,setMatches]=useState([]);
 const [archiveOpen,setArchiveOpen]=useState(false),[busy,setBusy]=useState(false),[detail,setDetail]=useState(null);
 const [stage,setStage]=useState(section),[category,setCategory]=useState('os'),[query,setQuery]=useState('');
 const [directoryPage,setDirectoryPage]=useState(0),[now,setNow]=useState(Date.now());
 const [records,setRecords]=useState({records:[]}),[audit,setAudit]=useState({records:[]}),[auditVisible,setAuditVisible]=useState(12);
 const [files,setFiles]=useState({records:[]}),[tools,setTools]=useState({records:[]});
 const [graph,setGraph]=useState(null),[graphVersion,setGraphVersion]=useState(null);
 const [runtimeFilter,setRuntimeFilter]=useState(''),[startupFilter,setStartupFilter]=useState('per_event');
 const [before,setBefore]=useState(null),[constraint,setConstraint]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const key=JSON.stringify([task,stage,category,before,graphVersion]),active=useRef(key),inFlight=useRef(new Set());active.current=key;
 async function load() {
  const current=key;
  if(inFlight.current.has(current))return;
  inFlight.current.add(current);
  try {
   const lookup=task?await api('/api/managed/workspace-binding?task_id='+encodeURIComponent(task)):{binding:null,candidates:(await api('/api/workspace-tasks')).records.filter(t=>t.managed).map(t=>({...t,task_id:t.id}))};
   if(active.current!==current)return;
   setBinding(lookup.binding);setMatches(lookup.candidates);
   if(task&&lookup.binding) {
    const base=`/api/managed/tasks/${task}`;
    const urls=stage==='overview'?[base+'/workbench',base+'/execution-audit?category=os',base+'/execution-audit?category=tools',base+'/domain-graph'+(graphVersion===null?'':'?version='+graphVersion)]:
      [base+'/workbench',stage==='audit'?base+`/execution-audit?category=${category}${before===null?'':`&before=${before}`}`:base+`/strategy-records?stage=${stage}&include_assessments=false${before===null?'':`&before=${before}`}`];
    const [state,list,toolList,graphData]=await Promise.all(urls.map(url=>api(url)));
    if(active.current!==current)return;
    setData(state);
    if(stage==='overview'){setFiles(list);setTools(toolList);setGraph(graphData);}else if(stage==='audit')setAudit(old=>before===null?list:{...list,records:mergeAuditRecords(old.records,list.records)});else setRecords(list);
   }
   setError('');setLoading(false);
  }catch(e){if(active.current===current){setError(e.message);setLoading(false);}}
  finally{inFlight.current.delete(current);}
 }
 useEffect(()=>{setAudit({records:[]});setData(null);setBinding(null);setDetail(null);setBefore(null);setConstraint('');setFiles({records:[]});setTools({records:[]});setGraph(null);setGraphVersion(null);setStage(section);},[task]);
 useEffect(()=>{setLoading(true);load();const timer=setInterval(()=>{setNow(Date.now());load();},3000);return()=>clearInterval(timer);},[key]);
 useEffect(()=>setDirectoryPage(0),[query]);
 useEffect(()=>setAuditVisible(12),[task,category,stage]);
 const run=async fn=>{setBusy(true);try{await fn();await load();}catch(e){notify(e.message);}finally{setBusy(false);}};
 useEffect(()=>{setStage(section);setBefore(null);},[section]);
 const switchStage=value=>{onSection?.(value);setRecords({records:[]});setAudit({records:[]});setLoading(true);setStage(value);setBefore(null);};
 const openRecord=r=>run(async()=>{const current=key,record=await api(`/api/managed/tasks/${task}/strategy-records/${encodeURIComponent(r.id)}`);if(active.current===current)setDetail({record});});
 const openPending=()=>run(async()=>{const current=key,id='runtime:'+pending.job_id;let parent;try{parent=await api(`/api/managed/tasks/${task}/strategy-records/${encodeURIComponent(id)}`);}catch{}if(active.current===current)setDetail({record:pendingReviewRecord(pending,data,parent),pending:true});});
 const openDomain=node=>run(async()=>{const current=key,domain=await api(`/api/managed/tasks/${task}/domains/${encodeURIComponent(node.key)}`);if(active.current===current)setDetail({domain});});
 const historical=readOnly||isTaskEnded(data?.state);
 const change=(...args)=>historical?Promise.reject(new Error('历史任务只读，请查看任务档案')):post(...args);
 const s=data?.state,pending=s?.pending_change||s?.pending_expansion,filter=stage==='startup'?startupFilter:runtimeFilter;
 const shown=filter?records.records.filter(r=>r.policy_type===filter):records.records;
 const filtered=matches.filter(m=>`${names[m.name]||m.name} ${m.task_id} ${m.workspace}`.toLowerCase().includes(query.toLowerCase()));
 const connection=data?connectionView(data,{failed:!!error,now}):null;
 return <div className="content managed-workbench">
  <div className="page-heading"><div><div className="task-title-line">{task&&<button className="text-action back-to-tasks" aria-label="所有任务" onClick={()=>onSelectTask('')}>←</button>}<h1>{task?(names[binding?.name]||binding?.name||'策略工作台'):'策略工作台'}</h1></div><p>{task?`${sourceTask?.source_name||'源工作区名称未记录'} · ${sourceTask?.source_path||'源目录未记录'}`:'选择任务，核验 DSH 执行进程、文件操作与权限变化。'}</p></div><div className="actions"><button className="button primary" onClick={()=>onCreateTask()}>＋ 新建任务</button></div></div>
  {task&&<details className="field-note"><summary>执行快照目录</summary><span className="task-path">{binding?.workspace||sourceTask?.workspace||'未记录'}</span></details>}
  {historical&&<p className="inline-notice warning">历史任务只读，保存的进程与策略回执不代表当前在线。<button className="button ghost tiny" onClick={()=>setArchiveOpen(true)}>查看完整档案</button></p>}
  {error&&<p role="alert" className="inline-notice warning">读取失败：{error}。在线状态未确认，正在重试。</p>}
  {!task&&<section className="task-directory" aria-label="受管任务列表">
   <div className="directory-head"><h2>受管任务 <span>{matches.length}</span></h2><input type="search" aria-label="搜索任务或工作区" placeholder="搜索任务或工作区" value={query} onChange={e=>setQuery(e.target.value)}/></div>
   <div className="directory-columns" aria-hidden="true"><span>任务 / 工作区</span><span>状态</span><span>策略</span><span/></div>
   {filtered.slice(directoryPage*6,directoryPage*6+6).map(m=><button className="task-directory-row" key={m.task_id} onClick={()=>{onSelectTask(m.task_id);}} aria-label={`查看任务 ${m.task_id}`}><div><strong>{names[m.name]||m.name}</strong><span>{m.workspace}</span></div><Tag>{phases[m.phase]||m.phase}</Tag><span className="directory-version">{m.version?`v${m.version}`:'未加载'}</span><span className="directory-arrow" aria-hidden="true">↗</span></button>)}
   {!filtered.length&&<div className="runtime-empty"><strong>{loading?'正在读取任务…':query?'没有匹配的任务':'尚无受管任务'}</strong>{!loading&&!query&&<p>新建任务后，即可查看 Agent 与文件操作的执行关系。</p>}</div>}
   {filtered.length>6&&<div className="directory-pagination"><span>{directoryPage+1} / {Math.ceil(filtered.length/6)}</span><button className="button tiny ghost" disabled={directoryPage===0} onClick={()=>setDirectoryPage(p=>p-1)}>上一页</button><button className="button tiny ghost" disabled={(directoryPage+1)*6>=filtered.length} onClick={()=>setDirectoryPage(p=>p+1)}>下一页</button></div>}
   <p className="directory-footer">列表状态来自任务记录；进入任务后核验实际进程。</p>
  </section>}
  {task&&!data&&!error&&<div className="runtime-empty"><strong>{loading?'正在读取任务…':'当前任务未登记受管 DSH 工作区'}</strong></div>}
  {s&&binding&&<>
   <section className="workspace-strip"><div className="actions"><Tag good={data.policy_verified===true && !error && connection.fresh}>{data.policy_verified===true && !error && connection.fresh?'策略绑定已核验':'策略生效未确认'}</Tag><span className={'connection-label '+connection.tone}>{connection.label}</span><Tag>{s.version?`策略 v${s.version}`:phases[s.phase]||'未加载'}</Tag>{!historical&&s.web_url&&connection.live&&<a className="button primary tiny" href={`/api/managed/tasks/${task}/open`} target="_blank" rel="noreferrer">打开 DSH ↗</a>}{!historical&&s.phase==='policy_review'&&<button className="button primary tiny" onClick={()=>onTaskRecord(task)}>查看并确认场景策略</button>}{!historical&&['prepared','failed'].includes(s.phase)&&<button className="button ghost tiny" disabled={busy} onClick={()=>run(()=>change(`/api/managed/tasks/${task}/start`))}>{s.phase==='failed'?'重新校验并恢复':'生成场景策略'}</button>}{!historical&&!['prepared','ended'].includes(s.phase)&&<button className="button ghost tiny" disabled={busy} onClick={()=>run(()=>change(`/api/managed/tasks/${task}/close`))}>结束任务</button>}</div></section>
   {s.error&&<details className="runtime-problem"><summary>任务已暂停 · 查看原因</summary><p>{s.error}</p></details>}
   {!historical&&s.phase==='failed'&&s.version===0&&<details className="panel"><summary>补充启动任务信息</summary><textarea aria-label="启动任务澄清" rows="3" value={constraint} onChange={e=>setConstraint(e.target.value)}/><button className="button primary" disabled={busy||!constraint.trim()} onClick={()=>run(async()=>{await change(`/api/managed/tasks/${task}/startup/clarify`,{text:constraint});setConstraint('');})}>重新交给 Pi 校验</button></details>}
   <div className="tabs managed-main-tabs" role="tablist" aria-label="策略工作台子页">{[['startup','运行前'],['runtime','运行时'],['overview','执行监控'],['audit','执行审计']].map(([id,label])=><button role="tab" tabIndex={stage===id?0:-1} onKeyDown={e=>tabKeys(e,['startup','runtime','overview','audit'],stage,switchStage)} aria-selected={stage===id} className={stage===id?'active':''} key={id} onClick={()=>switchStage(id)}>{label}</button>)}</div>
   {!historical&&stage==='startup'&&<TaskRecord key={task} task={{id:task,workspace:binding.workspace,name:binding.name}} api={api} post={change} source={sourceTask} notify={notify} onBack={()=>onSelectTask('')} onFollow={()=>switchStage('overview')}/>}
   {stage==='overview'?<RuntimeOverview data={data} binding={binding} files={files} tools={tools} failed={!!error} graph={graph} now={now} onVersion={value=>{setGraph(null);setGraphVersion(value);}} onDomain={openDomain} onProcess={process=>setDetail({process,checked_at:graph.checked_at})} onDetails={()=>setDetail({binding,runtime:data})} onAudit={a=>setDetail({audit:a})} onShowAudit={()=>{setCategory('os');switchStage('audit');}}/>:
    stage!=='audit'?<section className="panel policy-record-panel">
     <div className="record-list-head"><h2>{stage==='startup'?'运行前策略':'运行时策略'}</h2><div className="actions"><button className="text-action" onClick={()=>setDetail({binding,hook:records.hook})}>触发方式 ↗</button><select aria-label={stage==='startup'?'策略类型筛选':'运行时策略类型'} value={stage==='startup'?startupFilter:runtimeFilter} onChange={e=>stage==='startup'?setStartupFilter(e.target.value):setRuntimeFilter(e.target.value)}><option value="">全部语句</option><option value="per_event">OS 执行策略</option><option value="semantic_only">任务指导</option></select></div></div>
     {!historical&&pending&&stage==='runtime'&&<div className="record-pending"><Tag>{pendingChangeLabel(pending)}</Tag><button className="button ghost tiny" onClick={openPending}>查看候选</button><button className="button primary tiny" disabled={busy} onClick={()=>run(()=>change(`/api/managed/tasks/${task}/changes/${pending.job_id}/review`,{decision:'approve',expected_hash:pending.hash}))}>批准并加载</button><button className="button ghost tiny" disabled={busy} onClick={()=>run(()=>change(`/api/managed/tasks/${task}/changes/${pending.job_id}/review`,{decision:'reject',expected_hash:pending.hash}))}>拒绝变更</button><input aria-label="变更澄清" value={constraint} onChange={e=>setConstraint(e.target.value)} placeholder="补充澄清"/><button className="button ghost tiny" disabled={busy||!constraint.trim()} onClick={()=>run(()=>change(`/api/managed/tasks/${task}/changes/${pending.job_id}/review`,{decision:'clarify',expected_hash:pending.hash,text:constraint}))}>提交澄清</button></div>}
     {stage==='runtime'&&<p className="record-caption">{runtimeCaption(s)}<span>{records.counts?.no_change||0} 次评估无需调整权限</span></p>}
     <div className="policy-record-list">{shown.map(r=><button className="policy-record" key={r.id} onClick={()=>openRecord(r)}><div className="record-line"><div><b>{r.targets?.length?r.targets.map(t=>t.replace(binding.workspace+'/','')).join('、'):effects[r.effect]||types[r.policy_type]}</b><small>{when(r.created_at)} · {effects[r.effect]||types[r.policy_type]} · {recordPermissionLabel(r)}</small></div><Tag>{statuses[r.status]||r.status}</Tag><span className="record-open" aria-hidden="true">↗</span></div></button>)}</div>
     {!shown.length&&<p className="record-empty">{loading?'正在读取记录…':'尚无此类策略记录。'}</p>}
     {before!==null&&<button className="button ghost tiny" onClick={()=>setBefore(null)}>返回最新记录</button>}{records.next_cursor&&<button className="button ghost tiny" onClick={()=>setBefore(records.next_cursor)}>更早记录</button>}
    </section>:<section className="panel policy-record-panel">
     <div className="record-list-head"><h2>{category==='os'?'OS 文件操作':category==='tools'?'工具调用':'控制面记录'}</h2><select aria-label="审计层" value={category} onChange={e=>{setAudit({records:[]});setLoading(true);setCategory(e.target.value);setBefore(null);}}><option value="os">OS 文件操作</option><option value="tools">工具调用</option><option value="control">控制面记录</option></select></div>
     {category==='os'&&<p className="field-note">已收集的文件拒绝与独立效果核验；不覆盖全部系统调用。</p>}<div className="audit-record-list">{audit.records.slice(0,auditVisible).map(a=><button className="audit-record compact-audit" key={a.id} onClick={()=>setDetail({audit:a})}><div><b>{auditOperation(a)} · {a.target?a.target.replace(binding.workspace+'/',''):'对象未记录'}</b><small>{auditIdentity(a)}</small></div><Tag>{results[a.result]||a.result}</Tag><time>{when(a.time)}</time><span aria-hidden="true">↗</span></button>)}</div>
     {!audit.records.length&&<p className="record-empty">{loading?'正在读取记录…':'尚无此层审计记录。'}</p>}{before!==null&&<button className="button ghost tiny" onClick={()=>{setAudit({records:[]});setAuditVisible(12);setLoading(true);setBefore(null);}}>返回最新记录</button>}{(auditVisible<audit.records.length||audit.next_cursor)&&<button className="button ghost tiny" disabled={loading} onClick={()=>{const next=auditPageAction(audit.records.length,auditVisible,audit.next_cursor);setAuditVisible(next.visible);if(next.type==='fetch'){setLoading(true);setBefore(next.cursor);}}}>再显示 12 条</button>}<p className="field-note">已显示 {Math.min(auditVisible,audit.records.length)} / {audit.records.length} 条已读取记录</p>
    </section>}
  </>}
  {archiveOpen&&<ArchiveDrawer task={task} api={api} onClose={()=>setArchiveOpen(false)}/>}
  {detail&&(detail.runtime||detail.domain||detail.process?<RuntimeDetails key={detail.domain?.key||detail.process?.key||'connection'} detail={detail} onClose={()=>setDetail(null)}/>:<Drawer key={detail.record?.id||detail.audit?.id||'hook'} detail={detail} onRecord={openRecord} onClose={()=>setDetail(null)}/>)}
 </div>;
}
