import React,{useCallback,useEffect,useRef,useState} from 'react';
import PolicyInputForm from './PolicyInputForm.jsx';
const states={queued:'排队中',running:'生成中',completed:'生成完成',ready:'候选已生成',partial:'部分编译 / 失败',failed:'失败',cancelled:'已取消',interrupted:'已中断',approved:'已审核',pending_review:'待审核',rejected:'已拒绝',complete:'二审完整',description:'描述性内容',unreviewed:'未二审',needs_clarification:'待澄清',required:'需本机适配',not_required:'无需适配',compiled:'已编译',requires_context:'需本机适配',unsupported:'指导项 / 无执行 DSL',compile_failed:'编译失败',compile_timeout:'编译超时',backend_missing:'编译器不可用',invalid_candidate:'规则校验失败'};
const levels={semantic_only:'语义规则',content:'内容规则',per_event:'单事件规则',cross_event:'跨事件规则',not_applicable:'不适用'};
const scopes={self_contained:'通用',project:'项目 / 仓库',task:'任务',not_applicable:'不适用'};
const short=x=>x?.slice(0,12)||'—';
const tag=v=><span className={'tag '+(['complete','compiled','approved'].includes(v)?'good':'warn')}>{states[v]||v}</span>;
function Detail({row,onClose}){
 const ref=useRef(null),focus=useRef(document.activeElement);
 useEffect(()=>{const node=ref.current;node.showModal();return()=>{node.close();if(focus.current?.isConnected)focus.current.focus()}},[]);
 const s=row.record.statement,a=row.artifact;
 return <dialog className="record-dialog" ref={ref} aria-labelledby="generation-detail-title" onCancel={e=>{e.preventDefault();onClose()}}><div className="panel-head"><h2 id="generation-detail-title">策略来源与产物 · v{row.version}</h2><button className="button ghost" onClick={onClose}>关闭</button></div><div className="record-dialog-body"><p>{s.text_zh||s.text_original}</p><blockquote>{s.source_quote}</blockquote>{s.evidence_spans?.map((span,i)=><blockquote key={i}>L{span.line_start}–{span.line_end}：{span.source_quote}</blockquote>)}<p>{row.record.origin.repository} · {row.record.origin.path} · L{s.line_start}–{s.line_end}</p>{row.record.origin.url&&<a href={row.record.origin.url+'#L'+s.line_start} target="_blank" rel="noreferrer">查看固定来源 ↗</a>}<p>二审：{states[s.completeness]||s.completeness}</p>{s.review_issues?.map((issue,i)=><p key={i}>{issue}</p>)}<h3>适配与加载条件</h3><pre>{JSON.stringify(row.adaptation,null,2)}</pre>{row.load_blockers.map((x,i)=><p key={i}>{x}</p>)}<details><summary>参数来源与范围适配</summary><pre>{JSON.stringify(row.record.resolved_context,null,2)}</pre></details><details><summary>校验与编译</summary><pre>{JSON.stringify({checks:a?.policy_record?.compile_check,compilation:row.compilation},null,2)}</pre></details><details><summary>模型调用记录</summary><pre>{JSON.stringify(a?.llm_runs||[],null,2)}</pre></details><details><summary>PolicyIR</summary><pre>{JSON.stringify(a?.policy_ir||null,null,2)}</pre></details><details><summary>策略伪代码</summary><pre>{a?.pseudo_code||'尚未生成'}</pre></details><details open><summary>ActPlane DSL</summary><pre>{a?.actplane_dsl||'无执行 DSL'}</pre></details><p>源文件 hash：{row.record.origin.content_hash}<br/>语句 hash：{row.statement_hash}<br/>产物 hash：{row.artifact_hash||'—'}</p>{(row.review_blockers||[]).map((x,i)=><p key={i} className="error">{x}</p>)}{row.error&&<p className="error">{row.error}</p>}</div></dialog>
}
export default function PolicyGeneration({api,post,tasks,busy,action,notify,initialStatementId,onConsumed}){
 const [repo,setRepo]=useState('https://github.com/zeroclaw-labs/zeroclaw'),[ref,setRef]=useState('main'),[extra,setExtra]=useState(''),[mode,setMode]=useState('github');
 const [runs,setRuns]=useState([]),[runId,setRunId]=useState(()=>sessionStorage.getItem('historyGeneration')||''),[run,setRun]=useState(null),[page,setPage]=useState({items:[],total:0}),[offset,setOffset]=useState(0);
 const [filters,setFilters]=useState({q:'',execution_level:'',context_scope:'',completeness:'',adaptation:'',loadable:''}),[detail,setDetail]=useState(null),[selected,setSelected]=useState({});
 const [includeInstructions,setIncludeInstructions]=useState(true);
 const [inputExpanded,setInputExpanded]=useState(false);
 const sequence=useRef(0);
 const load=useCallback(async()=>{const n=++sequence.current;const list=await api('/api/history/generations');if(n!==sequence.current)return;setRuns(list);if(!runId)return;const [r,p]=await Promise.all([api('/api/history/generations/'+runId),api('/api/history/generations/'+runId+'/results?'+new URLSearchParams({...filters,limit:'20',offset:String(offset)}))]);if(n!==sequence.current)return;setRun(r);setPage(p)},[api,runId,filters,offset]);
 useEffect(()=>{load().catch(e=>notify(e.message));const timer=setInterval(()=>load().catch(()=>{}),4000);return()=>{sequence.current++;clearInterval(timer)}},[load,notify]);
 const chooseRun=id=>{setInputExpanded(false);setRunId(id);sessionStorage.setItem('historyGeneration',id);setOffset(0);setSelected({});setDetail(null)};
 const create=body=>action(async()=>{const result=await post('/api/history/generations',body);chooseRun(result.id);notify('统一生成已排队：'+short(result.id))});
 useEffect(()=>{if(initialStatementId){create({statement_version_id:initialStatementId,request_key:crypto.randomUUID()});onConsumed()}},[initialStatementId]);
 const review=(rows,decision)=>action(async()=>{await post('/api/history/generations/'+runId+'/review',{decision,reviewed_by:'研究者',items:rows.map(r=>({statement_version_id:r.statement_version_id,expected_statement_hash:r.statement_hash,artifact_id:r.artifact_id,expected_artifact_hash:r.artifact_hash}))});setSelected({});await load();notify(decision==='approve'?'语句与产物已共同审核':'已拒绝候选')});
 const change=(name,value)=>{setFilters({...filters,[name]:value});setOffset(0)};
 const picked=Object.values(selected);
 return <div className="policy-generation"><div className="panel-head"><h2>产出的策略</h2>{runId&&<button className="button primary" aria-expanded={inputExpanded} onClick={()=>setInputExpanded(v=>!v)}>新建生成</button>}</div>{(!runId||inputExpanded)&&<section className="panel history-form"><div className="panel-head"><div><h2>策略生成</h2><p>一次输入，自动完成采集、抽取、完整性二审和候选生成；最后统一审核。</p></div></div><div className="segmented"><button className={mode==='github'?'sel':''} onClick={()=>setMode('github')}>GitHub 文档</button><button className={mode==='manual'?'sel':''} onClick={()=>setMode('manual')}>输入策略语句</button></div>{mode==='github'&&<><div className="history-fields"><label>GitHub 仓库<input value={repo} onChange={e=>setRepo(e.target.value)}/></label><label>分支 / 标签 / commit<input value={ref} onChange={e=>setRef(e.target.value)}/></label><label>附加文档路径（每行一个，可选）<textarea rows="2" value={extra} onChange={e=>setExtra(e.target.value)} placeholder="SECURITY.md"/></label></div><label className="inline-check"><input type="checkbox" checked={includeInstructions} onChange={e=>setIncludeInstructions(e.target.checked)}/>同时采集仓库中的 AGENTS.md / CLAUDE.md</label><button className="button primary" disabled={busy||!repo||!ref} onClick={()=>create({repo_url:repo,ref,include_instruction_files:includeInstructions,additional_paths:extra.split(/[\n,]/).map(x=>x.trim()).filter(Boolean),request_key:crypto.randomUUID()})}>开始生成策略</button><p className="field-note">自动采集 AGENTS.md / CLAUDE.md，锁定实际 commit。需要运行环境参数的记录先标记，后续适配。</p></>}</section>}
 {(!runId||inputExpanded)&&mode==='manual'&&<PolicyInputForm tasks={tasks} post={post} busy={busy} action={action} onSaved={async r=>{const result=await post('/api/history/generations',{statement_version_id:r.id,request_key:crypto.randomUUID()});chooseRun(result.id);notify('策略输入已进入二审与生成')}}/>}
 <section className="panel generation-summary"><label>生成批次<select aria-label="选择生成批次" value={runId} onChange={e=>chooseRun(e.target.value)}><option value="">选择批次</option>{runs.map(r=><option key={r.id} value={r.id}>{short(r.id)} · {states[r.status]||r.status} · {r.input?.repo_url||'单条策略'}</option>)}</select></label>{run&&<><div className="button-row">{tag(run.status)}<span>阶段：{run.stage}</span>{['queued','running'].includes(run.status)&&<button className="button tiny ghost" disabled={busy||!!run.cancel_requested} onClick={()=>action(async()=>{await post('/api/history/generations/'+runId+'/cancel');await load()})}>取消生成</button>}{['failed','partial','cancelled','interrupted'].includes(run.status)&&<button className="button tiny ghost" disabled={busy} onClick={()=>action(async()=>{await post('/api/history/generations/'+runId+'/retry');await load()})}>从检查点重试</button>}</div>{run.source?.commit&&<p className="field-note">固定 commit：{run.source.commit}</p>}{run.error&&<p className="error">{run.error}</p>}<p className="field-note">{Object.entries(run.statistics||{}).map(([k,v])=>`${states[k]||k} ${v}`).join(' · ')} · 详细作业见采集与审计</p></>}</section>
 <div className="generation-filters"><label>搜索<input placeholder="策略、来源或文件路径" value={filters.q} onChange={e=>change('q',e.target.value)}/></label>{[['execution_level','执行层级',levels],['context_scope','上下文范围',scopes],['completeness','完整性',{complete:'二审完整',needs_clarification:'待澄清',unreviewed:'未二审'}],['adaptation','本机适配',{required:'需本机适配',complete:'已适配',not_required:'无需适配'}],['loadable','加载状态',{yes:'可加载',no:'不可加载'}]].map(([key,title,options])=><label key={key}>{title}<select aria-label={'筛选'+title} value={filters[key]} onChange={e=>change(key,e.target.value)}><option value="">全部</option>{Object.entries(options).map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>)}</div>
 <div className="records-pagination"><span>{page.total} 条策略</span><div className="button-row"><button className="button tiny primary" disabled={busy||!picked.length} onClick={()=>review(picked,'approve')}>最终审核通过（{picked.length}）</button><button className="button tiny ghost" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-20))}>上一页</button><button className="button tiny ghost" disabled={offset+page.items.length>=page.total} onClick={()=>setOffset(offset+20)}>下一页</button></div></div>
 <section className="panel table-panel"><div className="table-scroll"><table className="generation-table"><thead><tr><th>选择</th><th>完整策略语句</th><th>来源</th><th>层级 / 范围</th><th>审核与加载条件</th></tr></thead><tbody>{page.items.map(row=>{const s=row.record.statement,canApprove=s.completeness==='complete'&&!(row.review_blockers||[]).length&&!!row.artifact&&(!row.artifact.actplane_dsl||row.compile_state==='compiled');return <tr key={row.statement_version_id}><td><input type="checkbox" aria-label={'选择候选 '+row.statement_version_id} disabled={!canApprove} checked={!!selected[row.statement_version_id]} onChange={e=>setSelected(values=>{const next={...values};if(e.target.checked)next[row.statement_version_id]=row;else delete next[row.statement_version_id];return next})}/></td><td className="strategy-text"><button className="record-open" onClick={()=>setDetail(row)}>来源 / 伪代码 / DSL</button><p>{s.text_zh||s.text_original}</p>{s.text_zh&&<small>{s.text_original}</small>}<div className="record-actions"><button className="button tiny primary" disabled={busy||!canApprove||row.review_status==='approved'} onClick={()=>review([row],'approve')}>最终审核通过</button><button className="button tiny ghost" disabled={busy||row.review_status==='rejected'} onClick={()=>review([row],'reject')}>拒绝</button></div></td><td>{row.record.origin.repository}<small>{row.record.origin.path}:L{s.line_start}–{s.line_end}</small><small>{short(row.record.origin.commit)}</small></td><td>{levels[s.enforcement_level]}<small>{scopes[s.context_requirement]}</small></td><td>{tag(s.completeness)} {tag(row.review_status)}<small>{row.adaptation.state==='required'?tag('required'):row.compile_state?tag(row.compile_state):'未生成 DSL'}</small>{row.load_blockers.map((x,i)=><small key={i}>{x}</small>)}{row.error&&<small className="error">{row.error}</small>}</td></tr>})}{!page.items.length&&<tr><td colSpan="5" className="empty-row">{runId?'暂无符合条件的策略，生成结果会自动出现。':'输入来源开始生成，或选择已有批次。'}</td></tr>}</tbody></table></div></section>{detail&&<Detail row={detail} onClose={()=>setDetail(null)}/>}</div>
}
