import React,{useEffect,useRef,useState} from 'react';
import BootstrapFailureNotice from './BootstrapFailureNotice.jsx';
import {startupRecoveryPath,startupRecoveryRequest,pollStartupRecovery} from './startupRecovery.mjs';
export default function StartupRecovery({task,api,post,onOpenTask,fallbackError}){
 const [recovery,setRecovery]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0),[selectedCandidate,setSelectedCandidate]=useState(''),seq=useRef(0);
 useEffect(()=>{const id=++seq.current;setRecovery(null);setSelectedCandidate('');setError('');const stop=pollStartupRecovery({read:()=>api(startupRecoveryPath(task)),onData:data=>{if(id===seq.current){setRecovery(data);setError('');}},onError:e=>{if(id===seq.current){setRecovery(null);setSelectedCandidate('');setError(e.message);}}});return()=>{seq.current++;stop();};},[task,api,retry]);
 const candidate=recovery?.candidate||recovery?.link||(recovery?.candidates||[]).find(c=>c.task_id===selectedCandidate);
 async function recover(action){const current=seq.current;setBusy(true);setError('');try{const result=await post(startupRecoveryPath(task),startupRecoveryRequest(recovery,action,candidate));const target=result?.target?.task_id;if(!target)throw new Error('恢复接口未返回目标任务，未切换当前任务。');if(current===seq.current)onOpenTask(target);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const progress=recovery?.link&&["generating","prepared","failed"].includes(recovery.link.status)?recovery.link:null;
 const canAct=recovery?.eligible===true&&!!recovery?.origin?.context_hash&&!!recovery?.origin?.manifest_hash&&typeof onOpenTask==='function';
 return <>{Array.isArray(recovery?.candidates)&&recovery.candidates.length>1&&!recovery.candidate&&!recovery.link&&<label className="startup-recovery-choice">恢复候选<select aria-label="选择恢复候选" value={selectedCandidate} disabled={busy} onChange={e=>setSelectedCandidate(e.target.value)}><option value="">选择同源待审核任务</option>{recovery.candidates.map(c=><option key={c.task_id} value={c.task_id}>{c.task_id} · 候选 {c.proposal_id||c.proposal_hash?.slice(0,8)}</option>)}</select></label>}<BootstrapFailureNotice failure={recovery?.failure||{error:fallbackError}} candidateId={candidate?.task_id} recoveryReady={candidate?.status==="awaiting_review"} progressTaskId={progress?.task_id} progressStatus={progress?.status} onViewProgress={typeof onOpenTask==="function"?onOpenTask:undefined} canViewCandidate={canAct&&candidate?.status==='awaiting_review'} canRegenerate={canAct&&!["generating","prepared"].includes(progress?.status)} onViewCandidate={()=>recover('reuse')} onRegenerate={()=>recover('rebuild')} busy={busy} blockedReason={recovery?.blocked_reason}/>{!recovery&&!error&&<p role="status" className="field-note">正在核对可用的恢复候选…</p>}{error&&<p role="alert" className="field-note">恢复状态：{error} <button className="button ghost tiny" disabled={busy} onClick={()=>setRetry(n=>n+1)}>重新读取</button></p>}</>;
}
