import RecordBadge from './RecordBadge.jsx';
import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {archiveListWorkspace} from './archivePresentation.mjs';
import {timeLabel,displayName,phaseName} from './taskPresentation.mjs';
import ArchiveDrawer,{ArchiveReplay} from './TaskArchiveDetails.jsx';
import {scheduleArchiveScroll} from './archiveRecords.mjs';
import './taskConsole.css';
import './archive.css';
export {ArchiveDrawer};
export default function TaskArchive({api,navigation,navigate}){
 const [rows,setRows]=useState([]),[index,setIndex]=useState({total:0,pages:1}),[error,setError]=useState('');const scroll=useRef(0),active=navigation.page==='history',scrollKey='agentscope.archiveScroll:'+navigation.query+':'+navigation.filter+':'+navigation.listPage;
 useEffect(()=>{try{scroll.current=Number(sessionStorage.getItem(scrollKey))||0;}catch{}},[scrollKey]);
 useEffect(()=>{if(!active)return;let alive=true;const status=navigation.filter==='history'?'ended':navigation.filter==='active'?'active':'all';api(`/api/task-archives?q=${encodeURIComponent(navigation.query)}&status=${status}&page=${navigation.listPage}&limit=12`).then(r=>{if(alive){setRows(r.records||[]);setIndex({total:r.total||0,pages:r.pages||1});setError('');}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[active,api,navigation.query,navigation.filter,navigation.listPage]);
 useLayoutEffect(()=>{if(!active)return;return scheduleArchiveScroll({task:navigation.archiveTask,position:scroll.current,heading:document.getElementById('archive-replay-heading'),window,requestFrame:requestAnimationFrame,cancelFrame:cancelAnimationFrame});},[navigation.archiveTask,active,rows.length,scrollKey]);
 const shown=rows,page=navigation.listPage,pages=index.pages;
 if(active&&navigation.archiveTask)return <div className="content task-console"><ArchiveReplay key={navigation.archiveTask} task={navigation.archiveTask} tasks={rows} api={api} pane={navigation.archivePane} onPaneChange={archivePane=>navigate({archivePane})} onTaskChange={archiveTask=>navigate({archiveTask,archivePane:'startup'})} onBack={()=>navigate({archiveTask:''})}/></div>;
 return <div className="content task-console"><div className="task-console-heading"><div><h1>任务历史</h1><p>回放运行前策略、运行时策略、执行审计和进程与域图。</p></div></div>{error&&<p role="alert" className="inline-notice warning">读取失败：{error}</p>}<section className="panel task-section"><div className="task-section-heading"><h2>任务回放</h2><div className="task-table-filters"><button className="button ghost tiny" title="旧 RQ5 验收任务：OpenAgentSafety 场景" onClick={()=>navigate({query:'OpenAgentSafety',filter:'all',listPage:0})}>OpenAgentSafety 场景</button><input type="search" aria-label="搜索历史任务" value={navigation.query} onChange={e=>navigate({query:e.target.value,listPage:0})} placeholder="搜索任务或工作区"/><select aria-label="历史任务状态" value={navigation.filter} onChange={e=>navigate({filter:e.target.value,listPage:0})}><option value="history">已结束</option><option value="active">未结束（含失败）</option><option value="all">全部状态</option></select></div></div>{navigation.filter==='history'&&<p className="field-note">当前仅显示已结束任务；旧任务可能未记录结束状态。 <button className="button ghost tiny" onClick={()=>navigate({filter:'all',listPage:0})}>查看全部旧任务</button></p>}<div className="table-scroll"><table className="task-record-table"><thead><tr><th>创建 / 结束</th><th>任务对象</th><th>Agent / 工作区</th><th>处理结果</th><th>版本</th><th/></tr></thead><tbody>{shown.map(r=><tr key={r.id}><td>{r.created_at?timeLabel(r.created_at):'未记录'}<small>{r.ended_at?timeLabel(r.ended_at):'结束时间未记录'}</small></td><td><b>{displayName(r)}</b><small title={r.id}>{r.id.slice(0,8)}</small></td><td>{r.source?.agent_id||r.agent||'未记录'}<small>{r.workspace?.name||archiveListWorkspace(r)}</small></td><td><RecordBadge>{phaseName(r.phase||r.status)}</RecordBadge></td><td><RecordBadge tone="purple" dot={false} mono>{r.version?'v'+r.version:'—'}</RecordBadge></td><td><button id={"archive-open-"+r.id} className="button tiny ghost" onClick={()=>{scroll.current=window.scrollY;try{sessionStorage.setItem(scrollKey,String(scroll.current));}catch{}navigate({archiveTask:r.id,archivePane:'startup'});}}>回放任务</button></td></tr>)}{!shown.length&&<tr><td colSpan={6} className="task-empty">暂无匹配任务。</td></tr>}</tbody></table></div><div className="task-table-foot"><span>{index.total} 个任务</span><div className="actions"><button className="button ghost tiny" disabled={!page} onClick={()=>navigate({listPage:page-1})}>上一页</button><span>{page+1} / {pages}</span><button className="button ghost tiny" disabled={page+1>=pages} onClick={()=>navigate({listPage:page+1})}>下一页</button></div></div></section></div>;
}
