import React,{useEffect,useRef,useState} from 'react';
import {archiveListWorkspace} from './archivePresentation.mjs';
import {timeLabel,displayName,phaseName} from './taskPresentation.mjs';
import ArchiveDrawer from './TaskArchiveDetails.jsx';
import './taskConsole.css';
import './archive.css';
export {ArchiveDrawer};
export default function TaskArchive({api,navigation,navigate}){
 const [rows,setRows]=useState([]),[index,setIndex]=useState({total:0,pages:1}),[error,setError]=useState('');const scroll=useRef(0),active=navigation.page==='history',scrollKey='agentscope.archiveScroll:'+navigation.query+':'+navigation.filter+':'+navigation.listPage;
 useEffect(()=>{try{scroll.current=Number(sessionStorage.getItem(scrollKey))||0;}catch{}},[scrollKey]);
 useEffect(()=>{if(!active)return;let alive=true;const status=navigation.filter==='history'?'ended':navigation.filter==='active'?'active':'all';api(`/api/task-archives?q=${encodeURIComponent(navigation.query)}&status=${status}&page=${navigation.listPage}&limit=12`).then(r=>{if(alive){setRows(r.records||[]);setIndex({total:r.total||0,pages:r.pages||1});setError('');}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[active,api,navigation.query,navigation.filter,navigation.listPage]);
 useEffect(()=>{if(active&&!navigation.archiveTask)requestAnimationFrame(()=>window.scrollTo(0,scroll.current));},[navigation.archiveTask,active,rows.length,scrollKey]);
 const shown=rows,page=navigation.listPage,pages=index.pages;
 return <div className="content task-console"><div className="task-console-heading"><div><h1>任务历史</h1><p>每个任务保留一份完整档案。</p></div></div>{error&&<p role="alert" className="inline-notice warning">读取失败：{error}</p>}<section className="panel task-section"><div className="task-section-heading"><h2>任务档案</h2><div className="task-table-filters"><input type="search" aria-label="搜索历史任务" value={navigation.query} onChange={e=>navigate({query:e.target.value,listPage:0})} placeholder="搜索任务或工作区"/><select aria-label="历史任务状态" value={navigation.filter} onChange={e=>navigate({filter:e.target.value,listPage:0})}><option value="history">已结束</option><option value="active">待启动与执行中</option><option value="all">全部状态</option></select></div></div><div className="table-scroll"><table className="task-record-table"><thead><tr><th>创建 / 结束</th><th>任务对象</th><th>Agent / 工作区</th><th>处理结果</th><th>版本</th><th/></tr></thead><tbody>{shown.map(r=><tr key={r.id}><td>{r.created_at?timeLabel(r.created_at):'未记录'}<small>{r.ended_at?timeLabel(r.ended_at):'结束时间未记录'}</small></td><td><b>{displayName(r)}</b></td><td>{r.source?.agent_id||r.agent||'未记录'}<small>{r.workspace?.name||archiveListWorkspace(r)}</small></td><td>{phaseName(r.phase||r.status)}</td><td>{r.version?'v'+r.version:'—'}</td><td><button id={"archive-open-"+r.id} className="button tiny ghost" onClick={()=>{scroll.current=window.scrollY;try{sessionStorage.setItem(scrollKey,String(scroll.current));}catch{}navigate({archiveTask:r.id});}}>完整档案</button></td></tr>)}{!shown.length&&<tr><td colSpan={6} className="task-empty">暂无匹配任务。</td></tr>}</tbody></table></div><div className="task-table-foot"><span>{index.total} 个任务</span><div className="actions"><button className="button ghost tiny" disabled={!page} onClick={()=>navigate({listPage:page-1})}>上一页</button><span>{page+1} / {pages}</span><button className="button ghost tiny" disabled={page+1>=pages} onClick={()=>navigate({listPage:page+1})}>下一页</button></div></div></section>{active&&navigation.archiveTask&&<ArchiveDrawer key={navigation.archiveTask} task={navigation.archiveTask} api={api} onRestore={()=>navigate({page:'workbench',task:navigation.archiveTask,archiveTask:'',workbenchSection:'overview'})} onClose={()=>navigate({archiveTask:''})}/>}</div>;
}
