import React,{useEffect,useState,useRef} from 'react';
import {FieldRecords,WorkspaceFiles} from './AgentWorkspaces.jsx';
import {displayName,phaseName,timeLabel,visibleTasks,proposalRows,policySummary} from './taskPresentation.mjs';
import './taskConsole.css';
import {instanceState,visibleInstances} from './consoleState.mjs';
import WorkspaceSceneRead from './WorkspaceSceneRead.jsx';

export default function TaskHub({api,post,notify,tasks,task,onSelectTask,onFollowTask,onAgents,workspaceSeed='',agentSeed='native-dsh',onContext,createOnly=false}) {
  const [tab,setTab]=useState(task?'records':'create'),[records,setRecords]=useState([]),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[page,setPage]=useState(0);
  const [agents,setAgents]=useState([]),[selectedAgent,setSelectedAgent]=useState(agentSeed),[workspaces,setWorkspaces]=useState([]),[workspace,setWorkspace]=useState(workspaceSeed);
  const [inventory,setInventory]=useState(null),[loadingFiles,setLoadingFiles]=useState(false),[revision,setRevision]=useState(0);
  const [clock,setClock]=useState(Date.now()),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const dsh=agents.find(a=>a.id===selectedAgent),connected=instanceState(dsh,clock).live,current=tasks.find(t=>t.id===task)||records.find(t=>t.id===task);
  const selectedInventory=inventory?.workspace?.id===workspace?inventory:null;
  useEffect(()=>{onContext?.({agent:selectedAgent,workspace});},[selectedAgent,workspace]);
  useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{setWorkspace(workspaceSeed);if(!task)setTab('create');},[workspaceSeed]);
  useEffect(()=>setSelectedAgent(agentSeed),[agentSeed]);
  useEffect(()=>{if(task)setTab('records');},[task]);
  async function reload(){const [a,t]=await Promise.all([api('/api/workspace-agents'),api('/api/workspace-tasks')]);setAgents(a.agents);setRecords(t.records);if(a.agents.some(x=>x.id===selectedAgent&&x.connected))setWorkspaces((await api(`/api/workspace-agents/${encodeURIComponent(selectedAgent)}/workspaces`)).workspaces);else setWorkspaces([]);}
  useEffect(()=>{let active=true;const load=async()=>{try{const [a,t]=await Promise.all([api('/api/workspace-agents'),api('/api/workspace-tasks')]);if(!active)return;setAgents(a.agents);setRecords(t.records);if(a.agents.some(x=>x.id===selectedAgent&&x.connected)){const w=await api(`/api/workspace-agents/${encodeURIComponent(selectedAgent)}/workspaces`);if(active)setWorkspaces(w.workspaces);}setError('');}catch(e){if(active){setError(e.message);setAgents(old=>old.map(a=>({...a,connected:false,status:'unknown'})));}}};load();const timer=setInterval(load,3000);return()=>{active=false;clearInterval(timer);};},[api,selectedAgent]);
  useEffect(()=>{let active=true;setInventory(null);if(!workspace)return;setLoadingFiles(true);api(`/api/agent-workspaces/${workspace}/files`).then(value=>{if(active){setInventory(value);if(workspaceSeed===workspace&&value.workspace?.agent_id&&value.workspace.agent_id!=='dsh')setSelectedAgent(value.workspace.agent_id);setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoadingFiles(false);});return()=>{active=false;};},[workspace,revision,api]);
  useEffect(()=>setPage(0),[query,filter]);
  async function run(fn){setBusy(true);try{await fn();await reload();}catch(e){notify(e.message);}finally{setBusy(false);}}
  async function create(body){setBusy(true);try{const created=await post(`/api/agent-workspaces/${encodeURIComponent(workspace)}/tasks`,body);onSelectTask(created.id);setTab('records');await post(`/api/managed/tasks/${created.id}/start`);await reload();notify('场景目标已采用，Pi 正在生成策略；确认后才启动执行');}catch(e){notify(e.message);throw e;}finally{setBusy(false);}}
  const shown=visibleTasks(records,query,filter),pages=Math.max(1,Math.ceil(shown.length/12));
  return <div className="content task-console">
    <div className="task-console-heading"><div><h1>策略工作台</h1><p>选择工作区，让 Agent 先读取场景并识别任务，再生成策略供你确认。</p></div><button className="button ghost" onClick={onAgents}>查看 Agent 与工作区</button></div>
    {!createOnly&&<div role="tablist" aria-label="任务模块" className="tabs task-hub-tabs"><button role="tab" aria-selected={tab==='create'} className={tab==='create'?'active':''} onClick={()=>{setTab('create');onSelectTask('');}}>新建任务</button><button role="tab" aria-selected={tab==='records'} className={tab==='records'?'active':''} onClick={()=>setTab('records')}>任务记录</button></div>}
    {error&&<p role="alert" className="inline-notice warning">{error}</p>}
    {tab==='create'&&<div className="task-create-grid">
      <section className="panel task-section"><div className="task-section-heading"><h2>选择 Agent 与工作区</h2></div>
        <label>执行 Agent<select aria-label="执行 Agent" value={selectedAgent} onChange={e=>{setSelectedAgent(e.target.value);setWorkspace('');}}><option value="">尚未连接 Agent</option>{visibleInstances(agents,tasks).map(a=><option key={a.id} value={a.id}>{a.name} · {a.kind==='managed'?'受管':'原生'}</option>)}</select></label>
        {!connected&&<button type="button" className="button primary" disabled={busy||!dsh?.available} onClick={()=>run(()=>post(`/api/workspace-agents/${encodeURIComponent(selectedAgent)}/check`))}>检查所选 Agent</button>}
        <label>Agent 工作区<select aria-label="Agent 工作区" value={workspace} disabled={!connected} onChange={e=>setWorkspace(e.target.value)}><option value="">选择要读取的工作区</option>{workspaces.map(w=><option key={w.id} value={w.id} disabled={!w.readable}>{displayName(w)} · {w.path}</option>)}</select></label>
        {!workspaces.length&&connected&&<p className="field-note">暂无工作区。到“Agent 与工作区”添加目录并放入项目文件。</p>}
        {workspace&&<><FieldRecords items={[["源目录",inventory?.workspace?.path],["文件清单",loadingFiles?'正在检查':inventory?`${inventory.file_count} 个文件`:'尚未检查']]}/><details className="task-workspace-files"><summary>工作区文件（{inventory?.file_count??'—'}）</summary><WorkspaceFiles inventory={inventory} loading={loadingFiles} onRefresh={()=>setRevision(v=>v+1)}/></details></>}
      </section>
      <WorkspaceSceneRead key={`${selectedAgent}:${workspace}`} workspaceId={workspace} agentId={selectedAgent} manifestHash={selectedInventory?.manifest_hash} sourceGeneration={selectedInventory?.workspace?.instance_generation} canRead={!!(connected&&!loadingFiles&&selectedInventory?.file_count)} api={api} post={post} onUseDraft={create} onOpenTask={onSelectTask} onRefresh={()=>setRevision(v=>v+1)} busy={busy}/>
    </div>}
    {tab==='records'&&(!task?<section className="panel task-section"><div className="task-section-heading"><h2>任务记录</h2><div className="task-table-filters"><input aria-label="搜索任务" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索任务、工作区"/><select aria-label="任务状态" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">全部状态</option><option value="active">待启动与执行中</option><option value="history">历史任务</option></select></div></div>
      <div className="table-scroll"><table className="task-record-table"><thead><tr><th>任务</th><th>Agent / 工作区</th><th>状态</th><th>策略版本</th><th>更新时间</th><th></th></tr></thead><tbody>{shown.slice(page*12,page*12+12).map(t=><tr key={t.id}><td><b>{displayName(t)}</b><small>{t.id}</small></td><td>DSH<small className="task-path">{t.source_name||t.workspace}</small></td><td>{phaseName(t.phase)}</td><td>{t.version?`v${t.version}`:'未加载'}</td><td>{timeLabel(t.updated_at)}</td><td><button className="button tiny ghost" onClick={()=>onSelectTask(t.id)}>查看记录</button></td></tr>)}{!shown.length&&<tr><td colSpan={6} className="task-empty">暂无匹配任务。</td></tr>}</tbody></table></div>
      <div className="task-table-foot"><span>{shown.length} 条记录</span><div className="actions"><button className="button tiny ghost" disabled={!page} onClick={()=>setPage(page-1)}>上一页</button><span>{page+1} / {pages}</span><button className="button tiny ghost" disabled={page+1>=pages} onClick={()=>setPage(page+1)}>下一页</button></div></div>
    </section>:<TaskRecord key={task} task={current||{id:task}} source={records.find(t=>t.id===task)} api={api} post={post} notify={notify} onBack={()=>onSelectTask('')} onFollow={()=>onFollowTask(task)}/>)}
  </div>;
}

export function TaskRecord({task,source,api,post,notify,onBack,onFollow}) {
  const [data,setData]=useState(null),[versions,setVersions]=useState([]),[managed,setManaged]=useState(null),[pane,setPane]=useState('policies'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
  const proposal=data?.proposals?.[0],job=data?.jobs?.[0],rows=proposalRows(proposal),draft=proposal?.proposal?.draft;
  async function reload(){const [bootstrap,v,w]=await Promise.allSettled([api(`/api/tasks/${task.id}/bootstrap`),api(`/api/tasks/${task.id}/versions`),api(`/api/managed/tasks/${task.id}/workbench`)]);if(bootstrap.status==='fulfilled')setData(bootstrap.value);if(v.status==='fulfilled')setVersions(v.value);if(w.status==='fulfilled')setManaged(w.value);setError(bootstrap.status==='rejected'&&w.status==='rejected'?'此历史任务没有启动前 Pi 候选记录。':'');}
  useEffect(()=>{let active=true;const load=async()=>{const [bootstrap,v,w]=await Promise.allSettled([api(`/api/tasks/${task.id}/bootstrap`),api(`/api/tasks/${task.id}/versions`),api(`/api/managed/tasks/${task.id}/workbench`)]);if(!active)return;if(bootstrap.status==='fulfilled')setData(bootstrap.value);if(v.status==='fulfilled')setVersions(v.value);if(w.status==='fulfilled')setManaged(w.value);setError(bootstrap.status==='rejected'&&w.status==='rejected'?'此历史任务没有启动前 Pi 候选记录。':'');setLoading(false);};load();const timer=setInterval(load,3000);return()=>{active=false;clearInterval(timer);};},[task.id,api]);
  async function run(fn){setBusy(true);try{await fn();await reload();}catch(e){notify(e.message);}finally{setBusy(false);}}
  const state=managed?.state,phase=state?.phase||source?.phase||task.status;
  const tools=data?.tool_events||[];
  if(loading)return <section className="panel task-section"><p role="status" className="task-empty">正在读取任务记录与策略状态…</p></section>;
  return <>
    <div className="task-section-heading task-record-heading"><button className="button ghost" onClick={onBack}>返回任务记录</button><div className="actions">{managed&&<button className="button ghost" onClick={onFollow}>跟进 Agent 执行</button>}{state?.phase==='prepared'&&<button className="button primary" disabled={busy} onClick={()=>run(()=>post(`/api/managed/tasks/${task.id}/start`))}>生成场景策略</button>}{state?.phase==='policy_review'&&proposal?.state==='validated'&&<button className="button primary" disabled={busy} onClick={()=>run(()=>post(`/api/managed/tasks/${task.id}/startup/confirm`,{expected_context_hash:data.context.context_hash,expected_proposal_hash:proposal.content_hash}))}>确认策略并启动 Agent</button>}</div></div>
    <section className="panel task-section task-record-summary"><div className="task-section-heading"><h2>{displayName(task)}</h2><span className="tag">{phaseName(phase)}</span></div><FieldRecords items={[["任务 ID",task.id],["执行 Agent",'DSH'],["源工作区",source?.source_path||data?.context?.workspace_source?.path||'历史任务工作区'],["任务工作区",task.workspace||source?.workspace],["策略状态",state?.version?['running','recovering'].includes(state.phase)?`最近加载 v${state.version}` : `历史加载 v${state.version}`:proposal?.state==='validated'?'已校验，尚未加载':'尚未加载'],["执行会话",state?.session_id||'尚未建立'],["创建时间",timeLabel(task.created_at||source?.created_at)],["更新时间",timeLabel(task.updated_at||source?.updated_at)]]}/>
      {task.prompt&&<details className="task-row-detail"><summary>任务目标与约束</summary><p>{task.prompt}</p></details>}
      {state?.error&&<p role="alert" className="inline-notice warning">{phase==='failed'?'暂停原因':'历史诊断'}：{state.error}</p>}
    </section>
    {error&&<p role="status" className="field-note">{error}</p>}
    {<details open ><summary>启动前策略</summary><section className="panel task-section"><div className="task-section-heading"><h2>启动前策略记录</h2><span className="field-note">{rows.length} 条执行规则 · {draft?.guidance?.length||0} 条任务指导</span></div>
      <div className="table-scroll"><table className="task-record-table task-policy-table"><thead><tr><th>序号</th><th>策略要求</th><th>保护对象</th><th>校验</th><th>详情</th></tr></thead><tbody>{rows.map(r=><tr key={r.number}><td>{r.number}</td><td>{policySummary(r)}</td><td>{r.paths.map(p=><span key={p} className="task-path">{p.replace((task.workspace||'')+'/','')}</span>)}</td><td>{proposal.state==='validated'?'已校验':'待澄清'}</td><td><details className="task-row-detail"><summary>查看</summary><FieldRecords items={[["原始语句",r.statement],["来源",r.decision==='parameterize'?'历史模板参数化':r.decision==='reuse'?'历史规则复用':'当前任务识别'],["依据",r.reason],["证据数量",r.evidence_ids?.length||0]]}/>{r.dsl&&<pre className="record-code">{r.dsl}</pre>}</details></td></tr>)}{!rows.length&&<tr><td colSpan={5} className="task-empty">{['queued','running'].includes(job?.status)?'Pi 正在读取文件并生成策略…':'尚无执行规则记录。'}</td></tr>}</tbody></table></div>
      {!!draft?.guidance?.length&&<details className="task-row-detail task-guidance"><summary>任务指导（{draft.guidance.length} 条）</summary><div className="table-scroll"><table className="task-record-table"><thead><tr><th>序号</th><th>指导内容</th><th>执行方式</th></tr></thead><tbody>{draft.guidance.map((text,i)=><tr key={i}><td>{i+1}</td><td>{text}</td><td>Agent 行为指导</td></tr>)}</tbody></table></div></details>}
      {proposal?.state==='needs_clarification'&&<p className="inline-notice warning">待澄清：{proposal.proposal?.gaps?.join('；')}</p>}
    </section></details>}
    {<details ><summary>工作区文件证据</summary><section className="panel task-section"><div className="task-section-heading"><h2>本次任务读取的文件</h2></div><div className="table-scroll"><table className="task-record-table"><thead><tr><th>文件</th><th>类型</th><th>读取范围</th><th>证据状态</th></tr></thead><tbody>{(data?.context?.assets||[]).map(a=><tr key={a.mapped_path}><td className="task-path">{a.relative_path||a.path}</td><td>{a.kind==='binary'?'二进制文件':'项目文件'}</td><td>{a.kind==='binary'?'文件元数据':'项目内容'}</td><td>已登记快照</td></tr>)}{!data?.context?.assets?.length&&<tr><td colSpan={4} className="task-empty">没有已保存的文件快照。</td></tr>}</tbody></table></div></section></details>}
    {<details ><summary>生成过程与工具结果</summary><section className="panel task-section"><div className="task-section-heading"><h2>Pi 生成记录</h2></div><div className="table-scroll"><table className="task-record-table"><thead><tr><th>作业</th><th>状态</th><th>创建时间</th><th>公开诊断</th></tr></thead><tbody>{data?.jobs?.map(j=><tr key={j.id}><td>{j.id}</td><td>{({completed:'已完成',running:'生成中',queued:'排队中',failed:'失败',interrupted:'已中断'})[j.status]||j.status}</td><td>{timeLabel(j.created_at)}</td><td>{j.error||'—'}</td></tr>)}</tbody></table></div><h3 className="task-subheading">工具读取与校验</h3><div className="table-scroll"><table className="task-record-table"><thead><tr><th>时间</th><th>步骤</th><th>结果</th></tr></thead><tbody>{tools.slice(-40).reverse().map((t,i)=><tr key={t.id||i}><td>{timeLabel(t.occurred_at)}</td><td>{({get_task_context:'读取任务上下文',list_policy_sources:'列出工作区证据',read_policy_source:'读取证据',search_historical_policies:'检索历史策略',get_enforcement_capabilities:'检查执行能力',validate_policy_draft:'校验候选',submit_policy:'提交策略候选'})[t.tool]||t.tool}</td><td>{t.output?.valid===false?'未通过':typeof t.output?.diagnostic==='string'&&t.output.diagnostic||'已记录'}</td></tr>)}</tbody></table></div></section></details>}
    {<details ><summary>策略版本</summary><section className="panel task-section"><div className="task-section-heading"><h2>策略版本记录</h2></div><div className="table-scroll"><table className="task-record-table"><thead><tr><th>版本</th><th>编译</th><th>审核</th><th>批准人</th><th>时间</th></tr></thead><tbody>{versions.map(v=><tr key={v.id}><td>v{v.version}</td><td>{v.compile_state==='compiled'?'已编译':v.compile_state}</td><td>{({approved:'已批准',pending_review:'待审核',loaded:'已加载',rejected:'已拒绝'})[v.status]||v.status}</td><td>{v.approved_by||'—'}</td><td>{timeLabel(v.created_at)}</td></tr>)}{!versions.length&&<tr><td colSpan={5} className="task-empty">尚无策略版本；生成与校验不等于已加载。</td></tr>}</tbody></table></div></section></details>}
  </>;
}
