import React,{useEffect,useRef} from 'react';
import {tabKeys} from './consoleState.mjs';
// Shared presentation only: callers own all data, labels, and actions.
export function PolicyRecordRow({id,title,caption,status,onOpen,disabled=false,statementSummary=false}){return <button id={id} className="policy-record" disabled={disabled} onClick={onOpen}><div className="record-line"><div><b className={statementSummary?"record-statement-summary":undefined}>{title}</b><small>{caption}</small></div><span className="record-tag">{status}</span><span className="record-open" aria-hidden="true">↗</span></div></button>;}
export function AuditRecordRow({id,title,identity,result,time,onOpen}){return <button id={id} className="audit-record compact-audit" onClick={onOpen}><div><b>{title}</b><small>{identity}</small></div><span className="record-tag">{result}</span><time>{time}</time><span aria-hidden="true">↗</span></button>;}
export function RuntimeModeTabs({mode,onMode,children,scope='runtime',label='运行对象'}){const modes={graph:'关系图',files:'OS 文件操作',processes:'关联进程',scope:'权限范围'};return <div className="runtime-table-head"><div className="runtime-segments" role="tablist" aria-label={label}>{Object.entries(modes).map(([id,text])=><button key={id} id={`${scope}-${id}`} role="tab" aria-selected={mode===id} aria-controls={`${scope}-panel`} tabIndex={mode===id?0:-1} onKeyDown={e=>tabKeys(e,Object.keys(modes),mode,onMode)} onClick={()=>onMode(id)}>{text}</button>)}</div>{children}</div>;}
export function RecordDrawerFrame({title,label,onClose,children}){const ref=useRef(null),origin=useRef(null);useEffect(()=>{origin.current=document.activeElement;ref.current?.showModal();ref.current?.querySelector('button')?.focus();return()=>{ref.current?.close();requestAnimationFrame(()=>{if(origin.current?.isConnected)origin.current.focus({preventScroll:true});});};},[]);return <dialog ref={ref} className="record-drawer" aria-label={label||title} onCancel={onClose}><div className="record-drawer-head"><h2>{title}</h2><button className="button ghost tiny" onClick={onClose}>关闭</button></div>{children}</dialog>;}

export function RecordFields({items,showMissing=false}){return <dl className="record-fields">{items.filter(([,v])=>showMissing||v!==undefined&&v!==null).map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{v===undefined||v===null?'未记录':typeof v==='boolean'?(v?'是':'否'):Array.isArray(v)?v.join('、')||'无':v&&typeof v==='object'&&!React.isValidElement(v)?JSON.stringify(v):v||'无'}</dd></React.Fragment>)}</dl>;}
export function RecordDetailTabs({tabs,pane,onPane,label='策略记录详情',scope='record-detail'}){return <div className="record-drawer-tabs" role="tablist" aria-label={label}>{tabs.map(([id,text])=><button key={id} id={`${scope}-${id}`} role="tab" aria-selected={pane===id} aria-controls={`${scope}-panel`} tabIndex={pane===id?0:-1} onKeyDown={e=>tabKeys(e,tabs.map(([key])=>key),pane,onPane)} onClick={()=>onPane(id)}>{text}</button>)}</div>;}

export function workbenchPolicyTitle(record,workspace,fallback){
 if(record.targets?.length)return record.targets.map(target=>target.replace(workspace+'/','')).join('、');
 const text=typeof record.statement==='string'?record.statement.replace(/\s+/g,' ').trim():'';
 const chars=Array.from(text);return chars.length?chars.slice(0,100).join('')+(chars.length>100?'…':''):fallback;
}
