/* UI acceptance against the isolated service; optional historical fixture replay never applies real grants. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const {spawnSync}=require('node:child_process');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const [task,output,fixturePath]=process.argv.slice(2);
const launch=spawnSync('wsl.exe',['-d','Ubuntu','-u','root','--','/opt/agentscope/.venv/bin/python',
  '/opt/agentscope-history-v1/scripts/scope_browser_ticket.py'],{encoding:'utf8',windowsHide:true});
if(launch.status!==0)throw new Error('Could not create local browser session');
(async()=>{
  fs.mkdirSync(output,{recursive:true});
  const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'});
  try {
    const context=await browser.newContext({viewport:{width:1440,height:1000}});
    const page=await context.newPage(),errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    const url=new URL(JSON.parse(launch.stdout.trim()).url);url.searchParams.set('task',task);
    await page.goto(url.toString());
    await page.getByRole('heading',{name:'结束前的权限',exact:true}).waitFor();
    const realScope=await page.evaluate(async id=>await (await fetch('/api/tasks/'+id+'/scope-manager')).json(),task);
    assert.equal(await page.getByLabel('管理员口令',{exact:true}).count(),0);
    assert.equal(await page.evaluate(()=>sessionStorage.getItem('agentscopeAdminToken')),null);
    assert.equal(await page.evaluate(()=>location.hash),'');
    assert.ok((await context.cookies()).find(c=>c.name==='agentscopeLocalSession')?.httpOnly);
    assert.equal(await page.locator('.scope-pane .scope-permissions tbody tr').count(),6);
    assert.equal(await page.locator('.scope-stages button.done').count(),5);
    assert.equal(await page.locator('.sidebar').isVisible(),false);
    assert.equal(await page.getByRole('button',{name:'结束并撤销',exact:true}).count(),0);
    await page.screenshot({path:path.join(output,'scope-desktop.png'),fullPage:true});
    await page.getByRole('button',{name:'任务详情',exact:true}).click();
    await page.getByRole('dialog').waitFor({state:'visible'});
    assert.ok((await page.getByRole('dialog').innerText()).includes('自建 Python 标准库项目'));
    assert.ok((await page.getByRole('dialog').innerText()).includes('实际执行域文件探针与内核事件'));
    await page.keyboard.press('Escape');
    await page.getByRole('button',{name:'任务授权，查看记录'}).click();
    const drawer=page.getByRole('dialog');
    await drawer.waitFor({state:'visible'});
    assert.ok((await drawer.innerText()).includes('历史核验快照'));
    assert.equal(await drawer.locator('tr').filter({hasText:'frontend'}).getByText('可读写',{exact:true}).count(),1);
    assert.equal(await drawer.locator('pre').isVisible(),false);
    await page.keyboard.press('Escape');
    assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')),'任务授权，查看记录');
    await page.getByRole('tab',{name:'当前权限',exact:true}).focus();await page.keyboard.press('ArrowRight');
    assert.equal(await page.getByRole('tab',{name:'变更审核',exact:true}).getAttribute('aria-selected'),'true');
    await page.getByRole('button',{name:'查看已处理申请',exact:true}).click();
    assert.equal(await page.locator('.scope-request-row').count(),realScope.deltas.filter(d=>d.review_status!=='pending').length);
    await page.getByRole('button',{name:'开放报告目录，查看申请'}).first().click();
    await drawer.waitFor({state:'visible'});
    assert.equal(await drawer.getByRole('button',{name:'批准并应用'}).count(),0);
    assert.ok((await drawer.innerText()).includes('候选说明'));
    assert.equal(await drawer.locator('.scope-pi-explanation p').isVisible(),false);
    await page.screenshot({path:path.join(output,'scope-review-drawer.png'),fullPage:true});
    await page.keyboard.press('Escape');
    await page.getByRole('tab',{name:'变更审核',exact:true}).focus();await page.keyboard.press('ArrowRight');
    const assertCompact=async()=>{
      const lines=await page.locator('.scope-records li').allTextContents();
      assert.ok(lines.length<=8);
      assert.ok(lines.every(s=>s.length<90));
      assert.ok(lines.every(s=>!s.includes('/s/')&&!s.includes('proposal_hash')&&!s.includes('schema')));
    };
    await assertCompact();await page.screenshot({path:path.join(output,'scope-records.png'),fullPage:true});
    await page.getByRole('button',{name:'下一页记录'}).click();await assertCompact();
    await page.getByRole('button',{name:'拦截记录',exact:true}).click();await assertCompact();
    await page.locator('.scope-record-open').first().click();await drawer.waitFor({state:'visible'});
    assert.equal(await drawer.locator('pre').isVisible(),false);
    await drawer.locator('summary').click();assert.ok((await drawer.locator('pre').innerText()).includes('domain_id'));
    await page.keyboard.press('Escape');
    await page.getByRole('tab',{name:'当前权限',exact:true}).click();
    // Switch a real prepared task and prove refresh follows the new URL rather than the old task.
    const tasks=await page.evaluate(async()=>await (await fetch('/api/tasks')).json());
    const prepared=tasks.find(t=>t.repo==='AgentScope/custom-scope-demo'&&t.status==='prepared');
    assert.ok(prepared);
    await page.getByLabel('选择 Demo 任务').selectOption(prepared.id);
    await page.getByRole('heading',{name:'默认文件权限',exact:true}).waitFor();
    await page.reload();await page.getByRole('heading',{name:'默认文件权限',exact:true}).waitFor();
    assert.equal(new URL(page.url()).searchParams.get('task'),prepared.id);
    assert.equal(await page.getByLabel('选择 Demo 任务').inputValue(),prepared.id);
    assert.equal(await page.locator('.scope-stages button.done').count(),0);
    await page.getByLabel('选择 Demo 任务').selectOption(task);
    await page.getByRole('heading',{name:'结束前的权限',exact:true}).waitFor();
    await page.setViewportSize({width:423,height:900});
    const noOverflow=async()=>{
      const size=await page.evaluate(()=>({document:document.documentElement.scrollWidth,viewport:innerWidth}));
      assert.ok(size.document<=size.viewport,JSON.stringify(size));
    };
    await noOverflow();await page.screenshot({path:path.join(output,'scope-narrow.png'),fullPage:true});
    await page.getByRole('tab',{name:'执行记录',exact:true}).click();await assertCompact();await noOverflow();
    await page.screenshot({path:path.join(output,'scope-records-narrow.png'),fullPage:true});
    await page.getByRole('tab',{name:'变更审核',exact:true}).click();
    await page.getByRole('button',{name:'已处理',exact:true}).click();
    await page.getByRole('button',{name:'开放报告目录，查看申请'}).first().click();
    await drawer.waitFor({state:'visible'});await noOverflow();
    await page.screenshot({path:path.join(output,'scope-review-narrow.png'),fullPage:true});
    await page.keyboard.press('Escape');
    const replay=[];
    if(fixturePath){
      const fixture=JSON.parse(fs.readFileSync(fixturePath,'utf8'));
      let state=structuredClone(fixture.S1),posted=null;
      const replayPage=await context.newPage();replayPage.on('pageerror',e=>errors.push(e.message));
      await replayPage.route('**/api/tasks/'+task+'/scope-manager',route=>route.fulfill({json:state}));
      await replayPage.route('**/scope-manager/changes',async route=>{
        posted=route.request().postDataJSON();await route.fulfill({json:{accepted:true}});
      });
      const replayUrl='http://127.0.0.1:18003/?view=scope-demo&task='+task;
      await replayPage.goto(replayUrl);await replayPage.getByRole('heading',{name:'当前有效权限',exact:true}).waitFor();
      await replayPage.getByRole('button',{name:'调整任务权限',exact:true}).click();
      await replayPage.getByLabel('你的要求').fill('暂时只修改 backend，保护 tests/config。');
      await replayPage.getByRole('button',{name:'生成权限候选',exact:true}).click();
      await replayPage.getByRole('dialog').waitFor({state:'hidden'});
      assert.equal(posted.expected_snapshot,state.session.active_snapshot_id);assert.equal(posted.kind,'restrict');
      replay.push('new requirement uses confirmed base');
      state=structuredClone(fixture.S3_rejected);
      const delta=structuredClone(state.deltas.find(d=>d.kind==='expand'));
      delta.review_status='pending';delta.apply_status='not_applied';delta.verify_status='unverified';delta.base_snapshot_id=state.session.active_snapshot_id;
      delta.message_revision=state.session.message_revision;delta.process_epoch=state.session.process_epoch;
      state.deltas=[delta];state.jobs=[{delta_id:delta.id,status:'completed'}];
      await replayPage.reload();await replayPage.getByRole('tab',{name:/变更审核/}).click();
      await replayPage.getByRole('button',{name:'开放报告目录，查看申请'}).click();
      assert.ok(await replayPage.getByRole('button',{name:'批准并应用',exact:true}).isEnabled());
      assert.equal(await replayPage.getByRole('dialog').locator('.scope-diff-list>div').count(),1);
      assert.ok((await replayPage.getByRole('dialog').innerText()).includes('output'));
      replay.push('pending expansion shows actual diff and review action');
      await replayPage.screenshot({path:path.join(output,'scope-pending-review.png'),fullPage:true});
      delta.message_revision--;
      await replayPage.reload();await replayPage.getByRole('tab',{name:/变更审核/}).click();
      await replayPage.getByRole('button',{name:'开放报告目录，查看申请'}).click();
      assert.equal(await replayPage.getByRole('button',{name:'批准并应用',exact:true}).count(),0);
      await replayPage.getByRole('button',{name:'澄清并重新分析',exact:true}).click();
      assert.ok((await replayPage.getByLabel('你的要求').inputValue()).includes(delta.input.text));
      replay.push('stale candidate cannot approve; clarification preserves user message');
      state=structuredClone(fixture.S2);state.session.phase='waiting_constraint';state.session.gate='waiting_constraint';
      state.deltas=[];await replayPage.reload();
      await replayPage.getByText('等待收紧生效',{exact:true}).first().waitFor();
      replay.push('restriction remains waiting after rejection');
      state.session.gate='failed';state.effective=false;
      await replayPage.reload();await replayPage.getByRole('heading',{name:'最近核验的权限',exact:true}).waitFor();
      assert.equal(await replayPage.getByRole('heading',{name:'当前有效权限',exact:true}).count(),0);
      replay.push('failed apply shows historical scope without false activation');
      await replayPage.close();
    }
    assert.equal(errors.length,0,errors.join(';'));
    const result={task,noPasswordEntry:'passed',httpOnlySession:'passed',desktop:'passed',narrow423:'passed',compactRecords:'passed',
      historicalScope:'passed',endedCannotApprove:'passed',taskSource:'passed',tabs:'passed',keyboard:'passed',drawerFocus:'passed',taskSwitchRefresh:'passed',
      fixtureReplay:replay.length?replay:'not run',pageErrors:errors};
    fs.writeFileSync(path.join(output,'scope-ui.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
  } finally {await browser.close();}
})().catch(e=>{console.error(e.message);process.exit(1)});
